/*=============================================================================
  Fonte.........: dbo.SP_HDS0000_RFIS01
  Objetivo......: Base analitica para conciliacao dos impostos fiscais com a
                  contabilizacao, por grupo, filial, conta e LP.
  Banco esperado: CCW2SA_171703_PR_PD
  Grupo..........: 20 - Grupo Agronelli
  Objetos.......: SFT200, SF3200, CT2200 e CT5200
  Validado em...: 2026-08-28 (metadados e amostras, somente leitura, dbcode).

  Saidas para exportacao em abas:
    1. REGRAS_LP: regras das LPs que referenciam as contas informadas.
    2. FISCAL: impostos da SFT e SF3 em linhas, sem somar as duas origens.
    3. CONTABIL: movimentos da CT2 agrupados por filial, conta, LP e origem.

  Importante:
    - SFT e SF3 representam granularidades diferentes do fiscal. A procedure
      identifica a origem, mas nao soma ambas como se fossem fatos distintos.
    - O sinal fiscal ainda nao e imposto automaticamente. O sentido depende da
      operacao e da regra da LP; VALOR_FISCAL_ORIGINAL preserva o valor gravado.
    - A conta apresentada no fiscal e uma conta candidata semantica. A regra
      efetiva deve ser confirmada na aba REGRAS_LP antes da conciliacao final.
    - Nenhum objeto do banco e criado por este arquivo ate haver autorizacao
      explicita para executar o CREATE OR ALTER PROCEDURE.
=============================================================================*/
/* Exemplo:
EXEC dbo.SP_HDS0000_RFIS01
    @DATA_INICIAL = '20260801',
    @DATA_FINAL = '20260831',
    @FILIAL = NULL;
*/
CREATE OR ALTER PROCEDURE dbo.SP_HDS0000_RFIS01
    @DATA_INICIAL VARCHAR(10) = NULL,
    @DATA_FINAL VARCHAR(10) = NULL,
    @FILIAL VARCHAR(6) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT @FILIAL = NULLIF(LTRIM(RTRIM(@FILIAL)), '');

    DECLARE @DATA_INICIAL_DATE DATE;
    DECLARE @DATA_FINAL_DATE DATE;

    SELECT @DATA_INICIAL = NULLIF(LTRIM(RTRIM(@DATA_INICIAL)), '');
    SELECT @DATA_FINAL = NULLIF(LTRIM(RTRIM(@DATA_FINAL)), '');

    SELECT @DATA_INICIAL_DATE = CASE
        WHEN @DATA_INICIAL IS NULL
        THEN DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)
        ELSE COALESCE
        (
            TRY_CONVERT(DATE, @DATA_INICIAL, 112),
            TRY_CONVERT(DATE, @DATA_INICIAL, 103),
            TRY_CONVERT(DATE, @DATA_INICIAL, 23)
        )
    END;

    SELECT @DATA_FINAL_DATE = CASE
        WHEN @DATA_FINAL IS NULL
        THEN EOMONTH(GETDATE())
        ELSE COALESCE
        (
            TRY_CONVERT(DATE, @DATA_FINAL, 112),
            TRY_CONVERT(DATE, @DATA_FINAL, 103),
            TRY_CONVERT(DATE, @DATA_FINAL, 23)
        )
    END;

    IF @DATA_INICIAL_DATE IS NULL OR @DATA_FINAL_DATE IS NULL
    BEGIN
        THROW 50001, 'Datas invalidas. Use AAAAMMDD, DD/MM/AAAA ou AAAA-MM-DD.', 1;
    END;

    IF @DATA_INICIAL_DATE > @DATA_FINAL_DATE
    BEGIN
        THROW 50001, 'DATA_INICIAL nao pode ser maior que DATA_FINAL.', 1;
    END;

    -- Normaliza para comparar com os campos de data VARCHAR(8) do Protheus.
    SELECT @DATA_INICIAL = CONVERT(VARCHAR(8), @DATA_INICIAL_DATE, 112);
    SELECT @DATA_FINAL = CONVERT(VARCHAR(8), @DATA_FINAL_DATE, 112);

    CREATE TABLE #CONTAS_IMPOSTOS
    (
        CONTA VARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
        DESCRICAO_CONTA VARCHAR(80) COLLATE DATABASE_DEFAULT NOT NULL,
        IMPOSTO_CANDIDATO VARCHAR(30) COLLATE DATABASE_DEFAULT NULL
    );

    INSERT INTO #CONTAS_IMPOSTOS (CONTA, DESCRICAO_CONTA, IMPOSTO_CANDIDATO)
    VALUES
        ('201010901', 'IRRF A RECOLHER', 'IRRF'),
        ('201010902', 'ICMS A RECOLHER', 'ICMS'),
        ('201010903', 'RETENCOES P/ A SEGURIDADE SOCIAL', 'INSS'),
        ('201010904', 'CONTRIBUICAO SINDICAL A RECOLHER', NULL),
        ('201010905', 'ISSQN A RECOLHER', 'ISS'),
        ('201010906', 'RETENCOES PIS COFINS CSL - PCC', 'PCC'),
        ('201010908', 'ICMS ST A RECOLHER', 'ICMS ST'),
        ('201010909', 'ICMS S/ FRETE A PAGAR', 'ICMS FRETE'),
        ('201010911', 'ICMS DIF ALIQUOTA A RECOLHER', 'ICMS DIFAL'),
        ('201010913', 'IPI A RECOLHER - CIRCULANTE', 'IPI'),
        ('201010914', 'PIS A RECOLHER - CIRCULANTE', 'PIS'),
        ('201010915', 'COFINS A RECOLHER - CIRCULANTE', 'COFINS'),
        ('201010918', 'PARCELAMENTOS IMPOSTOS FEDERAIS', NULL),
        ('202010301', 'PARCELAMENTOS IMPOSTOS FEDERAIS', NULL),
        ('101021001', 'ICMS A RECUPERAR', 'ICMS'),
        ('101021002', 'PIS NAO CUMULATIVO A RECUPERAR', 'PIS'),
        ('101021003', 'COFINS NAO CUMULATIVO A RECUPERAR', 'COFINS'),
        ('101021004', 'IPI A RECUPERAR', 'IPI'),
        ('101021005', 'ICMS A RECUPERAR - CIAP', 'ICMS CIAP'),
        ('101021006', 'ICMS ST A RECUPERAR', 'ICMS ST'),
        ('101021105', 'ISS A RECUPERAR', 'ISS'),
        ('101020707', 'AJUSTE A DEBITO EFD CONTRIBUICOES', 'AJUSTE EFD');

    CREATE TABLE #REGRAS_LP
    (
        GRUPO_EMPRESA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        LP VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        SEQUENCIA VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        DESCRICAO_LP VARCHAR(40) COLLATE DATABASE_DEFAULT NOT NULL,
        DEBITO VARCHAR(500) COLLATE DATABASE_DEFAULT NOT NULL,
        CREDITO VARCHAR(500) COLLATE DATABASE_DEFAULT NOT NULL,
        FORMULA_VALOR VARCHAR(500) COLLATE DATABASE_DEFAULT NOT NULL,
        ORIGEM VARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL,
        TABELA_ORIGEM VARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL,
        RECNO_ORIGEM VARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL
    );

    INSERT INTO #REGRAS_LP
    SELECT '20', CT5_FILIAL, CT5_LANPAD, CT5_SEQUEN, CT5_DESC,
           CT5_DEBITO, CT5_CREDIT, CT5_VLR01, CT5_ORIGEM,
           CT5_TABORI, CT5_RECORI
    FROM dbo.CT5200
    WHERE D_E_L_E_T_ = '';

    -- Aba 1: cada regra pode referenciar mais de uma conta da lista.
    SELECT
        R.GRUPO_EMPRESA,
        RTRIM(R.FILIAL) AS FILIAL,
        RTRIM(R.LP) AS LP,
        RTRIM(R.SEQUENCIA) AS SEQUENCIA,
        RTRIM(R.DESCRICAO_LP) AS DESCRICAO_LP,
        C.CONTA,
        C.DESCRICAO_CONTA,
        CASE
            WHEN R.DEBITO LIKE '%' + C.CONTA + '%' THEN 'DEBITO'
            WHEN R.CREDITO LIKE '%' + C.CONTA + '%' THEN 'CREDITO'
        END AS LADO_CONTA,
        RTRIM(R.DEBITO) AS REGRA_DEBITO,
        RTRIM(R.CREDITO) AS REGRA_CREDITO,
        RTRIM(R.FORMULA_VALOR) AS REGRA_VALOR,
        RTRIM(R.ORIGEM) AS REGRA_ORIGEM,
        RTRIM(R.TABELA_ORIGEM) AS REGRA_TABELA_ORIGEM,
        RTRIM(R.RECNO_ORIGEM) AS REGRA_RECNO_ORIGEM
    FROM #REGRAS_LP AS R
    INNER JOIN #CONTAS_IMPOSTOS AS C
        ON R.DEBITO LIKE '%' + C.CONTA + '%'
        OR R.CREDITO LIKE '%' + C.CONTA + '%'
    WHERE (@FILIAL IS NULL OR R.FILIAL IN ('', @FILIAL))
    ORDER BY R.GRUPO_EMPRESA, R.FILIAL, R.LP, R.SEQUENCIA, C.CONTA;

    CREATE TABLE #FISCAL
    (
        GRUPO_EMPRESA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        ORIGEM_FISCAL VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        DATA_FISCAL VARCHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        TIPO_MOVIMENTO VARCHAR(1) COLLATE DATABASE_DEFAULT NOT NULL,
        DOCUMENTO VARCHAR(9) COLLATE DATABASE_DEFAULT NOT NULL,
        SERIE VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        PARTICIPANTE VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        LOJA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        CFOP VARCHAR(5) COLLATE DATABASE_DEFAULT NOT NULL,
        IDENTIFICADOR VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        RECNO_FISCAL BIGINT NOT NULL,
        IMPOSTO VARCHAR(30) COLLATE DATABASE_DEFAULT NOT NULL,
        CAMPO_VALOR VARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL,
        VALOR_FISCAL_ORIGINAL DECIMAL(19, 4) NOT NULL,
        CONTA_CANDIDATA VARCHAR(20) COLLATE DATABASE_DEFAULT NULL
    );

    ;WITH SFT AS
    (
        SELECT '20' GRUPO_EMPRESA, 'SFT' ORIGEM_FISCAL, FT_FILIAL FILIAL,
               FT_ENTRADA DATA_FISCAL, FT_TIPOMOV TIPO_MOVIMENTO,
               FT_NFISCAL DOCUMENTO, FT_SERIE SERIE, FT_CLIEFOR PARTICIPANTE,
               FT_LOJA LOJA, FT_CFOP CFOP, FT_IDENTF3 IDENTIFICADOR,
               R_E_C_N_O_ RECNO_FISCAL, FT_VALICM, FT_ICMSRET, FT_ICMSDIF,
               FT_VALIPI, FT_VALPIS, FT_VALCOF, FT_VALCSL, FT_VALIRR,
               FT_VALINS, FT_ISSSUB, FT_VRETPIS, FT_VRETCOF, FT_VRETCSL
        FROM dbo.SFT200
        WHERE D_E_L_E_T_ = ''
          AND FT_ENTRADA BETWEEN @DATA_INICIAL AND @DATA_FINAL
    )
    INSERT INTO #FISCAL
    SELECT S.GRUPO_EMPRESA, S.ORIGEM_FISCAL, S.FILIAL, S.DATA_FISCAL,
           S.TIPO_MOVIMENTO, S.DOCUMENTO, S.SERIE, S.PARTICIPANTE, S.LOJA,
           S.CFOP, S.IDENTIFICADOR, S.RECNO_FISCAL, I.IMPOSTO, I.CAMPO_VALOR,
           CONVERT(DECIMAL(19, 4), I.VALOR_FISCAL_ORIGINAL), I.CONTA_CANDIDATA
    FROM SFT AS S
    CROSS APPLY
    (
        VALUES
            ('ICMS', 'FT_VALICM', S.FT_VALICM, '101021001'),
            ('ICMS ST', 'FT_ICMSRET', S.FT_ICMSRET, '201010908'),
            ('ICMS DIFAL', 'FT_ICMSDIF', S.FT_ICMSDIF, '201010911'),
            ('IPI', 'FT_VALIPI', S.FT_VALIPI, '101021004'),
            ('PIS', 'FT_VALPIS', S.FT_VALPIS, '101021002'),
            ('COFINS', 'FT_VALCOF', S.FT_VALCOF, '101021003'),
            ('CSLL', 'FT_VALCSL', S.FT_VALCSL, '201010906'),
            ('IRRF', 'FT_VALIRR', S.FT_VALIRR, '201010901'),
            ('INSS', 'FT_VALINS', S.FT_VALINS, '201010903'),
            ('ISS', 'FT_ISSSUB', S.FT_ISSSUB, '201010905'),
            ('PIS RETIDO', 'FT_VRETPIS', S.FT_VRETPIS, '201010906'),
            ('COFINS RETIDO', 'FT_VRETCOF', S.FT_VRETCOF, '201010906'),
            ('CSLL RETIDA', 'FT_VRETCSL', S.FT_VRETCSL, '201010906')
    ) AS I (IMPOSTO, CAMPO_VALOR, VALOR_FISCAL_ORIGINAL, CONTA_CANDIDATA)
    WHERE I.VALOR_FISCAL_ORIGINAL <> 0
      AND (@FILIAL IS NULL OR S.FILIAL = @FILIAL);

    ;WITH SF3 AS
    (
        SELECT '20' GRUPO_EMPRESA, 'SF3' ORIGEM_FISCAL, F3_FILIAL FILIAL,
               F3_ENTRADA DATA_FISCAL, F3_TIPO TIPO_MOVIMENTO,
               F3_NFISCAL DOCUMENTO, F3_SERIE SERIE, F3_CLIEFOR PARTICIPANTE,
               F3_LOJA LOJA, F3_CFO CFOP, F3_IDENTFT IDENTIFICADOR,
               R_E_C_N_O_ RECNO_FISCAL, F3_VALICM, F3_ICMSRET, F3_ICMSDIF,
               F3_VALIPI, F3_ISSSUB
        FROM dbo.SF3200
        WHERE D_E_L_E_T_ = ''
          AND F3_ENTRADA BETWEEN @DATA_INICIAL AND @DATA_FINAL
    )
    INSERT INTO #FISCAL
    SELECT S.GRUPO_EMPRESA, S.ORIGEM_FISCAL, S.FILIAL, S.DATA_FISCAL,
           S.TIPO_MOVIMENTO, S.DOCUMENTO, S.SERIE, S.PARTICIPANTE, S.LOJA,
           S.CFOP, S.IDENTIFICADOR, S.RECNO_FISCAL, I.IMPOSTO, I.CAMPO_VALOR,
           CONVERT(DECIMAL(19, 4), I.VALOR_FISCAL_ORIGINAL), I.CONTA_CANDIDATA
    FROM SF3 AS S
    CROSS APPLY
    (
        VALUES
            ('ICMS', 'F3_VALICM', S.F3_VALICM, '101021001'),
            ('ICMS ST', 'F3_ICMSRET', S.F3_ICMSRET, '201010908'),
            ('ICMS DIFAL', 'F3_ICMSDIF', S.F3_ICMSDIF, '201010911'),
            ('IPI', 'F3_VALIPI', S.F3_VALIPI, '101021004'),
            ('ISS', 'F3_ISSSUB', S.F3_ISSSUB, '201010905')
    ) AS I (IMPOSTO, CAMPO_VALOR, VALOR_FISCAL_ORIGINAL, CONTA_CANDIDATA)
    WHERE I.VALOR_FISCAL_ORIGINAL <> 0
      AND (@FILIAL IS NULL OR S.FILIAL = @FILIAL);

    -- Aba 2: detalhe fiscal. Comparar SFT e SF3; nao somar as origens.
    SELECT
        F.GRUPO_EMPRESA,
        F.ORIGEM_FISCAL,
        RTRIM(F.FILIAL) AS FILIAL,
        F.DATA_FISCAL,
        F.TIPO_MOVIMENTO,
        RTRIM(F.DOCUMENTO) AS DOCUMENTO,
        RTRIM(F.SERIE) AS SERIE,
        RTRIM(F.PARTICIPANTE) AS PARTICIPANTE,
        RTRIM(F.LOJA) AS LOJA,
        RTRIM(F.CFOP) AS CFOP,
        RTRIM(F.IDENTIFICADOR) AS IDENTIFICADOR,
        F.RECNO_FISCAL,
        F.IMPOSTO,
        F.CAMPO_VALOR,
        F.VALOR_FISCAL_ORIGINAL,
        F.CONTA_CANDIDATA
    FROM #FISCAL AS F
    ORDER BY F.GRUPO_EMPRESA, F.FILIAL, F.DATA_FISCAL,
             F.DOCUMENTO, F.SERIE, F.ORIGEM_FISCAL, F.IMPOSTO;

    CREATE TABLE #CONTABIL
    (
        GRUPO_EMPRESA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        DATA_CONTABIL VARCHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        LP VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        ROTINA VARCHAR(10) COLLATE DATABASE_DEFAULT NOT NULL,
        ORIGEM VARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL,
        CONTA VARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL,
        LADO_CONTA VARCHAR(7) COLLATE DATABASE_DEFAULT NOT NULL,
        VALOR_MOVIMENTO DECIMAL(19, 4) NOT NULL,
        RECNO_CT2 BIGINT NOT NULL
    );

    ;WITH CT2 AS
    (
        SELECT '20' GRUPO_EMPRESA, CT2_FILIAL, CT2_DATA, CT2_LP, CT2_ROTINA,
               CT2_ORIGEM, CT2_DEBITO, CT2_CREDIT, CT2_VALOR, R_E_C_N_O_
        FROM dbo.CT2200
        WHERE D_E_L_E_T_ = ''
          AND CT2_DATA BETWEEN @DATA_INICIAL AND @DATA_FINAL
    )
    INSERT INTO #CONTABIL
    SELECT C.GRUPO_EMPRESA, C.CT2_FILIAL, C.CT2_DATA, C.CT2_LP,
           C.CT2_ROTINA, C.CT2_ORIGEM, M.CONTA, M.LADO_CONTA,
           CONVERT(DECIMAL(19, 4), C.CT2_VALOR), C.R_E_C_N_O_
    FROM CT2 AS C
    CROSS APPLY
    (
        VALUES
            (RTRIM(C.CT2_DEBITO), 'DEBITO'),
            (RTRIM(C.CT2_CREDIT), 'CREDITO')
    ) AS M (CONTA, LADO_CONTA)
    INNER JOIN #CONTAS_IMPOSTOS AS CI ON CI.CONTA = M.CONTA
    WHERE (@FILIAL IS NULL OR C.CT2_FILIAL = @FILIAL);

    -- Aba 3: valor positivo por lado e saldo contabil debito menos credito.
    SELECT
        C.GRUPO_EMPRESA,
        RTRIM(C.FILIAL) AS FILIAL,
        C.CONTA,
        CI.DESCRICAO_CONTA,
        RTRIM(C.LP) AS LP,
        RTRIM(C.ROTINA) AS ROTINA,
        RTRIM(C.ORIGEM) AS ORIGEM,
        C.LADO_CONTA,
        COUNT(*) AS QUANTIDADE_LANCAMENTOS,
        SUM(C.VALOR_MOVIMENTO) AS VALOR_MOVIMENTO,
        SUM(CASE WHEN C.LADO_CONTA = 'DEBITO'
                 THEN C.VALOR_MOVIMENTO ELSE -C.VALOR_MOVIMENTO END) AS SALDO_CONTABIL
    FROM #CONTABIL AS C
    INNER JOIN #CONTAS_IMPOSTOS AS CI ON CI.CONTA = C.CONTA
    GROUP BY C.GRUPO_EMPRESA, C.FILIAL, C.CONTA, CI.DESCRICAO_CONTA,
             C.LP, C.ROTINA, C.ORIGEM, C.LADO_CONTA
    ORDER BY C.GRUPO_EMPRESA, C.FILIAL, C.CONTA, C.LP,
             C.ROTINA, C.ORIGEM, C.LADO_CONTA;
END;
