/*=============================================================================
  Objeto........: dbo.SP_HDS3590_RCOM06
  Objetivo......: Auditar boletos DDA contra a condicao de pagamento do pedido
                  de compra e o titulo financeiro gerado pela nota fiscal.
  Banco.........: CCW2SA_171703_PR_PD
  Conexao.......: Agronelli_tst_local
  Granularidade.: Um item de NF/pedido por parcela financeira e boleto DDA.
  Validado em...: 2026-09-22, somente leitura, via MCP dbcode.

  Objetos validados:
    SC7060/SC7080/SC7200/SC7230 - itens dos pedidos de compra
    SD1060/SD1080/SD1200/SD1230 - itens das notas fiscais de entrada
    SF1060/SF1080/SF1200/SF1230 - cabecalhos das notas fiscais de entrada
    SE2060/SE2080/SE2200/SE2230 - titulos do contas a pagar
    FIG060/FIG080/FIG200/FIG230 - conciliacao DDA
    SA2060/SA2080/SA2200/SA2230 - fornecedores
    SE4060/SE4080/SE4200/SE4230 - condicoes de pagamento

  Criterios de auditoria:
    1. A condicao da NF deve ser igual a condicao do item do pedido.
    2. O vencimento do DDA deve ser igual ao vencimento real do titulo SE2;
       quando E2_VENCREA estiver vazio, usa-se o vencimento nominal.
    3. O valor do DDA deve ser igual ao valor do titulo, com tolerancia de R$ 0,01.

  Observacoes:
    - FIG_DATA e a data de processamento do arquivo DDA, nao a data de emissao
      juridica do boleto. E2_EMISSAO e a emissao do titulo financeiro.
    - FIG_TITULO e o documento de cobranca DDA. E2_NUMBOR e numero de bordero
      e, por isso, nao e apresentado como numero do boleto.
    - Condicoes especiais da SE4 nao sao recalculadas nesta procedure. A
      consistencia e verificada pela cadeia PC -> NF -> titulo SE2 -> DDA.
    - O periodo e limitado a menos de tres meses e os filtros de data sao
      aplicados nas tabelas fisicas antes dos JOINs de maior volume.
    - Este arquivo contem somente codigo-fonte versionado. A procedure nao foi
      criada ou alterada no banco.
=============================================================================*/
/*
Exemplo de uso apos instalacao autorizada:

EXEC dbo.SP_HDS3590_RCOM06
    @DATA_INI = '01/04/2026',
    @DATA_FIM = '30/04/2026',
    @EMPRESA = '20',
    @FILIAL = NULL,
    @FORNECEDOR = NULL,
    @SOMENTE_DIVERGENCIAS = 0,
    @INCLUIR_SEM_BOLETO = 1;
*/

CREATE OR ALTER PROCEDURE dbo.SP_HDS3590_RCOM06
    @DATA_INI VARCHAR(10),
    @DATA_FIM VARCHAR(10),
    @EMPRESA VARCHAR(MAX) = NULL,
    @FILIAL VARCHAR(MAX) = NULL,
    @FORNECEDOR VARCHAR(MAX) = NULL,
    @SOMENTE_DIVERGENCIAS BIT = 0,
    @INCLUIR_SEM_BOLETO BIT = 1
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @DATA_INICIAL DATE = TRY_CONVERT(DATE, @DATA_INI, 103);
    DECLARE @DATA_FINAL DATE = TRY_CONVERT(DATE, @DATA_FIM, 103);
    DECLARE @DATA_INICIAL_PROTHEUS CHAR(8);
    DECLARE @DATA_FINAL_PROTHEUS CHAR(8);
    DECLARE @DATA_DDA_INICIAL CHAR(8);
    DECLARE @DATA_DDA_FINAL CHAR(8);

    IF @DATA_INICIAL IS NULL
        THROW 50001, 'DATA_INI deve ser uma data valida no formato dd/mm/aaaa.', 1;

    IF @DATA_FINAL IS NULL
        THROW 50002, 'DATA_FIM deve ser uma data valida no formato dd/mm/aaaa.', 1;

    IF @DATA_INICIAL > @DATA_FINAL
        THROW 50003, 'DATA_INI nao pode ser maior que DATA_FIM.', 1;

    IF @DATA_FINAL >= DATEADD(MONTH, 12, @DATA_INICIAL)
        THROW 50004, 'O periodo deve ser inferior a DOZE meses por execucao.', 1;

    SET @DATA_INICIAL_PROTHEUS = CONVERT(CHAR(8), @DATA_INICIAL, 112);
    SET @DATA_FINAL_PROTHEUS = CONVERT(CHAR(8), @DATA_FINAL, 112);
    SET @DATA_DDA_INICIAL = CONVERT(CHAR(8), DATEADD(DAY, -31, @DATA_INICIAL), 112);
    SET @DATA_DDA_FINAL = CONVERT(CHAR(8), DATEADD(DAY, 93, @DATA_FINAL), 112);

    CREATE TABLE #FILTRO_EMPRESA
    (
        EMPRESA CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY
    );

    CREATE TABLE #FILTRO_FILIAL
    (
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY
    );

    CREATE TABLE #FILTRO_FORNECEDOR
    (
        FORNECEDOR VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY
    );

    INSERT INTO #FILTRO_EMPRESA (EMPRESA)
    SELECT DISTINCT CONVERT(CHAR(2), LTRIM(RTRIM(value)))
    FROM STRING_SPLIT(COALESCE(@EMPRESA, ''), ',')
    WHERE LTRIM(RTRIM(value)) <> '';

    IF EXISTS
    (
        SELECT 1
        FROM #FILTRO_EMPRESA
        WHERE EMPRESA NOT IN ('06', '08', '20', '23')
    )
        THROW 50005, 'EMPRESA aceita somente os grupos 06, 08, 20 e 23.', 1;

    INSERT INTO #FILTRO_FILIAL (FILIAL)
    SELECT DISTINCT CONVERT(VARCHAR(6), LTRIM(RTRIM(value)))
    FROM STRING_SPLIT(COALESCE(@FILIAL, ''), ',')
    WHERE LTRIM(RTRIM(value)) <> '';

    INSERT INTO #FILTRO_FORNECEDOR (FORNECEDOR)
    SELECT DISTINCT CONVERT(VARCHAR(6), LTRIM(RTRIM(value)))
    FROM STRING_SPLIT(COALESCE(@FORNECEDOR, ''), ',')
    WHERE LTRIM(RTRIM(value)) <> '';

    CREATE TABLE #BASE
    (
        EMPRESA CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        GRUPO_EMPRESA VARCHAR(30) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        RECNO_D1 BIGINT NOT NULL,
        PEDIDO VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        ITEM_PEDIDO VARCHAR(4) COLLATE DATABASE_DEFAULT NOT NULL,
        EMISSAO_PEDIDO CHAR(8) COLLATE DATABASE_DEFAULT NULL,
        CONDICAO_PEDIDO VARCHAR(3) COLLATE DATABASE_DEFAULT NULL,
        TIPO_CONDICAO VARCHAR(1) COLLATE DATABASE_DEFAULT NULL,
        FORMULA_CONDICAO VARCHAR(40) COLLATE DATABASE_DEFAULT NULL,
        DESCRICAO_CONDICAO VARCHAR(15) COLLATE DATABASE_DEFAULT NULL,
        FORMA_PAGAMENTO VARCHAR(6) COLLATE DATABASE_DEFAULT NULL,
        FORNECEDOR_PEDIDO VARCHAR(6) COLLATE DATABASE_DEFAULT NULL,
        LOJA_PEDIDO VARCHAR(2) COLLATE DATABASE_DEFAULT NULL,
        FORNECEDOR_NF VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        LOJA_NF VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        NOME_FORNECEDOR VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
        CNPJ_CPF VARCHAR(14) COLLATE DATABASE_DEFAULT NULL,
        PRODUTO VARCHAR(15) COLLATE DATABASE_DEFAULT NOT NULL,
        DESCRICAO_PRODUTO VARCHAR(60) COLLATE DATABASE_DEFAULT NOT NULL,
        UNIDADE VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        QUANTIDADE DECIMAL(20,6) NOT NULL,
        VALOR_UNITARIO DECIMAL(20,6) NOT NULL,
        VALOR_ITEM DECIMAL(20,2) NOT NULL,
        NOTA_FISCAL VARCHAR(9) COLLATE DATABASE_DEFAULT NOT NULL,
        SERIE VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        ITEM_NF VARCHAR(4) COLLATE DATABASE_DEFAULT NOT NULL,
        EMISSAO_NF CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        DIGITACAO_NF CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        CONDICAO_NF VARCHAR(3) COLLATE DATABASE_DEFAULT NULL,
        NUMERO_DUPLICATA VARCHAR(9) COLLATE DATABASE_DEFAULT NULL,
        VALOR_BRUTO_NF DECIMAL(20,2) NULL,
        CHAVE_NFE VARCHAR(44) COLLATE DATABASE_DEFAULT NULL,
        RECNO_C7 BIGINT NULL,
        RECNO_F1 BIGINT NULL,
        CONSTRAINT PK_BASE PRIMARY KEY CLUSTERED (EMPRESA, RECNO_D1)
    );

    INSERT INTO #BASE
    SELECT '06', '06 - IADS', RTRIM(D1.D1_FILIAL), D1.R_E_C_N_O_,
           RTRIM(D1.D1_PEDIDO), RTRIM(D1.D1_ITEMPC), NULLIF(C7.C7_EMISSAO, ''),
           NULLIF(RTRIM(C7.C7_COND), ''), NULLIF(RTRIM(E4.E4_TIPO), ''),
           NULLIF(RTRIM(E4.E4_COND), ''), NULLIF(RTRIM(E4.E4_DESCRI), ''),
           NULLIF(RTRIM(E4.E4_FORMA), ''),
           NULLIF(RTRIM(C7.C7_FORNECE), ''), NULLIF(RTRIM(C7.C7_LOJA), ''),
           RTRIM(D1.D1_FORNECE), RTRIM(D1.D1_LOJA), NULLIF(RTRIM(A2.A2_NOME), ''),
           NULLIF(RTRIM(A2.A2_CGC), ''), RTRIM(D1.D1_COD), RTRIM(D1.D1_DESCRI),
           RTRIM(D1.D1_UM), CONVERT(DECIMAL(20,6), D1.D1_QUANT),
           CONVERT(DECIMAL(20,6), D1.D1_VUNIT), CONVERT(DECIMAL(20,2), D1.D1_TOTAL),
           RTRIM(D1.D1_DOC), RTRIM(D1.D1_SERIE), RTRIM(D1.D1_ITEM), D1.D1_EMISSAO,
           D1.D1_DTDIGIT, NULLIF(RTRIM(F1.F1_COND), ''), NULLIF(RTRIM(F1.F1_DUPL), ''),
           CONVERT(DECIMAL(20,2), F1.F1_VALBRUT), NULLIF(RTRIM(F1.F1_CHVNFE), ''),
           C7.R_E_C_N_O_, F1.R_E_C_N_O_
    FROM dbo.SD1060 AS D1
    LEFT JOIN dbo.SC7060 AS C7
        ON C7.C7_FILIAL = D1.D1_FILIAL
       AND C7.C7_NUM = D1.D1_PEDIDO
       AND C7.C7_ITEM = D1.D1_ITEMPC
       AND C7.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SF1060 AS F1
        ON F1.F1_FILIAL = D1.D1_FILIAL
       AND F1.F1_DOC = D1.D1_DOC
       AND F1.F1_SERIE = D1.D1_SERIE
       AND F1.F1_FORNECE = D1.D1_FORNECE
       AND F1.F1_LOJA = D1.D1_LOJA
       AND F1.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SA2060 AS A2
        ON A2.A2_FILIAL = '' AND A2.A2_COD = D1.D1_FORNECE
       AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SE4060 AS E4
        ON E4.E4_FILIAL = '' AND E4.E4_CODIGO = C7.C7_COND
       AND E4.D_E_L_E_T_ = ''
    WHERE D1.D_E_L_E_T_ = ''
      AND D1.D1_EMISSAO BETWEEN @DATA_INICIAL_PROTHEUS AND @DATA_FINAL_PROTHEUS
      AND RTRIM(D1.D1_PEDIDO) <> ''
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_EMPRESA) OR EXISTS (SELECT 1 FROM #FILTRO_EMPRESA WHERE EMPRESA = '06'))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FILIAL) OR EXISTS (SELECT 1 FROM #FILTRO_FILIAL WHERE FILIAL = RTRIM(D1.D1_FILIAL)))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR) OR EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR WHERE FORNECEDOR = RTRIM(D1.D1_FORNECE)))
    OPTION (RECOMPILE);

    INSERT INTO #BASE
    SELECT '08', '08 - Neltech', RTRIM(D1.D1_FILIAL), D1.R_E_C_N_O_,
           RTRIM(D1.D1_PEDIDO), RTRIM(D1.D1_ITEMPC), NULLIF(C7.C7_EMISSAO, ''),
           NULLIF(RTRIM(C7.C7_COND), ''), NULLIF(RTRIM(E4.E4_TIPO), ''),
           NULLIF(RTRIM(E4.E4_COND), ''), NULLIF(RTRIM(E4.E4_DESCRI), ''),
           NULLIF(RTRIM(E4.E4_FORMA), ''),
           NULLIF(RTRIM(C7.C7_FORNECE), ''), NULLIF(RTRIM(C7.C7_LOJA), ''),
           RTRIM(D1.D1_FORNECE), RTRIM(D1.D1_LOJA), NULLIF(RTRIM(A2.A2_NOME), ''),
           NULLIF(RTRIM(A2.A2_CGC), ''), RTRIM(D1.D1_COD), RTRIM(D1.D1_DESCRI),
           RTRIM(D1.D1_UM), CONVERT(DECIMAL(20,6), D1.D1_QUANT),
           CONVERT(DECIMAL(20,6), D1.D1_VUNIT), CONVERT(DECIMAL(20,2), D1.D1_TOTAL),
           RTRIM(D1.D1_DOC), RTRIM(D1.D1_SERIE), RTRIM(D1.D1_ITEM), D1.D1_EMISSAO,
           D1.D1_DTDIGIT, NULLIF(RTRIM(F1.F1_COND), ''), NULLIF(RTRIM(F1.F1_DUPL), ''),
           CONVERT(DECIMAL(20,2), F1.F1_VALBRUT), NULLIF(RTRIM(F1.F1_CHVNFE), ''),
           C7.R_E_C_N_O_, F1.R_E_C_N_O_
    FROM dbo.SD1080 AS D1
    LEFT JOIN dbo.SC7080 AS C7
        ON C7.C7_FILIAL = D1.D1_FILIAL AND C7.C7_NUM = D1.D1_PEDIDO
       AND C7.C7_ITEM = D1.D1_ITEMPC AND C7.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SF1080 AS F1
        ON F1.F1_FILIAL = D1.D1_FILIAL AND F1.F1_DOC = D1.D1_DOC
       AND F1.F1_SERIE = D1.D1_SERIE AND F1.F1_FORNECE = D1.D1_FORNECE
       AND F1.F1_LOJA = D1.D1_LOJA AND F1.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SA2080 AS A2
        ON A2.A2_FILIAL = '' AND A2.A2_COD = D1.D1_FORNECE
       AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SE4080 AS E4
        ON E4.E4_FILIAL = '' AND E4.E4_CODIGO = C7.C7_COND AND E4.D_E_L_E_T_ = ''
    WHERE D1.D_E_L_E_T_ = ''
      AND D1.D1_EMISSAO BETWEEN @DATA_INICIAL_PROTHEUS AND @DATA_FINAL_PROTHEUS
      AND RTRIM(D1.D1_PEDIDO) <> ''
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_EMPRESA) OR EXISTS (SELECT 1 FROM #FILTRO_EMPRESA WHERE EMPRESA = '08'))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FILIAL) OR EXISTS (SELECT 1 FROM #FILTRO_FILIAL WHERE FILIAL = RTRIM(D1.D1_FILIAL)))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR) OR EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR WHERE FORNECEDOR = RTRIM(D1.D1_FORNECE)))
    OPTION (RECOMPILE);

    INSERT INTO #BASE
    SELECT '20', '20 - Grupo Agronelli', RTRIM(D1.D1_FILIAL), D1.R_E_C_N_O_,
           RTRIM(D1.D1_PEDIDO), RTRIM(D1.D1_ITEMPC), NULLIF(C7.C7_EMISSAO, ''),
           NULLIF(RTRIM(C7.C7_COND), ''), NULLIF(RTRIM(E4.E4_TIPO), ''),
           NULLIF(RTRIM(E4.E4_COND), ''), NULLIF(RTRIM(E4.E4_DESCRI), ''),
           NULLIF(RTRIM(E4.E4_FORMA), ''),
           NULLIF(RTRIM(C7.C7_FORNECE), ''), NULLIF(RTRIM(C7.C7_LOJA), ''),
           RTRIM(D1.D1_FORNECE), RTRIM(D1.D1_LOJA), NULLIF(RTRIM(A2.A2_NOME), ''),
           NULLIF(RTRIM(A2.A2_CGC), ''), RTRIM(D1.D1_COD), RTRIM(D1.D1_DESCRI),
           RTRIM(D1.D1_UM), CONVERT(DECIMAL(20,6), D1.D1_QUANT),
           CONVERT(DECIMAL(20,6), D1.D1_VUNIT), CONVERT(DECIMAL(20,2), D1.D1_TOTAL),
           RTRIM(D1.D1_DOC), RTRIM(D1.D1_SERIE), RTRIM(D1.D1_ITEM), D1.D1_EMISSAO,
           D1.D1_DTDIGIT, NULLIF(RTRIM(F1.F1_COND), ''), NULLIF(RTRIM(F1.F1_DUPL), ''),
           CONVERT(DECIMAL(20,2), F1.F1_VALBRUT), NULLIF(RTRIM(F1.F1_CHVNFE), ''),
           C7.R_E_C_N_O_, F1.R_E_C_N_O_
    FROM dbo.SD1200 AS D1
    LEFT JOIN dbo.SC7200 AS C7
        ON C7.C7_FILIAL = D1.D1_FILIAL AND C7.C7_NUM = D1.D1_PEDIDO
       AND C7.C7_ITEM = D1.D1_ITEMPC AND C7.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SF1200 AS F1
        ON F1.F1_FILIAL = D1.D1_FILIAL AND F1.F1_DOC = D1.D1_DOC
       AND F1.F1_SERIE = D1.D1_SERIE AND F1.F1_FORNECE = D1.D1_FORNECE
       AND F1.F1_LOJA = D1.D1_LOJA AND F1.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SA2200 AS A2
        ON A2.A2_FILIAL = '' AND A2.A2_COD = D1.D1_FORNECE
       AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SE4200 AS E4
        ON E4.E4_FILIAL = '' AND E4.E4_CODIGO = C7.C7_COND AND E4.D_E_L_E_T_ = ''
    WHERE D1.D_E_L_E_T_ = ''
      AND D1.D1_EMISSAO BETWEEN @DATA_INICIAL_PROTHEUS AND @DATA_FINAL_PROTHEUS
      AND RTRIM(D1.D1_PEDIDO) <> ''
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_EMPRESA) OR EXISTS (SELECT 1 FROM #FILTRO_EMPRESA WHERE EMPRESA = '20'))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FILIAL) OR EXISTS (SELECT 1 FROM #FILTRO_FILIAL WHERE FILIAL = RTRIM(D1.D1_FILIAL)))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR) OR EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR WHERE FORNECEDOR = RTRIM(D1.D1_FORNECE)))
    OPTION (RECOMPILE);

    INSERT INTO #BASE
    SELECT '23', '23 - MTP', RTRIM(D1.D1_FILIAL), D1.R_E_C_N_O_,
           RTRIM(D1.D1_PEDIDO), RTRIM(D1.D1_ITEMPC), NULLIF(C7.C7_EMISSAO, ''),
           NULLIF(RTRIM(C7.C7_COND), ''), NULLIF(RTRIM(E4.E4_TIPO), ''),
           NULLIF(RTRIM(E4.E4_COND), ''), NULLIF(RTRIM(E4.E4_DESCRI), ''),
           NULLIF(RTRIM(E4.E4_FORMA), ''),
           NULLIF(RTRIM(C7.C7_FORNECE), ''), NULLIF(RTRIM(C7.C7_LOJA), ''),
           RTRIM(D1.D1_FORNECE), RTRIM(D1.D1_LOJA), NULLIF(RTRIM(A2.A2_NOME), ''),
           NULLIF(RTRIM(A2.A2_CGC), ''), RTRIM(D1.D1_COD), RTRIM(D1.D1_DESCRI),
           RTRIM(D1.D1_UM), CONVERT(DECIMAL(20,6), D1.D1_QUANT),
           CONVERT(DECIMAL(20,6), D1.D1_VUNIT), CONVERT(DECIMAL(20,2), D1.D1_TOTAL),
           RTRIM(D1.D1_DOC), RTRIM(D1.D1_SERIE), RTRIM(D1.D1_ITEM), D1.D1_EMISSAO,
           D1.D1_DTDIGIT, NULLIF(RTRIM(F1.F1_COND), ''), NULLIF(RTRIM(F1.F1_DUPL), ''),
           CONVERT(DECIMAL(20,2), F1.F1_VALBRUT), NULLIF(RTRIM(F1.F1_CHVNFE), ''),
           C7.R_E_C_N_O_, F1.R_E_C_N_O_
    FROM dbo.SD1230 AS D1
    LEFT JOIN dbo.SC7230 AS C7
        ON C7.C7_FILIAL = D1.D1_FILIAL AND C7.C7_NUM = D1.D1_PEDIDO
       AND C7.C7_ITEM = D1.D1_ITEMPC AND C7.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SF1230 AS F1
        ON F1.F1_FILIAL = D1.D1_FILIAL AND F1.F1_DOC = D1.D1_DOC
       AND F1.F1_SERIE = D1.D1_SERIE AND F1.F1_FORNECE = D1.D1_FORNECE
       AND F1.F1_LOJA = D1.D1_LOJA AND F1.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SA2230 AS A2
        ON A2.A2_FILIAL = '' AND A2.A2_COD = D1.D1_FORNECE
       AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_ = ''
    LEFT JOIN dbo.SE4230 AS E4
        ON E4.E4_FILIAL = '' AND E4.E4_CODIGO = C7.C7_COND AND E4.D_E_L_E_T_ = ''
    WHERE D1.D_E_L_E_T_ = ''
      AND D1.D1_EMISSAO BETWEEN @DATA_INICIAL_PROTHEUS AND @DATA_FINAL_PROTHEUS
      AND RTRIM(D1.D1_PEDIDO) <> ''
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_EMPRESA) OR EXISTS (SELECT 1 FROM #FILTRO_EMPRESA WHERE EMPRESA = '23'))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FILIAL) OR EXISTS (SELECT 1 FROM #FILTRO_FILIAL WHERE FILIAL = RTRIM(D1.D1_FILIAL)))
      AND (NOT EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR) OR EXISTS (SELECT 1 FROM #FILTRO_FORNECEDOR WHERE FORNECEDOR = RTRIM(D1.D1_FORNECE)))
    OPTION (RECOMPILE);

    CREATE NONCLUSTERED INDEX IX_BASE_NF
        ON #BASE (EMPRESA, FILIAL, NOTA_FISCAL, SERIE, FORNECEDOR_NF, LOJA_NF);

    CREATE TABLE #NOTAS
    (
        EMPRESA CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        NOTA_FISCAL VARCHAR(9) COLLATE DATABASE_DEFAULT NOT NULL,
        SERIE VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        FORNECEDOR VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        LOJA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        NUMERO_DUPLICATA VARCHAR(9) COLLATE DATABASE_DEFAULT NOT NULL,
        CONSTRAINT PK_NOTAS PRIMARY KEY CLUSTERED
            (EMPRESA, FILIAL, NOTA_FISCAL, SERIE, FORNECEDOR, LOJA)
    );

    INSERT INTO #NOTAS
    SELECT B.EMPRESA, B.FILIAL, B.NOTA_FISCAL, B.SERIE, B.FORNECEDOR_NF,
           B.LOJA_NF, MAX(COALESCE(B.NUMERO_DUPLICATA, ''))
    FROM #BASE AS B
    GROUP BY B.EMPRESA, B.FILIAL, B.NOTA_FISCAL, B.SERIE,
             B.FORNECEDOR_NF, B.LOJA_NF;

    CREATE TABLE #TITULOS
    (
        EMPRESA CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        NOTA_FISCAL VARCHAR(9) COLLATE DATABASE_DEFAULT NOT NULL,
        SERIE_NF VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        FORNECEDOR VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        LOJA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        PREFIXO VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        TITULO VARCHAR(9) COLLATE DATABASE_DEFAULT NOT NULL,
        PARCELA VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        TIPO VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        EMISSAO_TITULO CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        VENCIMENTO_TITULO CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        VENCIMENTO_REAL CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        VALOR_TITULO DECIMAL(20,2) NOT NULL,
        SALDO_TITULO DECIMAL(20,2) NOT NULL,
        CODIGO_BARRAS VARCHAR(48) COLLATE DATABASE_DEFAULT NULL,
        LINHA_DIGITAVEL VARCHAR(48) COLLATE DATABASE_DEFAULT NULL,
        ORIGEM VARCHAR(8) COLLATE DATABASE_DEFAULT NULL,
        RECNO_E2 BIGINT NOT NULL,
        CHAVE_DDA VARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL,
        CONSTRAINT PK_TITULOS PRIMARY KEY CLUSTERED (EMPRESA, RECNO_E2)
    );

    INSERT INTO #TITULOS
    SELECT '06', RTRIM(E2.E2_FILIAL), N.NOTA_FISCAL, N.SERIE, RTRIM(E2.E2_FORNECE),
           RTRIM(E2.E2_LOJA), RTRIM(E2.E2_PREFIXO), RTRIM(E2.E2_NUM),
           RTRIM(E2.E2_PARCELA), RTRIM(E2.E2_TIPO), E2.E2_EMISSAO, E2.E2_VENCTO,
           E2.E2_VENCREA, CONVERT(DECIMAL(20,2), E2.E2_VALOR),
           CONVERT(DECIMAL(20,2), E2.E2_SALDO), NULLIF(RTRIM(E2.E2_CODBAR), ''),
           NULLIF(RTRIM(E2.E2_LINDIG), ''), NULLIF(RTRIM(E2.E2_ORIGEM), ''),
           E2.R_E_C_N_O_, E2.E2_FILIAL + '|' + E2.E2_PREFIXO + '|' + E2.E2_NUM
             + '|' + E2.E2_PARCELA + '|' + E2.E2_TIPO + '|' + E2.E2_FORNECE
             + '|' + E2.E2_LOJA + '|'
    FROM dbo.SE2060 AS E2
    INNER JOIN #NOTAS AS N
        ON N.EMPRESA = '06' AND N.FILIAL = RTRIM(E2.E2_FILIAL)
       AND N.SERIE = RTRIM(E2.E2_PREFIXO) AND N.NUMERO_DUPLICATA = RTRIM(E2.E2_NUM)
       AND N.FORNECEDOR = RTRIM(E2.E2_FORNECE) AND N.LOJA = RTRIM(E2.E2_LOJA)
    WHERE E2.D_E_L_E_T_ = ''
      AND E2.E2_EMISSAO BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
      AND E2.E2_TIPO NOT IN ('IRF', 'INS', 'ISS', 'PIS', 'COF', 'CSL')
    OPTION (RECOMPILE);

    INSERT INTO #TITULOS
    SELECT '08', RTRIM(E2.E2_FILIAL), N.NOTA_FISCAL, N.SERIE, RTRIM(E2.E2_FORNECE),
           RTRIM(E2.E2_LOJA), RTRIM(E2.E2_PREFIXO), RTRIM(E2.E2_NUM),
           RTRIM(E2.E2_PARCELA), RTRIM(E2.E2_TIPO), E2.E2_EMISSAO, E2.E2_VENCTO,
           E2.E2_VENCREA, CONVERT(DECIMAL(20,2), E2.E2_VALOR),
           CONVERT(DECIMAL(20,2), E2.E2_SALDO), NULLIF(RTRIM(E2.E2_CODBAR), ''),
           NULLIF(RTRIM(E2.E2_LINDIG), ''), NULLIF(RTRIM(E2.E2_ORIGEM), ''),
           E2.R_E_C_N_O_, E2.E2_FILIAL + '|' + E2.E2_PREFIXO + '|' + E2.E2_NUM
             + '|' + E2.E2_PARCELA + '|' + E2.E2_TIPO + '|' + E2.E2_FORNECE
             + '|' + E2.E2_LOJA + '|'
    FROM dbo.SE2080 AS E2
    INNER JOIN #NOTAS AS N
        ON N.EMPRESA = '08' AND N.FILIAL = RTRIM(E2.E2_FILIAL)
       AND N.SERIE = RTRIM(E2.E2_PREFIXO) AND N.NUMERO_DUPLICATA = RTRIM(E2.E2_NUM)
       AND N.FORNECEDOR = RTRIM(E2.E2_FORNECE) AND N.LOJA = RTRIM(E2.E2_LOJA)
    WHERE E2.D_E_L_E_T_ = ''
      AND E2.E2_EMISSAO BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
      AND E2.E2_TIPO NOT IN ('IRF', 'INS', 'ISS', 'PIS', 'COF', 'CSL')
    OPTION (RECOMPILE);

    INSERT INTO #TITULOS
    SELECT '20', RTRIM(E2.E2_FILIAL), N.NOTA_FISCAL, N.SERIE, RTRIM(E2.E2_FORNECE),
           RTRIM(E2.E2_LOJA), RTRIM(E2.E2_PREFIXO), RTRIM(E2.E2_NUM),
           RTRIM(E2.E2_PARCELA), RTRIM(E2.E2_TIPO), E2.E2_EMISSAO, E2.E2_VENCTO,
           E2.E2_VENCREA, CONVERT(DECIMAL(20,2), E2.E2_VALOR),
           CONVERT(DECIMAL(20,2), E2.E2_SALDO), NULLIF(RTRIM(E2.E2_CODBAR), ''),
           NULLIF(RTRIM(E2.E2_LINDIG), ''), NULLIF(RTRIM(E2.E2_ORIGEM), ''),
           E2.R_E_C_N_O_, E2.E2_FILIAL + '|' + E2.E2_PREFIXO + '|' + E2.E2_NUM
             + '|' + E2.E2_PARCELA + '|' + E2.E2_TIPO + '|' + E2.E2_FORNECE
             + '|' + E2.E2_LOJA + '|'
    FROM dbo.SE2200 AS E2
    INNER JOIN #NOTAS AS N
        ON N.EMPRESA = '20' AND N.FILIAL = RTRIM(E2.E2_FILIAL)
       AND N.SERIE = RTRIM(E2.E2_PREFIXO) AND N.NUMERO_DUPLICATA = RTRIM(E2.E2_NUM)
       AND N.FORNECEDOR = RTRIM(E2.E2_FORNECE) AND N.LOJA = RTRIM(E2.E2_LOJA)
    WHERE E2.D_E_L_E_T_ = ''
      AND E2.E2_EMISSAO BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
      AND E2.E2_TIPO NOT IN ('IRF', 'INS', 'ISS', 'PIS', 'COF', 'CSL')
    OPTION (RECOMPILE);

    INSERT INTO #TITULOS
    SELECT '23', RTRIM(E2.E2_FILIAL), N.NOTA_FISCAL, N.SERIE, RTRIM(E2.E2_FORNECE),
           RTRIM(E2.E2_LOJA), RTRIM(E2.E2_PREFIXO), RTRIM(E2.E2_NUM),
           RTRIM(E2.E2_PARCELA), RTRIM(E2.E2_TIPO), E2.E2_EMISSAO, E2.E2_VENCTO,
           E2.E2_VENCREA, CONVERT(DECIMAL(20,2), E2.E2_VALOR),
           CONVERT(DECIMAL(20,2), E2.E2_SALDO), NULLIF(RTRIM(E2.E2_CODBAR), ''),
           NULLIF(RTRIM(E2.E2_LINDIG), ''), NULLIF(RTRIM(E2.E2_ORIGEM), ''),
           E2.R_E_C_N_O_, E2.E2_FILIAL + '|' + E2.E2_PREFIXO + '|' + E2.E2_NUM
             + '|' + E2.E2_PARCELA + '|' + E2.E2_TIPO + '|' + E2.E2_FORNECE
             + '|' + E2.E2_LOJA + '|'
    FROM dbo.SE2230 AS E2
    INNER JOIN #NOTAS AS N
        ON N.EMPRESA = '23' AND N.FILIAL = RTRIM(E2.E2_FILIAL)
       AND N.SERIE = RTRIM(E2.E2_PREFIXO) AND N.NUMERO_DUPLICATA = RTRIM(E2.E2_NUM)
       AND N.FORNECEDOR = RTRIM(E2.E2_FORNECE) AND N.LOJA = RTRIM(E2.E2_LOJA)
    WHERE E2.D_E_L_E_T_ = ''
      AND E2.E2_EMISSAO BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
      AND E2.E2_TIPO NOT IN ('IRF', 'INS', 'ISS', 'PIS', 'COF', 'CSL')
    OPTION (RECOMPILE);

    CREATE UNIQUE NONCLUSTERED INDEX IX_TITULOS_DDA
        ON #TITULOS (EMPRESA, CHAVE_DDA);

    CREATE TABLE #DDA_BRUTO
    (
        EMPRESA CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        CHAVE_DDA VARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL,
        DATA_PROCESSAMENTO CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        DOCUMENTO_COBRANCA VARCHAR(15) COLLATE DATABASE_DEFAULT NOT NULL,
        VENCIMENTO_DDA CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        VALOR_DDA DECIMAL(20,2) NOT NULL,
        CODIGO_BARRAS_DDA VARCHAR(44) COLLATE DATABASE_DEFAULT NOT NULL,
        STATUS_CONCILIACAO CHAR(1) COLLATE DATABASE_DEFAULT NOT NULL,
        DATA_CONCILIACAO CHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        RECNO_FIG BIGINT NOT NULL
    );

    INSERT INTO #DDA_BRUTO
    SELECT '06', RTRIM(FIG.FIG_DDASE2), FIG.FIG_DATA, RTRIM(FIG.FIG_TITULO),
           FIG.FIG_VENCTO, CONVERT(DECIMAL(20,2), FIG.FIG_VALOR),
           RTRIM(FIG.FIG_CODBAR), FIG.FIG_CONCIL, FIG.FIG_DTCONC, FIG.R_E_C_N_O_
    FROM dbo.FIG060 AS FIG
    INNER JOIN #TITULOS AS T ON T.EMPRESA = '06' AND T.CHAVE_DDA = RTRIM(FIG.FIG_DDASE2)
    WHERE FIG.D_E_L_E_T_ = '' AND FIG.FIG_DATA BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
    OPTION (RECOMPILE);

    INSERT INTO #DDA_BRUTO
    SELECT '08', RTRIM(FIG.FIG_DDASE2), FIG.FIG_DATA, RTRIM(FIG.FIG_TITULO),
           FIG.FIG_VENCTO, CONVERT(DECIMAL(20,2), FIG.FIG_VALOR),
           RTRIM(FIG.FIG_CODBAR), FIG.FIG_CONCIL, FIG.FIG_DTCONC, FIG.R_E_C_N_O_
    FROM dbo.FIG080 AS FIG
    INNER JOIN #TITULOS AS T ON T.EMPRESA = '08' AND T.CHAVE_DDA = RTRIM(FIG.FIG_DDASE2)
    WHERE FIG.D_E_L_E_T_ = '' AND FIG.FIG_DATA BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
    OPTION (RECOMPILE);

    INSERT INTO #DDA_BRUTO
    SELECT '20', RTRIM(FIG.FIG_DDASE2), FIG.FIG_DATA, RTRIM(FIG.FIG_TITULO),
           FIG.FIG_VENCTO, CONVERT(DECIMAL(20,2), FIG.FIG_VALOR),
           RTRIM(FIG.FIG_CODBAR), FIG.FIG_CONCIL, FIG.FIG_DTCONC, FIG.R_E_C_N_O_
    FROM dbo.FIG200 AS FIG
    INNER JOIN #TITULOS AS T ON T.EMPRESA = '20' AND T.CHAVE_DDA = RTRIM(FIG.FIG_DDASE2)
    WHERE FIG.D_E_L_E_T_ = '' AND FIG.FIG_DATA BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
    OPTION (RECOMPILE);

    INSERT INTO #DDA_BRUTO
    SELECT '23', RTRIM(FIG.FIG_DDASE2), FIG.FIG_DATA, RTRIM(FIG.FIG_TITULO),
           FIG.FIG_VENCTO, CONVERT(DECIMAL(20,2), FIG.FIG_VALOR),
           RTRIM(FIG.FIG_CODBAR), FIG.FIG_CONCIL, FIG.FIG_DTCONC, FIG.R_E_C_N_O_
    FROM dbo.FIG230 AS FIG
    INNER JOIN #TITULOS AS T ON T.EMPRESA = '23' AND T.CHAVE_DDA = RTRIM(FIG.FIG_DDASE2)
    WHERE FIG.D_E_L_E_T_ = '' AND FIG.FIG_DATA BETWEEN @DATA_DDA_INICIAL AND @DATA_DDA_FINAL
    OPTION (RECOMPILE);

    ;WITH DDA AS
    (
        SELECT D.*,
               ROW_NUMBER() OVER
               (
                   PARTITION BY D.EMPRESA, D.CHAVE_DDA
                   ORDER BY D.DATA_PROCESSAMENTO DESC, D.RECNO_FIG DESC
               ) AS ORDEM
        FROM #DDA_BRUTO AS D
    ), RESULTADO AS
    (
        SELECT
            B.*,
            T.PREFIXO, T.TITULO, T.PARCELA, T.TIPO, T.EMISSAO_TITULO,
            T.VENCIMENTO_TITULO, T.VENCIMENTO_REAL, T.VALOR_TITULO,
            T.SALDO_TITULO, T.CODIGO_BARRAS, T.LINHA_DIGITAVEL, T.ORIGEM,
            T.RECNO_E2, D.DATA_PROCESSAMENTO, D.DOCUMENTO_COBRANCA,
            D.VENCIMENTO_DDA, D.VALOR_DDA, D.CODIGO_BARRAS_DDA,
            D.STATUS_CONCILIACAO, D.DATA_CONCILIACAO, D.RECNO_FIG,
            CASE
                WHEN B.RECNO_C7 IS NULL THEN 'PENDENCIA - PEDIDO NAO LOCALIZADO'
                WHEN B.FORNECEDOR_PEDIDO <> B.FORNECEDOR_NF
                  OR B.LOJA_PEDIDO <> B.LOJA_NF THEN 'DIVERGENCIA - FORNECEDOR PC X NF'
                WHEN B.RECNO_F1 IS NULL THEN 'PENDENCIA - CABECALHO DA NF NAO LOCALIZADO'
                WHEN COALESCE(B.CONDICAO_PEDIDO, '') <> COALESCE(B.CONDICAO_NF, '')
                    THEN 'DIVERGENCIA - CONDICAO PC X NF'
                WHEN T.RECNO_E2 IS NULL THEN 'PENDENCIA - TITULO FINANCEIRO NAO LOCALIZADO'
                WHEN D.RECNO_FIG IS NULL
                 AND (T.CODIGO_BARRAS IS NOT NULL OR T.LINHA_DIGITAVEL IS NOT NULL)
                    THEN 'ATENCAO - BOLETO NO TITULO SEM DDA'
                WHEN D.RECNO_FIG IS NULL THEN 'PENDENCIA - BOLETO NAO LOCALIZADO'
                WHEN D.VENCIMENTO_DDA <>
                     COALESCE(NULLIF(T.VENCIMENTO_REAL, ''), T.VENCIMENTO_TITULO)
                    THEN 'DIVERGENCIA - VENCIMENTO DDA X TITULO'
                WHEN ABS(D.VALOR_DDA - T.VALOR_TITULO) > 0.01
                    THEN 'DIVERGENCIA - VALOR DDA X TITULO'
                ELSE 'CONFORME'
            END AS STATUS_AUDITORIA
        FROM #BASE AS B
        LEFT JOIN #TITULOS AS T
            ON T.EMPRESA = B.EMPRESA AND T.FILIAL = B.FILIAL
           AND T.NOTA_FISCAL = B.NOTA_FISCAL AND T.SERIE_NF = B.SERIE
           AND T.FORNECEDOR = B.FORNECEDOR_NF AND T.LOJA = B.LOJA_NF
        LEFT JOIN DDA AS D
            ON D.EMPRESA = T.EMPRESA AND D.CHAVE_DDA = T.CHAVE_DDA AND D.ORDEM = 1
    )
    SELECT
        R.EMPRESA AS [GRUPO],
        R.GRUPO_EMPRESA AS [EMPRESA],
        R.FILIAL AS [FILIAL],
        R.PEDIDO AS [PEDIDO COMPRA],
        R.ITEM_PEDIDO AS [ITEM PEDIDO],
        TRY_CONVERT(DATE, R.EMISSAO_PEDIDO, 112) AS [EMISSAO PEDIDO],
        R.CONDICAO_PEDIDO AS [CONDICAO PC],
        R.TIPO_CONDICAO AS [TIPO CONDICAO],
        R.FORMULA_CONDICAO AS [REGRA CONDICAO],
        R.DESCRICAO_CONDICAO AS [DESCRICAO CONDICAO],
        R.FORMA_PAGAMENTO AS [FORMA PAGAMENTO],
        R.FORNECEDOR_NF AS [FORNECEDOR],
        R.LOJA_NF AS [LOJA],
        R.NOME_FORNECEDOR AS [NOME FORNECEDOR],
        R.CNPJ_CPF AS [CNPJ CPF],
        R.PRODUTO AS [MATERIAL],
        R.DESCRICAO_PRODUTO AS [DESCRICAO MATERIAL],
        R.UNIDADE AS [UNIDADE],
        R.QUANTIDADE AS [QUANTIDADE NF],
        R.VALOR_UNITARIO AS [VALOR UNITARIO NF],
        R.VALOR_ITEM AS [VALOR ITEM NF],
        R.NOTA_FISCAL AS [NOTA FISCAL],
        R.SERIE AS [SERIE NF],
        R.ITEM_NF AS [ITEM NF],
        TRY_CONVERT(DATE, R.EMISSAO_NF, 112) AS [EMISSAO NF],
        TRY_CONVERT(DATE, R.DIGITACAO_NF, 112) AS [DIGITACAO NF],
        R.CONDICAO_NF AS [CONDICAO NF],
        R.VALOR_BRUTO_NF AS [VALOR BRUTO NF],
        R.CHAVE_NFE AS [CHAVE NFE],
        R.PREFIXO AS [PREFIXO TITULO],
        R.TITULO AS [NUMERO TITULO],
        R.PARCELA AS [PARCELA],
        R.TIPO AS [TIPO TITULO],
        TRY_CONVERT(DATE, R.EMISSAO_TITULO, 112) AS [EMISSAO TITULO],
        TRY_CONVERT(DATE, R.VENCIMENTO_TITULO, 112) AS [VENCIMENTO TITULO],
        TRY_CONVERT(DATE, R.VENCIMENTO_REAL, 112) AS [VENCIMENTO REAL],
        R.VALOR_TITULO AS [VALOR TITULO],
        R.SALDO_TITULO AS [SALDO TITULO],
        R.DOCUMENTO_COBRANCA AS [NUMERO BOLETO DDA],
        TRY_CONVERT(DATE, R.DATA_PROCESSAMENTO, 112) AS [PROCESSAMENTO DDA],
        TRY_CONVERT(DATE, R.VENCIMENTO_DDA, 112) AS [VENCIMENTO BOLETO],
        R.VALOR_DDA AS [VALOR BOLETO],
        COALESCE(R.CODIGO_BARRAS_DDA, R.CODIGO_BARRAS) AS [CODIGO BARRAS],
        R.LINHA_DIGITAVEL AS [LINHA DIGITAVEL],
        TRY_CONVERT(DATE, NULLIF(R.DATA_CONCILIACAO, ''), 112) AS [DATA CONCILIACAO DDA],
        CASE R.STATUS_CONCILIACAO WHEN '1' THEN 'CONCILIADO' WHEN '2' THEN 'NAO CONCILIADO' END AS [STATUS DDA],
        DATEDIFF(DAY, TRY_CONVERT(DATE, R.EMISSAO_NF, 112),
                 TRY_CONVERT(DATE, R.VENCIMENTO_TITULO, 112)) AS [DIAS NF ATE VENCIMENTO],
        CASE WHEN R.VENCIMENTO_DDA = COALESCE(NULLIF(R.VENCIMENTO_REAL, ''), R.VENCIMENTO_TITULO) THEN 0
             ELSE DATEDIFF(DAY, TRY_CONVERT(DATE, COALESCE(NULLIF(R.VENCIMENTO_REAL, ''), R.VENCIMENTO_TITULO), 112),
                                 TRY_CONVERT(DATE, R.VENCIMENTO_DDA, 112)) END AS [DIFERENCA DIAS BOLETO],
        CASE
            WHEN R.STATUS_AUDITORIA = 'CONFORME' THEN 'OK'
            WHEN R.STATUS_AUDITORIA LIKE 'DIVERGENCIA - CONDICAO%'
              OR R.STATUS_AUDITORIA LIKE 'DIVERGENCIA - VENCIMENTO%'
              OR R.STATUS_AUDITORIA LIKE 'DIVERGENCIA - VALOR%' THEN 'ALTA'
            WHEN R.STATUS_AUDITORIA LIKE 'DIVERGENCIA - FORNECEDOR%' THEN 'ALTA'
            ELSE 'MEDIA'
        END AS [PRIORIDADE],
        R.STATUS_AUDITORIA AS [STATUS AUDITORIA]
    FROM RESULTADO AS R
    WHERE (@INCLUIR_SEM_BOLETO = 1 OR R.RECNO_FIG IS NOT NULL
           OR R.CODIGO_BARRAS IS NOT NULL OR R.LINHA_DIGITAVEL IS NOT NULL)
      AND (@SOMENTE_DIVERGENCIAS = 0 OR R.STATUS_AUDITORIA <> 'CONFORME')
    ORDER BY
        CASE WHEN R.STATUS_AUDITORIA = 'CONFORME' THEN 2 ELSE 1 END,
        R.EMISSAO_NF, R.EMPRESA, R.FILIAL, R.NOTA_FISCAL,
        R.PEDIDO, R.ITEM_PEDIDO, R.PARCELA
    OPTION (RECOMPILE);
END;
GO

-- Permissao a ser aplicada somente junto com a instalacao autorizada.
GRANT EXECUTE ON dbo.SP_HDS3590_RCOM06 TO [CLT171703totvsread];
GO
