/*--------------------------------------------------------------------------
AUTOR: ENRICO CARDOSO
DESCRICAO: Lista os pedidos de compra e seus status para todos os grupos.
BANCO ESPERADO: CCW2SA_171703_PR_PD
OBJETOS VALIDADOS: SC7/SA2/SD1/SCR/SB1/SBM dos grupos 20, 23, 06 e 08;
                   SYS_USR.
ULTIMA VALIDACAO: 28/08/2026

Execucao de exemplo:
    SP_HDS3418_RCOM04 '01/01/2025', '31/12/2025';
--------------------------------------------------------------------------*/
ALTER PROCEDURE dbo.SP_HDS3418_RCOM04
(
    @MV_PAR01 VARCHAR(10),
    @MV_PAR02 VARCHAR(10)
)
AS
BEGIN
    SET NOCOUNT ON;

    SET @MV_PAR01 = SUBSTRING(@MV_PAR01, 7, 4)
                  + SUBSTRING(@MV_PAR01, 4, 2)
                  + SUBSTRING(@MV_PAR01, 1, 2);
    SET @MV_PAR02 = SUBSTRING(@MV_PAR02, 7, 4)
                  + SUBSTRING(@MV_PAR02, 4, 2)
                  + SUBSTRING(@MV_PAR02, 1, 2);

    ;WITH C7_ORIGEM AS
    (
        SELECT '20' AS GRUPO_COD, '20 - Grupo Agronelli' AS GRUPO_EMPRESA,
               C7_FILIAL, C7_NUM, C7_FORNECE, C7_LOJA, C7_AG_STAT,
               C7_ITEM, C7_PRODUTO, C7_DESCRI, C7_UM, C7_QUANT, C7_QUJE,
               C7_PRECO, C7_TOTAL, C7_VLDESC, C7_LOCAL, C7_NUMSC,
               C7_DATPRF, C7_EMISSAO, C7_COND, C7_CC, C7_EMITIDO,
               C7_NUMCOT, C7_CONTRA, C7_USER, C7_SOLICIT, C7_JUSTIFI,
               C7_RESIDUO, C7_QTDACLA, C7_TIPO, C7_CONAPRO, R_E_C_N_O_
        FROM dbo.SC7200
        WHERE D_E_L_E_T_ = '' AND C7_EMISSAO BETWEEN @MV_PAR01 AND @MV_PAR02

        UNION ALL

        SELECT '23', '23 - MTP', C7_FILIAL, C7_NUM, C7_FORNECE, C7_LOJA,
               CAST('' AS VARCHAR(1)), C7_ITEM, C7_PRODUTO, C7_DESCRI, C7_UM,
               C7_QUANT, C7_QUJE, C7_PRECO, C7_TOTAL, C7_VLDESC, C7_LOCAL,
               C7_NUMSC, C7_DATPRF, C7_EMISSAO, C7_COND, C7_CC, C7_EMITIDO,
               C7_NUMCOT, C7_CONTRA, C7_USER, C7_SOLICIT, C7_JUSTIFI,
               C7_RESIDUO, C7_QTDACLA, C7_TIPO, C7_CONAPRO, R_E_C_N_O_
        FROM dbo.SC7230
        WHERE D_E_L_E_T_ = '' AND C7_EMISSAO BETWEEN @MV_PAR01 AND @MV_PAR02

        UNION ALL

        SELECT '06', '06 - IADS', C7_FILIAL, C7_NUM, C7_FORNECE, C7_LOJA,
               CAST('' AS VARCHAR(1)), C7_ITEM, C7_PRODUTO, C7_DESCRI, C7_UM,
               C7_QUANT, C7_QUJE, C7_PRECO, C7_TOTAL, C7_VLDESC, C7_LOCAL,
               C7_NUMSC, C7_DATPRF, C7_EMISSAO, C7_COND, C7_CC, C7_EMITIDO,
               C7_NUMCOT, C7_CONTRA, C7_USER, C7_SOLICIT, C7_JUSTIFI,
               C7_RESIDUO, C7_QTDACLA, C7_TIPO, C7_CONAPRO, R_E_C_N_O_
        FROM dbo.SC7060
        WHERE D_E_L_E_T_ = '' AND C7_EMISSAO BETWEEN @MV_PAR01 AND @MV_PAR02

        UNION ALL

        SELECT '08', '08 - Neltech', C7_FILIAL, C7_NUM, C7_FORNECE, C7_LOJA,
               CAST('' AS VARCHAR(1)), C7_ITEM, C7_PRODUTO, C7_DESCRI, C7_UM,
               C7_QUANT, C7_QUJE, C7_PRECO, C7_TOTAL, C7_VLDESC, C7_LOCAL,
               C7_NUMSC, C7_DATPRF, C7_EMISSAO, C7_COND, C7_CC, C7_EMITIDO,
               C7_NUMCOT, C7_CONTRA, C7_USER, C7_SOLICIT, C7_JUSTIFI,
               C7_RESIDUO, C7_QTDACLA, C7_TIPO, C7_CONAPRO, R_E_C_N_O_
        FROM dbo.SC7080
        WHERE D_E_L_E_T_ = '' AND C7_EMISSAO BETWEEN @MV_PAR01 AND @MV_PAR02
    ),
    A2_ORIGEM AS
    (
        SELECT '20' AS GRUPO_COD, A2_COD, A2_LOJA, A2_NOME, A2_NREDUZ, A2_CGC
        FROM dbo.SA2200 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '23', A2_COD, A2_LOJA, A2_NOME, A2_NREDUZ, A2_CGC
        FROM dbo.SA2230 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '06', A2_COD, A2_LOJA, A2_NOME, A2_NREDUZ, A2_CGC
        FROM dbo.SA2060 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '08', A2_COD, A2_LOJA, A2_NOME, A2_NREDUZ, A2_CGC
        FROM dbo.SA2080 WHERE D_E_L_E_T_ = ''
    ),
    C7 AS
    (
        SELECT
            C7O.GRUPO_COD,
            C7O.GRUPO_EMPRESA,
            C7O.C7_FILIAL AS FILIAL,
            C7O.C7_NUM AS NUM_PC,
            A2.A2_COD AS COD_FORNECE,
            A2.A2_LOJA AS LJA_FORNECE,
            A2.A2_NOME AS NME_FORNECE,
            A2.A2_NREDUZ AS NMR_FORNECE,
            A2.A2_CGC AS CGC,
            CASE C7O.C7_AG_STAT
                WHEN '1' THEN 'Normal'
                WHEN ''  THEN 'Normal'
                WHEN '2' THEN 'Urgente'
                WHEN '3' THEN 'Contrato'
                WHEN '4' THEN 'Emergencial'
                WHEN '5' THEN 'Regularização'
                ELSE C7O.C7_AG_STAT
            END AS TIPO,
            C7O.C7_ITEM AS ITEM,
            C7O.C7_PRODUTO AS COD_PRODUTO,
            C7O.C7_DESCRI AS NME_PRODUTO,
            C7O.C7_UM AS UM,
            C7O.C7_QUANT AS QUANT,
            C7O.C7_QUJE AS QUANT_ENTREGUE,
            C7O.C7_QUANT - C7O.C7_QUJE AS QUANT_DIFF,
            C7O.C7_PRECO AS PRECO_ATUAL,
            C7O.C7_TOTAL AS TOTAL,
            C7O.C7_VLDESC AS VL_DESCONTO,
            C7O.C7_LOCAL AS ARMAZEM,
            C7O.C7_NUMSC AS NUM_SC,
            C7O.C7_DATPRF AS DT_NECESSIDADE,
            C7O.C7_EMISSAO AS DT_EMISSAO,
            C7O.C7_COND AS PAGAMENTO,
            C7O.C7_CC AS CC,
            C7O.C7_EMITIDO AS IMPRESSO,
            C7O.C7_NUMCOT AS COTACAO,
            C7O.C7_CONTRA AS CONTRATO,
            COALESCE(NULLIF(RTRIM(U.USR_NOME), ''), RTRIM(C7O.C7_USER)) AS COMPRADOR,
            C7O.C7_SOLICIT AS SOLICITANTE,
            C7O.C7_JUSTIFI AS JUSTIFICATIVA,
            C7O.R_E_C_N_O_ AS RECNO,
            CASE
                WHEN C7O.C7_QUJE = C7O.C7_QUANT THEN 'Recebido'
                WHEN C7O.C7_RESIDUO <> '' THEN 'Eliminado Residuo'
                WHEN C7O.C7_QTDACLA <> 0 THEN 'Recebido Prenota'
                WHEN C7O.C7_TIPO <> 1 THEN 'Contrato Parceria'
                WHEN C7O.C7_CONTRA <> '' THEN 'Gestao de Contratos'
                WHEN C7O.C7_CONAPRO = 'R' THEN 'Rejeitado Alçada'
                WHEN C7O.C7_CONAPRO = 'B' AND C7O.C7_QUJE < C7O.C7_QUANT THEN 'Alçada de Aprov.'
                WHEN C7O.C7_QUJE = 0 AND C7O.C7_QTDACLA = 0
                     AND C7O.C7_CONAPRO <> 'B' AND C7O.C7_TIPO = 1
                     AND C7O.C7_RESIDUO = '' THEN 'Pendente'
                WHEN C7O.C7_QUJE > 0 AND C7O.C7_QTDACLA = 0
                     AND C7O.C7_CONAPRO <> 'B' AND C7O.C7_TIPO = 1
                     AND C7O.C7_RESIDUO = '' THEN 'Recebido Parcial'
                ELSE 'SEM STATUS'
            END AS STATUS
        FROM C7_ORIGEM C7O
        INNER JOIN A2_ORIGEM A2
            ON A2.GRUPO_COD = C7O.GRUPO_COD
           AND A2.A2_COD = C7O.C7_FORNECE
           AND A2.A2_LOJA = C7O.C7_LOJA
        LEFT JOIN dbo.SYS_USR U
            ON U.USR_ID = C7O.C7_USER
           AND U.D_E_L_E_T_ = ''
    ),
    PRODUTOS AS
    (
        SELECT DISTINCT GRUPO_COD, COD_PRODUTO
        FROM C7
    ),
    D1_ORIGEM AS
    (
        SELECT '20' AS GRUPO_COD, D1_FILIAL, D1_PEDIDO, D1_ITEMPC, D1_DTDIGIT
        FROM dbo.SD1200 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '23', D1_FILIAL, D1_PEDIDO, D1_ITEMPC, D1_DTDIGIT
        FROM dbo.SD1230 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '06', D1_FILIAL, D1_PEDIDO, D1_ITEMPC, D1_DTDIGIT
        FROM dbo.SD1060 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '08', D1_FILIAL, D1_PEDIDO, D1_ITEMPC, D1_DTDIGIT
        FROM dbo.SD1080 WHERE D_E_L_E_T_ = ''
    ),
    D1 AS
    (
        SELECT GRUPO_COD, D1_FILIAL, D1_PEDIDO, D1_ITEMPC,
               MAX(D1_DTDIGIT) AS DT_DIGITACAO
        FROM D1_ORIGEM
        GROUP BY GRUPO_COD, D1_FILIAL, D1_PEDIDO, D1_ITEMPC
    ),
    CR_ORIGEM AS
    (
        SELECT '20' AS GRUPO_COD, CR_FILIAL, CR_NUM, CR_DATALIB, CR_TIPO, CR_STATUS
        FROM dbo.SCR200 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '23', CR_FILIAL, CR_NUM, CR_DATALIB, CR_TIPO, CR_STATUS
        FROM dbo.SCR230 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '06', CR_FILIAL, CR_NUM, CR_DATALIB, CR_TIPO, CR_STATUS
        FROM dbo.SCR060 WHERE D_E_L_E_T_ = ''
        UNION ALL
        SELECT '08', CR_FILIAL, CR_NUM, CR_DATALIB, CR_TIPO, CR_STATUS
        FROM dbo.SCR080 WHERE D_E_L_E_T_ = ''
    ),
    CR AS
    (
        SELECT GRUPO_COD, CR_FILIAL, CR_NUM, MAX(CR_DATALIB) AS DT_LIBERADO
        FROM CR_ORIGEM
        WHERE CR_TIPO = 'PC'
        GROUP BY GRUPO_COD, CR_FILIAL, CR_NUM
        HAVING MIN(CR_STATUS) = '03'
    ),
    CR2 AS
    (
        SELECT GRUPO_COD, CR_FILIAL, CR_NUM, MAX(CR_DATALIB) AS DT_LIBERADO
        FROM CR_ORIGEM
        WHERE CR_TIPO = 'SC'
        GROUP BY GRUPO_COD, CR_FILIAL, CR_NUM
        HAVING MIN(CR_STATUS) = '03'
    ),
    B1_ORIGEM AS
    (
        SELECT '20' AS GRUPO_COD, B1_COD, B1_GRUPO FROM dbo.SB1200 WHERE D_E_L_E_T_ = ''
        UNION ALL SELECT '23', B1_COD, B1_GRUPO FROM dbo.SB1230 WHERE D_E_L_E_T_ = ''
        UNION ALL SELECT '06', B1_COD, B1_GRUPO FROM dbo.SB1060 WHERE D_E_L_E_T_ = ''
        UNION ALL SELECT '08', B1_COD, B1_GRUPO FROM dbo.SB1080 WHERE D_E_L_E_T_ = ''
    ),
    BM_ORIGEM AS
    (
        SELECT '20' AS GRUPO_COD, BM_GRUPO, BM_DESC FROM dbo.SBM200 WHERE D_E_L_E_T_ = ''
        UNION ALL SELECT '23', BM_GRUPO, BM_DESC FROM dbo.SBM230 WHERE D_E_L_E_T_ = ''
        UNION ALL SELECT '06', BM_GRUPO, BM_DESC FROM dbo.SBM060 WHERE D_E_L_E_T_ = ''
        UNION ALL SELECT '08', BM_GRUPO, BM_DESC FROM dbo.SBM080 WHERE D_E_L_E_T_ = ''
    ),
    B1 AS
    (
        SELECT B1.GRUPO_COD, B1.B1_COD,
               RTRIM(BM.BM_GRUPO) + '-' + RTRIM(BM.BM_DESC) AS GRUPO
        FROM B1_ORIGEM B1
        INNER JOIN PRODUTOS P
            ON P.GRUPO_COD = B1.GRUPO_COD
           AND P.COD_PRODUTO = B1.B1_COD
        INNER JOIN BM_ORIGEM BM
            ON BM.GRUPO_COD = B1.GRUPO_COD
           AND BM.BM_GRUPO = B1.B1_GRUPO
    )
    SELECT
        C7.GRUPO_EMPRESA,
        C7.STATUS,
        C7.FILIAL,
        C7.NUM_PC,
        C7.COD_FORNECE,
        C7.LJA_FORNECE,
        C7.NME_FORNECE,
        C7.NMR_FORNECE,
        C7.CGC,
        C7.TIPO,
        C7.ITEM,
        C7.COD_PRODUTO,
        C7.NME_PRODUTO,
        B1.GRUPO,
        C7.UM,
        C7.QUANT,
        C7.QUANT_ENTREGUE,
        C7.QUANT_DIFF,
        COALESCE(ULTIMO_PC.ULTIMO_PRECO, C7.PRECO_ATUAL) AS ULTIMO_PRECO,
        C7.PRECO_ATUAL,
        C7.TOTAL,
        C7.VL_DESCONTO,
        C7.ARMAZEM,
        C7.NUM_SC,
        CONVERT(VARCHAR(10), CONVERT(DATE, C7.DT_NECESSIDADE, 112), 103) AS DT_NECESSIDADE,
        CONVERT(VARCHAR(10), CONVERT(DATE, C7.DT_EMISSAO, 112), 103) AS DT_EMISSAO,
        CONVERT(VARCHAR(10), CONVERT(DATE, CR2.DT_LIBERADO, 112), 103) AS DT_LIBERADO_SC,
        CONVERT(VARCHAR(10), CONVERT(DATE, CR.DT_LIBERADO, 112), 103) AS DT_LIBERADO_PC,
        CONVERT(VARCHAR(10), CONVERT(DATE, D1.DT_DIGITACAO, 112), 103) AS DT_DIGITACAO,
        C7.PAGAMENTO,
        C7.CC,
        C7.IMPRESSO,
        C7.COTACAO,
        C7.CONTRATO,
        C7.COMPRADOR,
        C7.SOLICITANTE,
        C7.JUSTIFICATIVA
    FROM C7
    LEFT JOIN D1
        ON D1.GRUPO_COD = C7.GRUPO_COD
       AND D1.D1_FILIAL = C7.FILIAL
       AND D1.D1_PEDIDO = C7.NUM_PC
       AND D1.D1_ITEMPC = C7.ITEM
    LEFT JOIN CR
        ON CR.GRUPO_COD = C7.GRUPO_COD
       AND CR.CR_FILIAL = C7.FILIAL
       AND CR.CR_NUM = C7.NUM_PC
    LEFT JOIN CR2
        ON CR2.GRUPO_COD = C7.GRUPO_COD
       AND CR2.CR_FILIAL = C7.FILIAL
       AND CR2.CR_NUM = C7.NUM_SC
    LEFT JOIN B1
        ON B1.GRUPO_COD = C7.GRUPO_COD
       AND B1.B1_COD = C7.COD_PRODUTO
    OUTER APPLY
    (
        SELECT TOP (1) H.C7_PRECO AS ULTIMO_PRECO
        FROM
        (
            SELECT C7_FILIAL, C7_NUM, C7_PRODUTO, C7_EMISSAO, C7_PRECO, R_E_C_N_O_
            FROM dbo.SC7200 WHERE C7.GRUPO_COD = '20' AND D_E_L_E_T_ = ''
            UNION ALL
            SELECT C7_FILIAL, C7_NUM, C7_PRODUTO, C7_EMISSAO, C7_PRECO, R_E_C_N_O_
            FROM dbo.SC7230 WHERE C7.GRUPO_COD = '23' AND D_E_L_E_T_ = ''
            UNION ALL
            SELECT C7_FILIAL, C7_NUM, C7_PRODUTO, C7_EMISSAO, C7_PRECO, R_E_C_N_O_
            FROM dbo.SC7060 WHERE C7.GRUPO_COD = '06' AND D_E_L_E_T_ = ''
            UNION ALL
            SELECT C7_FILIAL, C7_NUM, C7_PRODUTO, C7_EMISSAO, C7_PRECO, R_E_C_N_O_
            FROM dbo.SC7080 WHERE C7.GRUPO_COD = '08' AND D_E_L_E_T_ = ''
        ) H
        WHERE H.C7_FILIAL = C7.FILIAL
          AND H.C7_PRODUTO = C7.COD_PRODUTO
          AND H.C7_NUM <> C7.NUM_PC
          AND (H.C7_EMISSAO < C7.DT_EMISSAO
               OR (H.C7_EMISSAO = C7.DT_EMISSAO AND H.R_E_C_N_O_ < C7.RECNO))
        ORDER BY H.C7_EMISSAO DESC, H.R_E_C_N_O_ DESC
    ) ULTIMO_PC
    OPTION (RECOMPILE);
END;
