/*
 Objetivo: exibir os titulos em aberto de clientes funcionarios e, em cascata,
           os lancamentos de folha que possivelmente compoem cada titulo.
 Banco esperado: CCW2SA_171703_PR_PD.
 Objetos validados: SRA200, SRA230, SRA060,
                    RGB200, RGB230, RGB060, SRC200, SRC230, SRC060,
                    SRD200, SRD230, SRD060,
                    SA1200, SA1230, SA1060, SE1200, SE1230, SE1060,
                    SE2200, SE2230 e SE2060.
 Ultima validacao: 2026-09-17.

 Regras:
   - @DataEmissaoInicial deve ser informada no formato dd/mm/aaaa;
   - usa o historico de titulos do cliente funcionario para consumir primeiro
     os lancamentos de folha correspondentes a titulos ja baixados;
   - apresenta somente os titulos que continuam com E1_SALDO em aberto;
   - para exibicao, considera apenas titulos em aberto com E1_EMISSAO maior
     ou igual a @DataEmissaoInicial; o historico baixado continua sendo usado
     internamente para impedir reaproveitamento de lancamentos da folha;
   - desconsidera titulos cujo prefixo seja NCC;
   - no contas a receber, considera somente titulos com E1_TIPO = NF;
   - grupo 20 usa a verba 451, grupo 23 usa 460 e grupo 06 usa 465;
   - para cada grupo/filial/matricula/competencia, usa somente a etapa mais
     avancada encontrada: SRD (3), SRC (2), RGB (1);
   - consolida as linhas escolhidas por CPF e competencia;
   - casa o saldo do titulo com o total da folha por CPF e valor;
   - valores repetidos sao pareados por ocorrencia, do mais recente para o
     mais antigo, evitando reutilizar a mesma composicao em dois titulos;
   - ORIGEM RECEBER identifica o titulo; as linhas "  - FOLHA" logo abaixo
     mostram os componentes usados no casamento.
   - os titulos agrupados de folha com prefixo GPE sao lidos no SE2 e
     apresentados ao final como ORIGEM TITULO GPE, desde que o historico
     contenha DESCONTOS...DIVERSOS e E2_SALDO seja maior que zero.
*/
CREATE OR ALTER PROCEDURE dbo.SP_HDS3824_RFIN01
    @DataEmissaoInicial VARCHAR(10),
    @SomenteComCorrespondencia BIT = 0,
    @SaldoMinimo DECIMAL(16, 2) = 0.01
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @DataEmissaoInicialDate DATE =
        TRY_CONVERT(DATE, @DataEmissaoInicial, 103);

    IF @DataEmissaoInicialDate IS NULL
       OR @DataEmissaoInicial NOT LIKE '[0-3][0-9]/[0-1][0-9]/[1-2][0-9][0-9][0-9]'
    BEGIN
        THROW 50001, '@DataEmissaoInicial deve usar o formato dd/mm/aaaa.', 1;
    END;

    IF @SaldoMinimo < 0
    BEGIN
        THROW 50002, '@SaldoMinimo nao pode ser negativo.', 1;
    END;

    CREATE TABLE #FUNCIONARIO
    (
        CPF VARCHAR(11) COLLATE DATABASE_DEFAULT NOT NULL,
        GRUPO CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        MATRICULA VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        NOME VARCHAR(30) COLLATE DATABASE_DEFAULT NOT NULL,
        SITUACAO_FOLHA CHAR(1) COLLATE DATABASE_DEFAULT NOT NULL,
        ADMISSAO VARCHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        DEMISSAO VARCHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF, GRUPO, FILIAL, MATRICULA)
    );

    INSERT INTO #FUNCIONARIO
        (CPF, GRUPO, FILIAL, MATRICULA, NOME, SITUACAO_FOLHA, ADMISSAO, DEMISSAO)
    SELECT DISTINCT TRIM(RA.RA_CIC), '20', RA.RA_FILIAL, RA.RA_MAT,
           RA.RA_NOME, RA.RA_SITFOLH, RA.RA_ADMISSA, RA.RA_DEMISSA
    FROM dbo.SRA200 AS RA
    WHERE RA.D_E_L_E_T_ = '' AND TRIM(RA.RA_CIC) <> '' AND RA.RA_NOME NOT LIKE '%TEST%'
    UNION
    SELECT DISTINCT TRIM(RA.RA_CIC), '23', RA.RA_FILIAL, RA.RA_MAT,
           RA.RA_NOME, RA.RA_SITFOLH, RA.RA_ADMISSA, RA.RA_DEMISSA
    FROM dbo.SRA230 AS RA
    WHERE RA.D_E_L_E_T_ = '' AND TRIM(RA.RA_CIC) <> '' AND RA.RA_NOME NOT LIKE '%TEST%'
    UNION
    SELECT DISTINCT TRIM(RA.RA_CIC), '06', RA.RA_FILIAL, RA.RA_MAT,
           RA.RA_NOME, RA.RA_SITFOLH, RA.RA_ADMISSA, RA.RA_DEMISSA
    FROM dbo.SRA060 AS RA
    WHERE RA.D_E_L_E_T_ = '' AND TRIM(RA.RA_CIC) <> '' AND RA.RA_NOME NOT LIKE '%TEST%';

    CREATE TABLE #LOTACAO_FUNCIONARIO
    (
        CPF VARCHAR(11) COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
        EMP_FIL_FUNCIONARIO VARCHAR(MAX) COLLATE DATABASE_DEFAULT NOT NULL
    );

    ;WITH LOTACAO_DISTINTA AS
    (
        SELECT F.CPF, F.GRUPO, F.FILIAL,
               MAX(CASE WHEN F.DEMISSAO = '' AND F.SITUACAO_FOLHA <> 'D'
                        THEN 1 ELSE 0 END) AS CADASTRO_ATUAL,
               MAX(F.ADMISSAO) AS ULTIMA_ADMISSAO
        FROM #FUNCIONARIO AS F
        GROUP BY F.CPF, F.GRUPO, F.FILIAL
    )
    INSERT INTO #LOTACAO_FUNCIONARIO (CPF, EMP_FIL_FUNCIONARIO)
    SELECT L.CPF,
           STRING_AGG(CAST(CONCAT(L.GRUPO, '/', TRIM(L.FILIAL)) AS VARCHAR(MAX)), '; ')
               WITHIN GROUP
               (ORDER BY L.CADASTRO_ATUAL DESC, L.ULTIMA_ADMISSAO DESC,
                         L.GRUPO, L.FILIAL)
    FROM LOTACAO_DISTINTA AS L
    GROUP BY L.CPF;

    CREATE TABLE #CLIENTE
    (
        CPF VARCHAR(11) COLLATE DATABASE_DEFAULT NOT NULL,
        GRUPO CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        CLIENTE VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        LOJA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        NOME_CLIENTE VARCHAR(50) COLLATE DATABASE_DEFAULT NOT NULL,
        CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF, GRUPO, CLIENTE, LOJA)
    );

    INSERT INTO #CLIENTE (CPF, GRUPO, CLIENTE, LOJA, NOME_CLIENTE)
    SELECT DISTINCT TRIM(A1.A1_CGC), '20', A1.A1_COD, A1.A1_LOJA, A1.A1_NOME
    FROM dbo.SA1200 AS A1
    WHERE A1.D_E_L_E_T_ = '' AND TRIM(A1.A1_CGC) <> ''
      AND EXISTS (SELECT 1 FROM #FUNCIONARIO AS F WHERE F.CPF = TRIM(A1.A1_CGC))
    UNION
    SELECT DISTINCT TRIM(A1.A1_CGC), '23', A1.A1_COD, A1.A1_LOJA, A1.A1_NOME
    FROM dbo.SA1230 AS A1
    WHERE A1.D_E_L_E_T_ = '' AND TRIM(A1.A1_CGC) <> ''
      AND EXISTS (SELECT 1 FROM #FUNCIONARIO AS F WHERE F.CPF = TRIM(A1.A1_CGC))
    UNION
    SELECT DISTINCT TRIM(A1.A1_CGC), '06', A1.A1_COD, A1.A1_LOJA, A1.A1_NOME
    FROM dbo.SA1060 AS A1
    WHERE A1.D_E_L_E_T_ = '' AND TRIM(A1.A1_CGC) <> ''
      AND EXISTS (SELECT 1 FROM #FUNCIONARIO AS F WHERE F.CPF = TRIM(A1.A1_CGC));

    CREATE TABLE #TITULO
    (
        CPF VARCHAR(11) COLLATE DATABASE_DEFAULT NOT NULL,
        NOME_FUNCIONARIO VARCHAR(30) COLLATE DATABASE_DEFAULT NOT NULL,
        GRUPO_TITULO CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL_TITULO VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        PREFIXO VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        NUMERO VARCHAR(9) COLLATE DATABASE_DEFAULT NOT NULL,
        PARCELA VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        TIPO VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        CLIENTE VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        LOJA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        NOME_CLIENTE VARCHAR(50) COLLATE DATABASE_DEFAULT NOT NULL,
        EMISSAO VARCHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        VENCIMENTO VARCHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        BAIXA VARCHAR(8) COLLATE DATABASE_DEFAULT NOT NULL,
        STATUS_TITULO VARCHAR(7) COLLATE DATABASE_DEFAULT NOT NULL,
        VALOR_TITULO DECIMAL(16, 2) NOT NULL,
        SALDO_ABERTO DECIMAL(16, 2) NOT NULL,
        VALOR_CASAMENTO DECIMAL(16, 2) NOT NULL,
        HISTORICO VARCHAR(70) COLLATE DATABASE_DEFAULT NOT NULL,
        RECNO_TITULO BIGINT NOT NULL,
        PRIMARY KEY (GRUPO_TITULO, RECNO_TITULO)
    );

    INSERT INTO #TITULO
        (CPF, NOME_FUNCIONARIO, GRUPO_TITULO, FILIAL_TITULO, PREFIXO,
         NUMERO, PARCELA, TIPO, CLIENTE, LOJA, NOME_CLIENTE, EMISSAO,
         VENCIMENTO, BAIXA, STATUS_TITULO, VALOR_TITULO, SALDO_ABERTO,
         VALOR_CASAMENTO, HISTORICO, RECNO_TITULO)
    SELECT C.CPF, F.NOME, '20', E1.E1_FILIAL, E1.E1_PREFIXO, E1.E1_NUM,
           E1.E1_PARCELA, E1.E1_TIPO, E1.E1_CLIENTE, E1.E1_LOJA,
           C.NOME_CLIENTE, E1.E1_EMISSAO, E1.E1_VENCREA, E1.E1_BAIXA,
           CASE WHEN E1.E1_SALDO >= @SaldoMinimo THEN 'ABERTO' ELSE 'BAIXADO' END,
           CONVERT(DECIMAL(16, 2), E1.E1_VALOR),
           CONVERT(DECIMAL(16, 2), E1.E1_SALDO),
           CASE WHEN E1.E1_SALDO >= @SaldoMinimo
                THEN CONVERT(DECIMAL(16, 2), E1.E1_SALDO)
                ELSE CONVERT(DECIMAL(16, 2), E1.E1_VALOR) END,
           E1.E1_HIST, E1.R_E_C_N_O_
    FROM dbo.SE1200 AS E1
    INNER JOIN #CLIENTE AS C
        ON C.GRUPO = '20' AND C.CLIENTE = E1.E1_CLIENTE AND C.LOJA = E1.E1_LOJA
    CROSS APPLY
    (
        SELECT TOP (1) F0.NOME
        FROM #FUNCIONARIO AS F0
        WHERE F0.CPF = C.CPF
        ORDER BY CASE WHEN F0.GRUPO = '20' THEN 0 ELSE 1 END,
                 F0.GRUPO, F0.FILIAL, F0.MATRICULA
    ) AS F
    WHERE E1.D_E_L_E_T_ = ''
      AND TRIM(E1.E1_PREFIXO) <> 'NCC'
      AND TRIM(E1.E1_TIPO) = 'NF'
      AND ((E1.E1_SALDO >= @SaldoMinimo
            AND E1.E1_EMISSAO >= CONVERT(CHAR(8), @DataEmissaoInicialDate, 112))
           OR (E1.E1_SALDO < @SaldoMinimo AND E1.E1_BAIXA <> ''))
    UNION ALL
    SELECT C.CPF, F.NOME, '23', E1.E1_FILIAL, E1.E1_PREFIXO, E1.E1_NUM,
           E1.E1_PARCELA, E1.E1_TIPO, E1.E1_CLIENTE, E1.E1_LOJA,
           C.NOME_CLIENTE, E1.E1_EMISSAO, E1.E1_VENCREA, E1.E1_BAIXA,
           CASE WHEN E1.E1_SALDO >= @SaldoMinimo THEN 'ABERTO' ELSE 'BAIXADO' END,
           CONVERT(DECIMAL(16, 2), E1.E1_VALOR),
           CONVERT(DECIMAL(16, 2), E1.E1_SALDO),
           CASE WHEN E1.E1_SALDO >= @SaldoMinimo
                THEN CONVERT(DECIMAL(16, 2), E1.E1_SALDO)
                ELSE CONVERT(DECIMAL(16, 2), E1.E1_VALOR) END,
           E1.E1_HIST, E1.R_E_C_N_O_
    FROM dbo.SE1230 AS E1
    INNER JOIN #CLIENTE AS C
        ON C.GRUPO = '23' AND C.CLIENTE = E1.E1_CLIENTE AND C.LOJA = E1.E1_LOJA
    CROSS APPLY
    (
        SELECT TOP (1) F0.NOME
        FROM #FUNCIONARIO AS F0
        WHERE F0.CPF = C.CPF
        ORDER BY CASE WHEN F0.GRUPO = '23' THEN 0 ELSE 1 END,
                 F0.GRUPO, F0.FILIAL, F0.MATRICULA
    ) AS F
    WHERE E1.D_E_L_E_T_ = ''
      AND TRIM(E1.E1_PREFIXO) <> 'NCC'
      AND TRIM(E1.E1_TIPO) = 'NF'
      AND ((E1.E1_SALDO >= @SaldoMinimo
            AND E1.E1_EMISSAO >= CONVERT(CHAR(8), @DataEmissaoInicialDate, 112))
           OR (E1.E1_SALDO < @SaldoMinimo AND E1.E1_BAIXA <> ''))
    UNION ALL
    SELECT C.CPF, F.NOME, '06', E1.E1_FILIAL, E1.E1_PREFIXO, E1.E1_NUM,
           E1.E1_PARCELA, E1.E1_TIPO, E1.E1_CLIENTE, E1.E1_LOJA,
           C.NOME_CLIENTE, E1.E1_EMISSAO, E1.E1_VENCREA, E1.E1_BAIXA,
           CASE WHEN E1.E1_SALDO >= @SaldoMinimo THEN 'ABERTO' ELSE 'BAIXADO' END,
           CONVERT(DECIMAL(16, 2), E1.E1_VALOR),
           CONVERT(DECIMAL(16, 2), E1.E1_SALDO),
           CASE WHEN E1.E1_SALDO >= @SaldoMinimo
                THEN CONVERT(DECIMAL(16, 2), E1.E1_SALDO)
                ELSE CONVERT(DECIMAL(16, 2), E1.E1_VALOR) END,
           E1.E1_HIST, E1.R_E_C_N_O_
    FROM dbo.SE1060 AS E1
    INNER JOIN #CLIENTE AS C
        ON C.GRUPO = '06' AND C.CLIENTE = E1.E1_CLIENTE AND C.LOJA = E1.E1_LOJA
    CROSS APPLY
    (
        SELECT TOP (1) F0.NOME
        FROM #FUNCIONARIO AS F0
        WHERE F0.CPF = C.CPF
        ORDER BY CASE WHEN F0.GRUPO = '06' THEN 0 ELSE 1 END,
                 F0.GRUPO, F0.FILIAL, F0.MATRICULA
    ) AS F
    WHERE E1.D_E_L_E_T_ = ''
      AND TRIM(E1.E1_PREFIXO) <> 'NCC'
      AND TRIM(E1.E1_TIPO) = 'NF'
      AND ((E1.E1_SALDO >= @SaldoMinimo
            AND E1.E1_EMISSAO >= CONVERT(CHAR(8), @DataEmissaoInicialDate, 112))
           OR (E1.E1_SALDO < @SaldoMinimo AND E1.E1_BAIXA <> ''));

    CREATE TABLE #FOLHA_BRUTA
    (
        CPF VARCHAR(11) COLLATE DATABASE_DEFAULT NOT NULL,
        GRUPO_FOLHA CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL_FOLHA VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        MATRICULA VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        COMPETENCIA CHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        VERBA CHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        FONTE CHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        PRIORIDADE TINYINT NOT NULL,
        PROCESSO VARCHAR(5) COLLATE DATABASE_DEFAULT NOT NULL,
        ROTEIRO VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        SEQUENCIA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        VALOR_COMPONENTE DECIMAL(16, 2) NOT NULL,
        RECNO_FOLHA BIGINT NOT NULL,
        PRIMARY KEY (GRUPO_FOLHA, FONTE, RECNO_FOLHA)
    );

    INSERT INTO #FOLHA_BRUTA
        (CPF, GRUPO_FOLHA, FILIAL_FOLHA, MATRICULA, COMPETENCIA, VERBA,
         FONTE, PRIORIDADE, PROCESSO, ROTEIRO, SEQUENCIA,
         VALOR_COMPONENTE, RECNO_FOLHA)
    SELECT F.CPF, '20', R.RGB_FILIAL, R.RGB_MAT, R.RGB_PERIOD, R.RGB_PD,
           'RGB', 1, R.RGB_PROCES, R.RGB_ROTEIR, R.RGB_SEQ,
           CONVERT(DECIMAL(16, 2), R.RGB_VALOR), R.R_E_C_N_O_
    FROM dbo.RGB200 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '20' AND F.FILIAL = R.RGB_FILIAL AND F.MATRICULA = R.RGB_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RGB_PD = '451' AND R.RGB_PERIOD <> ''
    UNION ALL
    SELECT F.CPF, '23', R.RGB_FILIAL, R.RGB_MAT, R.RGB_PERIOD, R.RGB_PD,
           'RGB', 1, R.RGB_PROCES, R.RGB_ROTEIR, R.RGB_SEQ,
           CONVERT(DECIMAL(16, 2), R.RGB_VALOR), R.R_E_C_N_O_
    FROM dbo.RGB230 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '23' AND F.FILIAL = R.RGB_FILIAL AND F.MATRICULA = R.RGB_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RGB_PD = '460' AND R.RGB_PERIOD <> ''
    UNION ALL
    SELECT F.CPF, '06', R.RGB_FILIAL, R.RGB_MAT, R.RGB_PERIOD, R.RGB_PD,
           'RGB', 1, R.RGB_PROCES, R.RGB_ROTEIR, R.RGB_SEQ,
           CONVERT(DECIMAL(16, 2), R.RGB_VALOR), R.R_E_C_N_O_
    FROM dbo.RGB060 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '06' AND F.FILIAL = R.RGB_FILIAL AND F.MATRICULA = R.RGB_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RGB_PD = '465' AND R.RGB_PERIOD <> ''
    UNION ALL
    SELECT F.CPF, '20', R.RC_FILIAL, R.RC_MAT, R.RC_PERIODO, R.RC_PD,
           'SRC', 2, R.RC_PROCES, R.RC_ROTEIR, R.RC_SEQ,
           CONVERT(DECIMAL(16, 2), R.RC_VALOR), R.R_E_C_N_O_
    FROM dbo.SRC200 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '20' AND F.FILIAL = R.RC_FILIAL AND F.MATRICULA = R.RC_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RC_PD = '451' AND R.RC_PERIODO <> ''
    UNION ALL
    SELECT F.CPF, '23', R.RC_FILIAL, R.RC_MAT, R.RC_PERIODO, R.RC_PD,
           'SRC', 2, R.RC_PROCES, R.RC_ROTEIR, R.RC_SEQ,
           CONVERT(DECIMAL(16, 2), R.RC_VALOR), R.R_E_C_N_O_
    FROM dbo.SRC230 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '23' AND F.FILIAL = R.RC_FILIAL AND F.MATRICULA = R.RC_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RC_PD = '460' AND R.RC_PERIODO <> ''
    UNION ALL
    SELECT F.CPF, '06', R.RC_FILIAL, R.RC_MAT, R.RC_PERIODO, R.RC_PD,
           'SRC', 2, R.RC_PROCES, R.RC_ROTEIR, R.RC_SEQ,
           CONVERT(DECIMAL(16, 2), R.RC_VALOR), R.R_E_C_N_O_
    FROM dbo.SRC060 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '06' AND F.FILIAL = R.RC_FILIAL AND F.MATRICULA = R.RC_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RC_PD = '465' AND R.RC_PERIODO <> ''
    UNION ALL
    SELECT F.CPF, '20', R.RD_FILIAL, R.RD_MAT, R.RD_DATARQ, R.RD_PD,
           'SRD', 3, R.RD_PROCES, R.RD_ROTEIR, R.RD_SEQ,
           CONVERT(DECIMAL(16, 2), R.RD_VALOR), R.R_E_C_N_O_
    FROM dbo.SRD200 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '20' AND F.FILIAL = R.RD_FILIAL AND F.MATRICULA = R.RD_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RD_PD = '451' AND R.RD_DATARQ <> ''
    UNION ALL
    SELECT F.CPF, '23', R.RD_FILIAL, R.RD_MAT, R.RD_DATARQ, R.RD_PD,
           'SRD', 3, R.RD_PROCES, R.RD_ROTEIR, R.RD_SEQ,
           CONVERT(DECIMAL(16, 2), R.RD_VALOR), R.R_E_C_N_O_
    FROM dbo.SRD230 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '23' AND F.FILIAL = R.RD_FILIAL AND F.MATRICULA = R.RD_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RD_PD = '460' AND R.RD_DATARQ <> ''
    UNION ALL
    SELECT F.CPF, '06', R.RD_FILIAL, R.RD_MAT, R.RD_DATARQ, R.RD_PD,
           'SRD', 3, R.RD_PROCES, R.RD_ROTEIR, R.RD_SEQ,
           CONVERT(DECIMAL(16, 2), R.RD_VALOR), R.R_E_C_N_O_
    FROM dbo.SRD060 AS R
    INNER JOIN #FUNCIONARIO AS F
        ON F.GRUPO = '06' AND F.FILIAL = R.RD_FILIAL AND F.MATRICULA = R.RD_MAT
    WHERE R.D_E_L_E_T_ = '' AND R.RD_PD = '465' AND R.RD_DATARQ <> '';

    CREATE TABLE #FOLHA_ESCOLHIDA
    (
        CPF VARCHAR(11) COLLATE DATABASE_DEFAULT NOT NULL,
        GRUPO_FOLHA CHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        FILIAL_FOLHA VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        MATRICULA VARCHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        COMPETENCIA CHAR(6) COLLATE DATABASE_DEFAULT NOT NULL,
        VERBA CHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        FONTE CHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        PROCESSO VARCHAR(5) COLLATE DATABASE_DEFAULT NOT NULL,
        ROTEIRO VARCHAR(3) COLLATE DATABASE_DEFAULT NOT NULL,
        SEQUENCIA VARCHAR(2) COLLATE DATABASE_DEFAULT NOT NULL,
        VALOR_COMPONENTE DECIMAL(16, 2) NOT NULL,
        RECNO_FOLHA BIGINT NOT NULL,
        PRIMARY KEY (GRUPO_FOLHA, FONTE, RECNO_FOLHA)
    );

    INSERT INTO #FOLHA_ESCOLHIDA
    SELECT B.CPF, B.GRUPO_FOLHA, B.FILIAL_FOLHA, B.MATRICULA,
           B.COMPETENCIA, B.VERBA, B.FONTE, B.PROCESSO, B.ROTEIRO,
           B.SEQUENCIA, B.VALOR_COMPONENTE, B.RECNO_FOLHA
    FROM #FOLHA_BRUTA AS B
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM #FOLHA_BRUTA AS B2
        WHERE B2.GRUPO_FOLHA = B.GRUPO_FOLHA
          AND B2.FILIAL_FOLHA = B.FILIAL_FOLHA
          AND B2.MATRICULA = B.MATRICULA
          AND B2.COMPETENCIA = B.COMPETENCIA
          AND B2.PRIORIDADE > B.PRIORIDADE
    );

    ;WITH FOLHA_TOTAL AS
    (
        SELECT F.CPF, F.COMPETENCIA, SUM(F.VALOR_COMPONENTE) AS VALOR_FOLHA,
               COUNT(*) AS QTD_COMPONENTES
        FROM #FOLHA_ESCOLHIDA AS F
        GROUP BY F.CPF, F.COMPETENCIA
    ),
    FOLHA_RANQUEADA AS
    (
        SELECT F.*,
               ROW_NUMBER() OVER
               (
                   PARTITION BY F.CPF, CONVERT(BIGINT, ROUND(F.VALOR_FOLHA * 100, 0))
                   ORDER BY F.COMPETENCIA DESC
               ) AS OCORRENCIA_VALOR
        FROM FOLHA_TOTAL AS F
    ),
    TITULO_RANQUEADO AS
    (
        SELECT T.*,
               ROW_NUMBER() OVER
               (
                   PARTITION BY T.CPF, CONVERT(BIGINT, ROUND(T.VALOR_CASAMENTO * 100, 0))
                   ORDER BY CASE WHEN T.STATUS_TITULO = 'BAIXADO' THEN 0 ELSE 1 END,
                            COALESCE(NULLIF(T.BAIXA, ''), T.EMISSAO) DESC,
                            T.VENCIMENTO DESC,
                            T.GRUPO_TITULO, T.RECNO_TITULO DESC
               ) AS OCORRENCIA_VALOR
        FROM #TITULO AS T
    ),
    CASAMENTO AS
    (
        SELECT T.*, F.COMPETENCIA, F.VALOR_FOLHA, F.QTD_COMPONENTES,
               CASE
                   WHEN F.CPF IS NOT NULL THEN 'VALOR_ENCONTRADO_NA_FOLHA'
                   WHEN EXISTS
                        (
                            SELECT 1
                            FROM FOLHA_RANQUEADA AS FX
                            WHERE FX.CPF = T.CPF
                              AND CONVERT(BIGINT, ROUND(FX.VALOR_FOLHA * 100, 0)) =
                                  CONVERT(BIGINT, ROUND(T.VALOR_CASAMENTO * 100, 0))
                        ) THEN 'VALOR_FOLHA_JA_CONSUMIDO'
                   ELSE 'SEM_COMPOSICAO_EXATA'
               END AS STATUS_CASAMENTO
        FROM TITULO_RANQUEADO AS T
        LEFT JOIN FOLHA_RANQUEADA AS F
           ON F.CPF = T.CPF
           AND F.OCORRENCIA_VALOR = T.OCORRENCIA_VALOR
           AND CONVERT(BIGINT, ROUND(F.VALOR_FOLHA * 100, 0)) =
               CONVERT(BIGINT, ROUND(T.VALOR_CASAMENTO * 100, 0))
    ),
    CASCATA AS
    (
        SELECT 'RECEBER' AS ORIGEM, C.CPF, C.NOME_FUNCIONARIO AS NOME,
               C.VALOR_TITULO AS VALOR, C.SALDO_ABERTO AS SALDO,
               C.GRUPO_TITULO AS EMP_TITULO,
               C.FILIAL_TITULO AS FIL_TITULO, C.NUMERO AS NUM, C.PREFIXO,
               C.TIPO AS TIPO,
               CONVERT(CHAR(10), TRY_CONVERT(DATE, C.EMISSAO, 112), 103) AS EMISSAO,
               CONVERT(CHAR(10), TRY_CONVERT(DATE, C.VENCIMENTO, 112), 103) AS VENCIMENTO,
               L.EMP_FIL_FUNCIONARIO,
               CAST(NULL AS VARCHAR(6)) AS MATRICULA,
               CAST(NULL AS CHAR(6)) AS PERIODO,
               C.EMISSAO AS ORDEM_DATA, C.GRUPO_TITULO AS ORDEM_EMP,
               C.RECNO_TITULO AS ORDEM_TITULO, 1 AS ORDEM_NIVEL,
               CAST(0 AS BIGINT) AS ORDEM_COMPONENTE
        FROM CASAMENTO AS C
        INNER JOIN #LOTACAO_FUNCIONARIO AS L ON L.CPF = C.CPF
        WHERE C.STATUS_TITULO = 'ABERTO'
          AND (@SomenteComCorrespondencia = 0 OR C.COMPETENCIA IS NOT NULL)

        UNION ALL

        SELECT '  - FOLHA', C.CPF, C.NOME_FUNCIONARIO,
               F.VALOR_COMPONENTE, CAST(NULL AS DECIMAL(16, 2)),
               CAST(NULL AS CHAR(2)),
               CAST(NULL AS VARCHAR(6)), CAST(NULL AS VARCHAR(9)),
               CAST(NULL AS VARCHAR(3)), CAST(NULL AS VARCHAR(3)),
               CAST(NULL AS CHAR(10)),
               CAST(NULL AS CHAR(10)), L.EMP_FIL_FUNCIONARIO,
               F.MATRICULA, F.COMPETENCIA,
               C.EMISSAO, C.GRUPO_TITULO, C.RECNO_TITULO, 2,
               F.RECNO_FOLHA
        FROM CASAMENTO AS C
        INNER JOIN #FOLHA_ESCOLHIDA AS F
            ON F.CPF = C.CPF AND F.COMPETENCIA = C.COMPETENCIA
        INNER JOIN #LOTACAO_FUNCIONARIO AS L ON L.CPF = C.CPF
        WHERE C.STATUS_TITULO = 'ABERTO'
          AND (@SomenteComCorrespondencia = 0 OR C.COMPETENCIA IS NOT NULL)
    ),
    GPE AS
    (
        SELECT 'TITULO GPE' AS ORIGEM, CAST(NULL AS VARCHAR(11)) AS CPF,
               E2.E2_NOMFOR AS NOME, CONVERT(DECIMAL(16, 2), E2.E2_VALOR) AS VALOR,
               CONVERT(DECIMAL(16, 2), E2.E2_SALDO) AS SALDO,
               CAST('20' AS CHAR(2)) AS EMP_TITULO, E2.E2_FILIAL AS FIL_TITULO,
               E2.E2_NUM AS NUM, E2.E2_PREFIXO AS PREFIXO,
               E2.E2_TIPO AS TIPO,
               CONVERT(CHAR(10), TRY_CONVERT(DATE, E2.E2_EMISSAO, 112), 103) AS EMISSAO,
               CONVERT(CHAR(10), TRY_CONVERT(DATE, E2.E2_VENCREA, 112), 103) AS VENCIMENTO,
               CAST(NULL AS VARCHAR(MAX)) AS EMP_FIL_FUNCIONARIO,
               CAST(NULL AS VARCHAR(6)) AS MATRICULA,
               CAST(NULL AS CHAR(6)) AS PERIODO,
               E2.E2_EMISSAO AS ORDEM_DATA, CAST('20' AS CHAR(2)) AS ORDEM_EMP,
               E2.R_E_C_N_O_ AS ORDEM_TITULO, 1 AS ORDEM_NIVEL,
               CAST(0 AS BIGINT) AS ORDEM_COMPONENTE
        FROM dbo.SE2200 AS E2
        WHERE E2.D_E_L_E_T_ = '' AND TRIM(E2.E2_PREFIXO) = 'GPE'
          AND E2.E2_HIST LIKE '%DESCONTOS%DIVERSOS%'
          AND E2.E2_SALDO > 0
          AND E2.E2_EMISSAO >= CONVERT(CHAR(8), @DataEmissaoInicialDate, 112)

        UNION ALL

        SELECT 'TITULO GPE', CAST(NULL AS VARCHAR(11)), E2.E2_NOMFOR,
               CONVERT(DECIMAL(16, 2), E2.E2_VALOR),
               CONVERT(DECIMAL(16, 2), E2.E2_SALDO), '23', E2.E2_FILIAL,
               E2.E2_NUM, E2.E2_PREFIXO, E2.E2_TIPO,
               CONVERT(CHAR(10), TRY_CONVERT(DATE, E2.E2_EMISSAO, 112), 103),
               CONVERT(CHAR(10), TRY_CONVERT(DATE, E2.E2_VENCREA, 112), 103),
               CAST(NULL AS VARCHAR(MAX)), CAST(NULL AS VARCHAR(6)),
               CAST(NULL AS CHAR(6)), E2.E2_EMISSAO, '23', E2.R_E_C_N_O_, 1,
               CAST(0 AS BIGINT)
        FROM dbo.SE2230 AS E2
        WHERE E2.D_E_L_E_T_ = '' AND TRIM(E2.E2_PREFIXO) = 'GPE'
          AND E2.E2_HIST LIKE '%DESCONTOS%DIVERSOS%'
          AND E2.E2_SALDO > 0
          AND E2.E2_EMISSAO >= CONVERT(CHAR(8), @DataEmissaoInicialDate, 112)

        UNION ALL

        SELECT 'TITULO GPE', CAST(NULL AS VARCHAR(11)), E2.E2_NOMFOR,
               CONVERT(DECIMAL(16, 2), E2.E2_VALOR),
               CONVERT(DECIMAL(16, 2), E2.E2_SALDO), '06', E2.E2_FILIAL,
               E2.E2_NUM, E2.E2_PREFIXO, E2.E2_TIPO,
               CONVERT(CHAR(10), TRY_CONVERT(DATE, E2.E2_EMISSAO, 112), 103),
               CONVERT(CHAR(10), TRY_CONVERT(DATE, E2.E2_VENCREA, 112), 103),
               CAST(NULL AS VARCHAR(MAX)), CAST(NULL AS VARCHAR(6)),
               CAST(NULL AS CHAR(6)), E2.E2_EMISSAO, '06', E2.R_E_C_N_O_, 1,
               CAST(0 AS BIGINT)
        FROM dbo.SE2060 AS E2
        WHERE E2.D_E_L_E_T_ = '' AND TRIM(E2.E2_PREFIXO) = 'GPE'
          AND E2.E2_HIST LIKE '%DESCONTOS%DIVERSOS%'
          AND E2.E2_SALDO > 0
          AND E2.E2_EMISSAO >= CONVERT(CHAR(8), @DataEmissaoInicialDate, 112)
    ),
    SAIDA AS
    (
        SELECT C.*, 1 AS ORDEM_BLOCO FROM CASCATA AS C
        UNION ALL
        SELECT G.*, 2 FROM GPE AS G
    )
    SELECT ORIGEM, CPF, NOME, VALOR, SALDO, EMP_TITULO, FIL_TITULO, NUM,
           PREFIXO, TIPO,
           EMISSAO, VENCIMENTO, EMP_FIL_FUNCIONARIO, MATRICULA, PERIODO
    FROM SAIDA
    ORDER BY ORDEM_BLOCO, NOME, CPF, ORDEM_NIVEL, ORDEM_DATA DESC,
             ORDEM_EMP, ORDEM_TITULO DESC, ORDEM_COMPONENTE;
END;
