/*=============================================================================
  Fonte.........: dbo.SP_HDS0000_RFIS04
  Objetivo......: Resultado 3 - confronto independente entre SFT e CT2 por
                  filial e conta, considerando somente rotinas fiscais na CT2.
  Grupo..........: 20 - Grupo Agronelli
  Banco esperado: CCW2SA_171703_PR_PD
  Objetos.......: SFT200 e CT2200
  Validado em...: 2026-08-28, somente leitura, via MCP dbcode.
=============================================================================*/
CREATE OR ALTER PROCEDURE dbo.SP_HDS0000_RFIS04
    @DATA_INICIAL VARCHAR(10)=NULL, @DATA_FINAL VARCHAR(10)=NULL, @FILIAL VARCHAR(6)=NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @DI DATE, @DF DATE;
    SELECT @DATA_INICIAL=NULLIF(LTRIM(RTRIM(@DATA_INICIAL)),''), @DATA_FINAL=NULLIF(LTRIM(RTRIM(@DATA_FINAL)),''), @FILIAL=NULLIF(LTRIM(RTRIM(@FILIAL)),'');
    SELECT @DI=CASE WHEN @DATA_INICIAL IS NULL THEN DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1) ELSE COALESCE(TRY_CONVERT(DATE,@DATA_INICIAL,112),TRY_CONVERT(DATE,@DATA_INICIAL,103),TRY_CONVERT(DATE,@DATA_INICIAL,23)) END;
    SELECT @DF=CASE WHEN @DATA_FINAL IS NULL THEN EOMONTH(GETDATE()) ELSE COALESCE(TRY_CONVERT(DATE,@DATA_FINAL,112),TRY_CONVERT(DATE,@DATA_FINAL,103),TRY_CONVERT(DATE,@DATA_FINAL,23)) END;
    IF @DI IS NULL OR @DF IS NULL THROW 50001,'Datas invalidas. Use AAAAMMDD, DD/MM/AAAA ou AAAA-MM-DD.',1;
    IF @DI>@DF THROW 50001,'DATA_INICIAL nao pode ser maior que DATA_FINAL.',1;
    SELECT @DATA_INICIAL=CONVERT(VARCHAR(8),@DI,112),@DATA_FINAL=CONVERT(VARCHAR(8),@DF,112);

    ;WITH CONTAS AS
    (
        SELECT * FROM (VALUES
          ('201010901','IRRF A RECOLHER','C'),('201010902','ICMS A RECOLHER','C'),('201010903','RETENCOES P/ A SEGURIDADE SOCIAL','C'),
          ('201010905','ISSQN A RECOLHER','C'),('201010906','RETENCOES PIS COFINS CSL - PCC','C'),('201010908','ICMS ST A RECOLHER','C'),
          ('201010911','ICMS DIF ALIQUOTA A RECOLHER','C'),('201010913','IPI A RECOLHER - CIRCULANTE','C'),('201010914','PIS A RECOLHER - CIRCULANTE','C'),
          ('201010915','COFINS A RECOLHER - CIRCULANTE','C'),('101021001','ICMS A RECUPERAR','D'),('101021002','PIS NAO CUMULATIVO A RECUPERAR','D'),
          ('101021003','COFINS NAO CUMULATIVO A RECUPERAR','D'),('101021004','IPI A RECUPERAR','D'),('101021006','ICMS ST A RECUPERAR','D'),('101021105','ISS A RECUPERAR','D')
        ) X(CONTA,DESCRICAO_CONTA,NATUREZA_SALDO)
    ),
    FISCAL AS
    (
        SELECT S.FT_FILIAL FILIAL,I.CONTA,COUNT_BIG(*) QUANTIDADE_REGISTROS,
               SUM(CONVERT(DECIMAL(19,4),I.VALOR_IMPOSTO)) VALOR_FISCAL
        FROM dbo.SFT200 S
        CROSS APPLY (VALUES
          (CASE WHEN S.FT_TIPOMOV='E' THEN '101021001' ELSE '201010902' END,S.FT_VALICM),
          (CASE WHEN S.FT_TIPOMOV='E' THEN '101021006' ELSE '201010908' END,S.FT_ICMSRET),
          ('201010911',S.FT_ICMSDIF),
          (CASE WHEN S.FT_TIPOMOV='E' THEN '101021004' ELSE '201010913' END,S.FT_VALIPI),
          (CASE WHEN S.FT_TIPOMOV='E' THEN '101021002' ELSE '201010914' END,S.FT_VALPIS),
          (CASE WHEN S.FT_TIPOMOV='E' THEN '101021003' ELSE '201010915' END,S.FT_VALCOF),
          ('201010901',S.FT_VALIRR),('201010903',S.FT_VALINS),('201010905',S.FT_ISSSUB),
          ('201010906',S.FT_VRETPIS),('201010906',S.FT_VRETCOF),('201010906',S.FT_VRETCSL)
        ) I(CONTA,VALOR_IMPOSTO)
        WHERE S.D_E_L_E_T_='' AND S.FT_ENTRADA BETWEEN @DATA_INICIAL AND @DATA_FINAL
          AND I.VALOR_IMPOSTO<>0 AND (@FILIAL IS NULL OR S.FT_FILIAL=@FILIAL)
        GROUP BY S.FT_FILIAL,I.CONTA
    ),
    CONTABIL_BASE AS
    (
        SELECT T.CT2_FILIAL FILIAL,M.CONTA,C.NATUREZA_SALDO,M.LADO,T.CT2_VALOR
        FROM dbo.CT2200 T
        CROSS APPLY (VALUES(RTRIM(T.CT2_DEBITO),'DEBITO'),(RTRIM(T.CT2_CREDIT),'CREDITO')) M(CONTA,LADO)
        INNER JOIN CONTAS C ON C.CONTA COLLATE DATABASE_DEFAULT=M.CONTA COLLATE DATABASE_DEFAULT
        WHERE T.D_E_L_E_T_='' AND T.CT2_DATA BETWEEN @DATA_INICIAL AND @DATA_FINAL
          AND RTRIM(T.CT2_ROTINA) IN ('CTBANFE','CTBANFS','MATA103')
          AND (@FILIAL IS NULL OR T.CT2_FILIAL=@FILIAL)
    ),
    CONTABIL AS
    (
        SELECT FILIAL,CONTA,COUNT_BIG(*) QUANTIDADE_LANCAMENTOS,
          SUM(CONVERT(DECIMAL(19,4),CASE WHEN NATUREZA_SALDO='D' AND LADO='DEBITO' THEN CT2_VALOR WHEN NATUREZA_SALDO='D' AND LADO='CREDITO' THEN -CT2_VALOR WHEN NATUREZA_SALDO='C' AND LADO='CREDITO' THEN CT2_VALOR ELSE -CT2_VALOR END)) VALOR_CONTABIL
        FROM CONTABIL_BASE GROUP BY FILIAL,CONTA
    )
    SELECT RTRIM(COALESCE(F.FILIAL,T.FILIAL)) FILIAL,COALESCE(F.CONTA,T.CONTA) CONTA,
        C.DESCRICAO_CONTA,C.NATUREZA_SALDO,
        ISNULL(F.QUANTIDADE_REGISTROS,0) QUANTIDADE_REGISTROS_SFT,
        ISNULL(F.VALOR_FISCAL,0) VALOR_FISCAL,
        ISNULL(T.QUANTIDADE_LANCAMENTOS,0) QUANTIDADE_LANCAMENTOS_CT2,
        ISNULL(T.VALOR_CONTABIL,0) VALOR_CONTABIL,
        ISNULL(F.VALOR_FISCAL,0)-ISNULL(T.VALOR_CONTABIL,0) DIFERENCA,
        CASE WHEN ABS(ISNULL(F.VALOR_FISCAL,0)-ISNULL(T.VALOR_CONTABIL,0))<=0.01 THEN 'CONCILIADO' ELSE 'DIVERGENTE' END SITUACAO
    FROM FISCAL F FULL OUTER JOIN CONTABIL T ON T.FILIAL=F.FILIAL AND T.CONTA COLLATE DATABASE_DEFAULT=F.CONTA COLLATE DATABASE_DEFAULT
    INNER JOIN CONTAS C ON C.CONTA COLLATE DATABASE_DEFAULT=COALESCE(F.CONTA,T.CONTA) COLLATE DATABASE_DEFAULT
    ORDER BY COALESCE(F.FILIAL,T.FILIAL),COALESCE(F.CONTA,T.CONTA);
END;
