/*=============================================================================
  Fonte.........: dbo.SP_HDS0000_RFIS02
  Objetivo......: Resultado 1 - impostos da SFT agrupados por filial,
                  movimento, imposto e conta contabil relacionada.
  Grupo..........: 20 - Grupo Agronelli
  Banco esperado: CCW2SA_171703_PR_PD
  Objeto.........: SFT200
  Validado em...: 2026-08-28, somente leitura, via MCP dbcode.
=============================================================================*/
CREATE OR ALTER PROCEDURE dbo.SP_HDS0000_RFIS02
    @DATA_INICIAL VARCHAR(10) = NULL,
    @DATA_FINAL VARCHAR(10) = NULL,
    @FILIAL VARCHAR(6) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @DI DATE, @DF DATE;

    SELECT @DATA_INICIAL = NULLIF(LTRIM(RTRIM(@DATA_INICIAL)), ''),
           @DATA_FINAL = NULLIF(LTRIM(RTRIM(@DATA_FINAL)), ''),
           @FILIAL = NULLIF(LTRIM(RTRIM(@FILIAL)), '');
    SELECT @DI = CASE WHEN @DATA_INICIAL IS NULL THEN DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)
        ELSE COALESCE(TRY_CONVERT(DATE,@DATA_INICIAL,112),TRY_CONVERT(DATE,@DATA_INICIAL,103),TRY_CONVERT(DATE,@DATA_INICIAL,23)) END;
    SELECT @DF = CASE WHEN @DATA_FINAL IS NULL THEN EOMONTH(GETDATE())
        ELSE COALESCE(TRY_CONVERT(DATE,@DATA_FINAL,112),TRY_CONVERT(DATE,@DATA_FINAL,103),TRY_CONVERT(DATE,@DATA_FINAL,23)) END;
    IF @DI IS NULL OR @DF IS NULL THROW 50001, 'Datas invalidas. Use AAAAMMDD, DD/MM/AAAA ou AAAA-MM-DD.', 1;
    IF @DI > @DF THROW 50001, 'DATA_INICIAL nao pode ser maior que DATA_FINAL.', 1;
    SELECT @DATA_INICIAL=CONVERT(VARCHAR(8),@DI,112), @DATA_FINAL=CONVERT(VARCHAR(8),@DF,112);

    SELECT RTRIM(S.FT_FILIAL) AS FILIAL, S.FT_TIPOMOV AS TIPO_MOVIMENTO,
        CASE S.FT_TIPOMOV WHEN 'E' THEN 'ENTRADA' WHEN 'S' THEN 'SAIDA' ELSE 'OUTRO' END AS MOVIMENTO,
        I.IMPOSTO, I.CAMPO_SFT, I.CONTA, I.DESCRICAO_CONTA,
        COUNT_BIG(*) AS QUANTIDADE_REGISTROS,
        SUM(CONVERT(DECIMAL(19,4),I.VALOR_IMPOSTO)) AS VALOR_FISCAL
    FROM dbo.SFT200 AS S
    CROSS APPLY (VALUES
        ('ICMS','FT_VALICM',CASE WHEN S.FT_TIPOMOV='E' THEN '101021001' ELSE '201010902' END,CASE WHEN S.FT_TIPOMOV='E' THEN 'ICMS A RECUPERAR' ELSE 'ICMS A RECOLHER' END,S.FT_VALICM),
        ('ICMS ST','FT_ICMSRET',CASE WHEN S.FT_TIPOMOV='E' THEN '101021006' ELSE '201010908' END,CASE WHEN S.FT_TIPOMOV='E' THEN 'ICMS ST A RECUPERAR' ELSE 'ICMS ST A RECOLHER' END,S.FT_ICMSRET),
        ('ICMS DIFAL','FT_ICMSDIF','201010911','ICMS DIF ALIQUOTA A RECOLHER',S.FT_ICMSDIF),
        ('IPI','FT_VALIPI',CASE WHEN S.FT_TIPOMOV='E' THEN '101021004' ELSE '201010913' END,CASE WHEN S.FT_TIPOMOV='E' THEN 'IPI A RECUPERAR' ELSE 'IPI A RECOLHER - CIRCULANTE' END,S.FT_VALIPI),
        ('PIS','FT_VALPIS',CASE WHEN S.FT_TIPOMOV='E' THEN '101021002' ELSE '201010914' END,CASE WHEN S.FT_TIPOMOV='E' THEN 'PIS NAO CUMULATIVO A RECUPERAR' ELSE 'PIS A RECOLHER - CIRCULANTE' END,S.FT_VALPIS),
        ('COFINS','FT_VALCOF',CASE WHEN S.FT_TIPOMOV='E' THEN '101021003' ELSE '201010915' END,CASE WHEN S.FT_TIPOMOV='E' THEN 'COFINS NAO CUMULATIVO A RECUPERAR' ELSE 'COFINS A RECOLHER - CIRCULANTE' END,S.FT_VALCOF),
        ('IRRF','FT_VALIRR','201010901','IRRF A RECOLHER',S.FT_VALIRR),
        ('INSS','FT_VALINS','201010903','RETENCOES P/ A SEGURIDADE SOCIAL',S.FT_VALINS),
        ('ISS RETIDO','FT_ISSSUB','201010905','ISSQN A RECOLHER',S.FT_ISSSUB),
        ('PIS RETIDO','FT_VRETPIS','201010906','RETENCOES PIS COFINS CSL - PCC',S.FT_VRETPIS),
        ('COFINS RETIDO','FT_VRETCOF','201010906','RETENCOES PIS COFINS CSL - PCC',S.FT_VRETCOF),
        ('CSLL RETIDA','FT_VRETCSL','201010906','RETENCOES PIS COFINS CSL - PCC',S.FT_VRETCSL)
    ) AS I(IMPOSTO,CAMPO_SFT,CONTA,DESCRICAO_CONTA,VALOR_IMPOSTO)
    WHERE S.D_E_L_E_T_='' AND S.FT_ENTRADA BETWEEN @DATA_INICIAL AND @DATA_FINAL
      AND I.VALOR_IMPOSTO<>0 AND (@FILIAL IS NULL OR S.FT_FILIAL=@FILIAL)
    GROUP BY S.FT_FILIAL,S.FT_TIPOMOV,I.IMPOSTO,I.CAMPO_SFT,I.CONTA,I.DESCRICAO_CONTA
    ORDER BY S.FT_FILIAL,S.FT_TIPOMOV,I.CONTA,I.IMPOSTO;
END;

-------------------- CAPTURA PROCEDURES 
--SELECT sm.definition
--FROM sys.sql_modules sm
--JOIN sys.objects o
--    ON sm.object_id = o.object_id
--WHERE o.name = 'SP_HDS0000_RFIS02';
--
--
-------------------- PERMISSAO PROCEDURE
GRANT EXECUTE ON dbo.SP_HDS0000_RFIS02
TO [CLT171703totvsread];
--