/*
 Objetivo: títulos a receber em aberto e identificação de cliente funcionário.
 Banco: CCW2SA_171703_PR_PD.
 Objetos validados: SE1, SC5, SA1, SA3 e SRA dos grupos 20, 23, 06, 08 e 50.
 Última validação: 2026-09-01.
*/
CREATE OR ALTER PROCEDURE dbo.SP_HDS3752_RCON02
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 'AGROINDUSTRIA' AS EMPRESA, SE1.E1_PREFIXO AS PREFIXO,
           SE1.E1_NUM AS NUMERO, SE1.E1_FILORIG AS SEGMENTO,
           SE1.E1_PARCELA AS PARCELA, SE1.E1_TIPO AS TIPO,
           SE1.E1_NATUREZ AS NATUREZA, SE1.E1_CLIENTE AS CLIENTE,
           SE1.E1_LOJA AS LOJA, CLI.A1_NOME AS RAZAO_SOCIAL,
           SE1.E1_NOMCLI AS NOME_CLIENTE, CLI.A1_MSBLQL AS BLOQUEIO,
           CONVERT(DATETIME, SE1.E1_EMISSAO, 103) AS EMISSAO,
           CONVERT(DATETIME, SE1.E1_VENCREA, 103) AS VENCIMENTO_REAL,
           CASE WHEN CONVERT(DATETIME, SE1.E1_AG_DTPR, 103) = CONVERT(DATETIME, '19000101', 112)
                THEN NULL ELSE CONVERT(DATETIME, SE1.E1_AG_DTPR, 103) END AS DATA_PRORROGACAO,
           SE1.E1_VALOR AS VALOR_TOTAL, SE1.E1_SALDO AS SALDO_A_RECEBER,
           SE1.E1_HIST AS HISTORICO, SE1.E1_SITUACA AS CARTEIRA,
           SE1.E1_PEDIDO AS PEDIDO, CLI.A1_DDD AS DDD,
           CLI.A1_TEL AS TELEFONE, CLI.A1_EMAIL AS EMAIL,
           REP.A3_NOME AS NOME_REPRESENTANTE, VEN.A3_NOME AS NOME_VENDEDOR,
           GER.A3_NOME AS NOME_GERENTE,
           CASE WHEN EXISTS (SELECT 1 FROM dbo.SRA200 AS SRA
                             WHERE SRA.RA_CIC = CLI.A1_CGC AND SRA.RA_CIC <> ''
                               AND SRA.D_E_L_E_T_ <> '*')
                THEN 'SIM' ELSE 'NAO' END AS FUNCIONARIO
    FROM dbo.SE1200 AS SE1
    INNER JOIN dbo.SA1200 AS CLI ON CLI.A1_COD = SE1.E1_CLIENTE AND CLI.A1_LOJA = SE1.E1_LOJA AND CLI.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SC5200 AS PED ON PED.C5_FILIAL = SE1.E1_FILORIG AND PED.C5_NUM = SE1.E1_PEDIDO AND PED.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3200 AS REP ON REP.A3_FILIAL = PED.C5_FILIAL AND REP.A3_COD = PED.C5_VEND1 AND REP.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3200 AS VEN ON VEN.A3_FILIAL = PED.C5_FILIAL AND VEN.A3_COD = PED.C5_VEND2 AND VEN.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3200 AS GER ON GER.A3_FILIAL = PED.C5_FILIAL AND GER.A3_COD = VEN.A3_GEREN AND GER.D_E_L_E_T_ <> '*'
    WHERE SE1.E1_SALDO <> 0 AND SE1.D_E_L_E_T_ <> '*'

    UNION ALL

    SELECT 'MTP EIRELI', SE1.E1_PREFIXO, SE1.E1_NUM, SE1.E1_FILORIG,
           SE1.E1_PARCELA, SE1.E1_TIPO, SE1.E1_NATUREZ, SE1.E1_CLIENTE,
           SE1.E1_LOJA, CLI.A1_NOME, SE1.E1_NOMCLI, CLI.A1_MSBLQL,
           CONVERT(DATETIME, SE1.E1_EMISSAO, 103), CONVERT(DATETIME, SE1.E1_VENCREA, 103),
           CASE WHEN CONVERT(DATETIME, SE1.E1_AG_DTPR, 103) = CONVERT(DATETIME, '19000101', 112)
                THEN NULL ELSE CONVERT(DATETIME, SE1.E1_AG_DTPR, 103) END,
           SE1.E1_VALOR, SE1.E1_SALDO, SE1.E1_HIST, SE1.E1_SITUACA,
           SE1.E1_PEDIDO, CLI.A1_DDD, CLI.A1_TEL, CLI.A1_EMAIL,
           REP.A3_NOME, VEN.A3_NOME, GER.A3_NOME,
           CASE WHEN EXISTS (SELECT 1 FROM dbo.SRA230 AS SRA WHERE SRA.RA_CIC = CLI.A1_CGC AND SRA.RA_CIC <> '' AND SRA.D_E_L_E_T_ <> '*')
                THEN 'SIM' ELSE 'NAO' END
    FROM dbo.SE1230 AS SE1
    INNER JOIN dbo.SA1230 AS CLI ON CLI.A1_COD = SE1.E1_CLIENTE AND CLI.A1_LOJA = SE1.E1_LOJA AND CLI.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SC5230 AS PED ON PED.C5_FILIAL = SE1.E1_FILORIG AND PED.C5_NUM = SE1.E1_PEDIDO AND PED.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3230 AS REP ON REP.A3_FILIAL = PED.C5_FILIAL AND REP.A3_COD = PED.C5_VEND1 AND REP.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3230 AS VEN ON VEN.A3_FILIAL = PED.C5_FILIAL AND VEN.A3_COD = PED.C5_VEND2 AND VEN.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3230 AS GER ON GER.A3_FILIAL = PED.C5_FILIAL AND GER.A3_COD = VEN.A3_GEREN AND GER.D_E_L_E_T_ <> '*'
    WHERE SE1.E1_SALDO <> 0 AND SE1.D_E_L_E_T_ <> '*'

    UNION ALL

    SELECT 'IADES', SE1.E1_PREFIXO, SE1.E1_NUM, SE1.E1_FILORIG,
           SE1.E1_PARCELA, SE1.E1_TIPO, SE1.E1_NATUREZ, SE1.E1_CLIENTE,
           SE1.E1_LOJA, CLI.A1_NOME, SE1.E1_NOMCLI, CLI.A1_MSBLQL,
           CONVERT(DATETIME, SE1.E1_EMISSAO, 103), CONVERT(DATETIME, SE1.E1_VENCREA, 103),
           CAST(NULL AS DATETIME), SE1.E1_VALOR, SE1.E1_SALDO, SE1.E1_HIST,
           SE1.E1_SITUACA, SE1.E1_PEDIDO, CLI.A1_DDD, CLI.A1_TEL, CLI.A1_EMAIL,
           REP.A3_NOME, VEN.A3_NOME, GER.A3_NOME,
           CASE WHEN EXISTS (SELECT 1 FROM dbo.SRA060 AS SRA WHERE SRA.RA_CIC = CLI.A1_CGC AND SRA.RA_CIC <> '' AND SRA.D_E_L_E_T_ <> '*')
                THEN 'SIM' ELSE 'NAO' END
    FROM dbo.SE1060 AS SE1
    INNER JOIN dbo.SA1060 AS CLI ON CLI.A1_COD = SE1.E1_CLIENTE AND CLI.A1_LOJA = SE1.E1_LOJA AND CLI.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SC5060 AS PED ON PED.C5_FILIAL = SE1.E1_FILORIG AND PED.C5_NUM = SE1.E1_PEDIDO AND PED.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3060 AS REP ON REP.A3_FILIAL = PED.C5_FILIAL AND REP.A3_COD = PED.C5_VEND1 AND REP.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3060 AS VEN ON VEN.A3_FILIAL = PED.C5_FILIAL AND VEN.A3_COD = PED.C5_VEND2 AND VEN.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3060 AS GER ON GER.A3_FILIAL = PED.C5_FILIAL AND GER.A3_COD = VEN.A3_GEREN AND GER.D_E_L_E_T_ <> '*'
    WHERE SE1.E1_SALDO <> 0 AND SE1.D_E_L_E_T_ <> '*'

    UNION ALL

    SELECT 'NELLTECH', SE1.E1_PREFIXO, SE1.E1_NUM, SE1.E1_FILORIG,
           SE1.E1_PARCELA, SE1.E1_TIPO, SE1.E1_NATUREZ, SE1.E1_CLIENTE,
           SE1.E1_LOJA, CLI.A1_NOME, SE1.E1_NOMCLI, CLI.A1_MSBLQL,
           CONVERT(DATETIME, SE1.E1_EMISSAO, 103), CONVERT(DATETIME, SE1.E1_VENCREA, 103),
           CAST(NULL AS DATETIME), SE1.E1_VALOR, SE1.E1_SALDO, SE1.E1_HIST,
           SE1.E1_SITUACA, SE1.E1_PEDIDO, CLI.A1_DDD, CLI.A1_TEL, CLI.A1_EMAIL,
           REP.A3_NOME, VEN.A3_NOME, GER.A3_NOME,
           CASE WHEN EXISTS (SELECT 1 FROM dbo.SRA080 AS SRA WHERE SRA.RA_CIC = CLI.A1_CGC AND SRA.RA_CIC <> '' AND SRA.D_E_L_E_T_ <> '*')
                THEN 'SIM' ELSE 'NAO' END
    FROM dbo.SE1080 AS SE1
    INNER JOIN dbo.SA1080 AS CLI ON CLI.A1_COD = SE1.E1_CLIENTE AND CLI.A1_LOJA = SE1.E1_LOJA AND CLI.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SC5080 AS PED ON PED.C5_FILIAL = SE1.E1_FILORIG AND PED.C5_NUM = SE1.E1_PEDIDO AND PED.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3080 AS REP ON REP.A3_FILIAL = PED.C5_FILIAL AND REP.A3_COD = PED.C5_VEND1 AND REP.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3080 AS VEN ON VEN.A3_FILIAL = PED.C5_FILIAL AND VEN.A3_COD = PED.C5_VEND2 AND VEN.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3080 AS GER ON GER.A3_FILIAL = PED.C5_FILIAL AND GER.A3_COD = VEN.A3_GEREN AND GER.D_E_L_E_T_ <> '*'
    WHERE SE1.E1_SALDO <> 0 AND SE1.D_E_L_E_T_ <> '*'

    UNION ALL

    SELECT 'QUINTAS', SE1.E1_PREFIXO, SE1.E1_NUM, SE1.E1_FILORIG,
           SE1.E1_PARCELA, SE1.E1_TIPO, SE1.E1_NATUREZ, SE1.E1_CLIENTE,
           SE1.E1_LOJA, CLI.A1_NOME, SE1.E1_NOMCLI, CLI.A1_MSBLQL,
           CONVERT(DATETIME, SE1.E1_EMISSAO, 103), CONVERT(DATETIME, SE1.E1_VENCREA, 103),
           CASE WHEN CONVERT(DATETIME, SE1.E1_AG_DTPR, 103) = CONVERT(DATETIME, '19000101', 112)
                THEN NULL ELSE CONVERT(DATETIME, SE1.E1_AG_DTPR, 103) END,
           SE1.E1_VALOR, SE1.E1_SALDO, SE1.E1_HIST, SE1.E1_SITUACA,
           SE1.E1_PEDIDO, CLI.A1_DDD, CLI.A1_TEL, CLI.A1_EMAIL,
           REP.A3_NOME, VEN.A3_NOME, GER.A3_NOME,
           CASE WHEN EXISTS (SELECT 1 FROM dbo.SRA500 AS SRA WHERE SRA.RA_CIC = CLI.A1_CGC AND SRA.RA_CIC <> '' AND SRA.D_E_L_E_T_ <> '*')
                THEN 'SIM' ELSE 'NAO' END
    FROM dbo.SE1500 AS SE1
    INNER JOIN dbo.SA1500 AS CLI ON CLI.A1_COD = SE1.E1_CLIENTE AND CLI.A1_LOJA = SE1.E1_LOJA AND CLI.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SC5500 AS PED ON PED.C5_FILIAL = SE1.E1_FILORIG AND PED.C5_NUM = SE1.E1_PEDIDO AND PED.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3500 AS REP ON REP.A3_FILIAL = PED.C5_FILIAL AND REP.A3_COD = PED.C5_VEND1 AND REP.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3500 AS VEN ON VEN.A3_FILIAL = PED.C5_FILIAL AND VEN.A3_COD = PED.C5_VEND2 AND VEN.D_E_L_E_T_ <> '*'
    LEFT JOIN dbo.SA3500 AS GER ON GER.A3_FILIAL = PED.C5_FILIAL AND GER.A3_COD = VEN.A3_GEREN AND GER.D_E_L_E_T_ <> '*'
    WHERE SE1.E1_SALDO <> 0 AND SE1.D_E_L_E_T_ <> '*';
END;
