/*=============================================================================
  Fonte.........: dbo.SP_HDS0000_RFIS03
  Objetivo......: Resultado 2 - CT2 tributaria agrupada por filial, conta,
                  LP, rotina e lado contabil.
  Grupo..........: 20 - Grupo Agronelli
  Banco esperado: CCW2SA_171703_PR_PD
  Objeto.........: CT2200
  Validado em...: 2026-08-28, somente leitura, via MCP dbcode.
=============================================================================*/
CREATE OR ALTER PROCEDURE dbo.SP_HDS0000_RFIS03
    @DATA_INICIAL VARCHAR(10)=NULL, @DATA_FINAL VARCHAR(10)=NULL, @FILIAL VARCHAR(6)=NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @DI DATE, @DF DATE;
    SELECT @DATA_INICIAL=NULLIF(LTRIM(RTRIM(@DATA_INICIAL)),''), @DATA_FINAL=NULLIF(LTRIM(RTRIM(@DATA_FINAL)),''), @FILIAL=NULLIF(LTRIM(RTRIM(@FILIAL)),'');
    SELECT @DI=CASE WHEN @DATA_INICIAL IS NULL THEN DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1) ELSE COALESCE(TRY_CONVERT(DATE,@DATA_INICIAL,112),TRY_CONVERT(DATE,@DATA_INICIAL,103),TRY_CONVERT(DATE,@DATA_INICIAL,23)) END;
    SELECT @DF=CASE WHEN @DATA_FINAL IS NULL THEN EOMONTH(GETDATE()) ELSE COALESCE(TRY_CONVERT(DATE,@DATA_FINAL,112),TRY_CONVERT(DATE,@DATA_FINAL,103),TRY_CONVERT(DATE,@DATA_FINAL,23)) END;
    IF @DI IS NULL OR @DF IS NULL THROW 50001,'Datas invalidas. Use AAAAMMDD, DD/MM/AAAA ou AAAA-MM-DD.',1;
    IF @DI>@DF THROW 50001,'DATA_INICIAL nao pode ser maior que DATA_FINAL.',1;
    SELECT @DATA_INICIAL=CONVERT(VARCHAR(8),@DI,112),@DATA_FINAL=CONVERT(VARCHAR(8),@DF,112);

    ;WITH CONTAS AS
    (
        SELECT * FROM (VALUES
          ('201010901','IRRF A RECOLHER','C'),('201010902','ICMS A RECOLHER','C'),('201010903','RETENCOES P/ A SEGURIDADE SOCIAL','C'),
          ('201010905','ISSQN A RECOLHER','C'),('201010906','RETENCOES PIS COFINS CSL - PCC','C'),('201010908','ICMS ST A RECOLHER','C'),
          ('201010911','ICMS DIF ALIQUOTA A RECOLHER','C'),('201010913','IPI A RECOLHER - CIRCULANTE','C'),('201010914','PIS A RECOLHER - CIRCULANTE','C'),
          ('201010915','COFINS A RECOLHER - CIRCULANTE','C'),('101021001','ICMS A RECUPERAR','D'),('101021002','PIS NAO CUMULATIVO A RECUPERAR','D'),
          ('101021003','COFINS NAO CUMULATIVO A RECUPERAR','D'),('101021004','IPI A RECUPERAR','D'),('101021006','ICMS ST A RECUPERAR','D'),('101021105','ISS A RECUPERAR','D')
        ) X(CONTA,DESCRICAO_CONTA,NATUREZA_SALDO)
    )
    SELECT RTRIM(T.CT2_FILIAL) FILIAL,M.CONTA,C.DESCRICAO_CONTA,RTRIM(T.CT2_LP) LP,RTRIM(T.CT2_ROTINA) ROTINA,M.LADO,
        CASE WHEN RTRIM(T.CT2_ROTINA) IN ('CTBANFE','CTBANFS','MATA103') THEN 'SIM' ELSE 'NAO' END EH_ROTINA_FISCAL,
        COUNT_BIG(*) QUANTIDADE_LANCAMENTOS,SUM(CONVERT(DECIMAL(19,4),T.CT2_VALOR)) VALOR_MOVIMENTO,
        SUM(CONVERT(DECIMAL(19,4),CASE WHEN C.NATUREZA_SALDO='D' AND M.LADO='DEBITO' THEN T.CT2_VALOR WHEN C.NATUREZA_SALDO='D' AND M.LADO='CREDITO' THEN -T.CT2_VALOR WHEN C.NATUREZA_SALDO='C' AND M.LADO='CREDITO' THEN T.CT2_VALOR ELSE -T.CT2_VALOR END)) VALOR_CONTABIL_NATUREZA
    FROM dbo.CT2200 T
    CROSS APPLY (VALUES(RTRIM(T.CT2_DEBITO),'DEBITO'),(RTRIM(T.CT2_CREDIT),'CREDITO')) M(CONTA,LADO)
    INNER JOIN CONTAS C ON C.CONTA COLLATE DATABASE_DEFAULT=M.CONTA COLLATE DATABASE_DEFAULT
    WHERE T.D_E_L_E_T_='' AND T.CT2_DATA BETWEEN @DATA_INICIAL AND @DATA_FINAL AND (@FILIAL IS NULL OR T.CT2_FILIAL=@FILIAL)
    GROUP BY T.CT2_FILIAL,M.CONTA,C.DESCRICAO_CONTA,C.NATUREZA_SALDO,T.CT2_LP,T.CT2_ROTINA,M.LADO
    ORDER BY T.CT2_FILIAL,M.CONTA,EH_ROTINA_FISCAL DESC,T.CT2_LP,T.CT2_ROTINA,M.LADO;
END;
