-- AUTOR : ENRICO AUGUSTO 
-- DATA   : 06/02/2020
-- QUERY : QUANTIDADE DE CLIENTES AGRUPADOS QUE TEVE VENDA 

//* TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT*//
/* PERDIDOS EMPRESAS 497___________________________________________________________________________*/
SELECT * FROM  (
	
	SELECT 'PERDIDOS' AS 'POSICAO' , count( DISTINCT( D2_CLIENTE+D2_LOJA ) ) AS CONTADOR  
	FROM SD2010 D2
	INNER JOIN SF4010 F4 ON F4_CODIGO = D2_TES AND F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  F4.D_E_L_E_T_ <> '*'	
	WHERE D2_EMISSAO BETWEEN '20191201' AND '20191231' 
	AND D2.D_E_L_E_T_ <> '*'
	AND D2_LOCAL = '01'
	AND LEN(D2_COD) = 4 	
	AND D2_CLIENTE+D2_LOJA NOT IN (SELECT DISTINCT( D2_CLIENTE+D2_LOJA ) FROM SD2010 
																INNER JOIN SF4010 F4 ON F4_CODIGO = D2_TES AND F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  F4.D_E_L_E_T_ <> '*'
																WHERE D2_EMISSAO BETWEEN '20200101' AND '20200131'
																AND D2.D_E_L_E_T_ <> '*'
															  ) -- PERDIDOS 188
							
	UNION 	   
						
	SELECT 'PERDIDOS' AS 'POSICAO', count( DISTINCT( D2_CLIENTE+D2_LOJA ) ) AS CONTADOR 
	FROM SD2020 D2
	INNER JOIN SF4020 F4 ON   F4.F4_CODIGO = D2.D2_TES AND F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  F4.D_E_L_E_T_ <> '*' 
	WHERE D2_EMISSAO BETWEEN '20191201' AND '20191231'
	AND D2.D_E_L_E_T_ <> '*'
	AND D2_LOCAL = '01'
	AND LEN(D2_COD) = 4  
	AND D2_CLIENTE+D2_LOJA NOT IN (SELECT DISTINCT( D2_CLIENTE+D2_LOJA ) 
																FROM SD2020 D2
																INNER JOIN SF4020 F4 ON F4.F4_CODIGO = D2.D2_TES AND F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  F4.D_E_L_E_T_ <> '*' 
																WHERE D2_EMISSAO BETWEEN '20200101' AND '20200131'
																AND D2.D_E_L_E_T_ <> '*'
																) -- PERDIDOS 243
										
	UNION 
	
	SELECT 'PERDIDOS' AS 'POSICAO', count( DISTINCT( D2_CLIENTE+D2_LOJA ) ) AS CONTADOR 
	FROM SD2050 D2
	INNER JOIN SF4050 F4 ON F4.F4_CODIGO = D2.D2_TES AND F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  F4.D_E_L_E_T_ <> '*' 
	WHERE D2_EMISSAO BETWEEN '20191201' AND '20191231'
	AND D2.D_E_L_E_T_ <> '*'
	AND D2_LOCAL = '01'
	AND LEN(D2_COD) = 4 
	
	AND D2_CLIENTE+D2_LOJA NOT IN (SELECT DISTINCT( D2_CLIENTE+D2_LOJA ) 
																FROM SD2050 D2
																INNER JOIN SF4050 F4 ON F4.F4_CODIGO = D2.D2_TES AND F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  F4.D_E_L_E_T_ <> '*' 
																WHERE D2_EMISSAO BETWEEN '20200101' AND '20200131'
																AND D2.D_E_L_E_T_ <> '*'
																) -- PERDIDOS 66
																						

	UNION
	
	//* TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT*// 
	/* RECUPERADOS EMPRESAS 641________________________________________________________________________*/

	
	SELECT 'RECUPERADOS' AS 'POSICAO' , COUNT (DISTINCT( D2_CLIENTE+D2_LOJA ) ) AS CONTADOR FROM SD2010 WHERE D2_EMISSAO BETWEEN '20200101' AND '20200131'
	AND D_E_L_E_T_ <> '*'
	AND D2_LOCAL = '01'
	AND LEN(D2_COD) = 4 
	AND D2_TES IN ( SELECT F4_CODIGO  FROM SF4010  WHERE F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  D_E_L_E_T_ <> '*' )
	AND D2_CLIENTE+D2_LOJA NOT IN ( SELECT DISTINCT( D2_CLIENTE+D2_LOJA ) FROM SD2010 WHERE D2_EMISSAO BETWEEN '20191201' AND '20191231'
																AND D_E_L_E_T_ <> '*'
																AND D2_TES IN ( SELECT F4_CODIGO  FROM SF4010  WHERE F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  D_E_L_E_T_ <> '*'  )
																)  -- 191 RECUPERADOS 															
	UNION
	
	SELECT 'RECUPERADOS' AS 'POSICAO' , COUNT (DISTINCT( D2_CLIENTE+D2_LOJA )) AS CONTADOR FROM SD2020 WHERE D2_EMISSAO BETWEEN '20200101' AND '20200131'
	AND D_E_L_E_T_ <> '*'
	AND D2_LOCAL = '01'
	AND LEN(D2_COD) = 4 
	AND D2_TES IN ( SELECT F4_CODIGO  FROM SF4020  WHERE F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  D_E_L_E_T_ <> '*' )
	AND D2_CLIENTE+D2_LOJA NOT IN ( SELECT DISTINCT( D2_CLIENTE+D2_LOJA ) FROM SD2020 WHERE D2_EMISSAO BETWEEN '20191201' AND '20191231'
																AND D_E_L_E_T_ <> '*'
																AND D2_TES IN ( SELECT F4_CODIGO  FROM SF4020  WHERE F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  D_E_L_E_T_ <> '*'  )
																)  -- 357  RECUPERADOS
	UNION
	
	SELECT 'RECUPERADOS' AS 'POSICAO' , COUNT (DISTINCT( D2_CLIENTE+D2_LOJA )) AS CONTADOR  FROM SD2050 WHERE D2_EMISSAO BETWEEN '20200101' AND '20200131'
	AND D_E_L_E_T_ <> '*'
	AND D2_LOCAL = '01'
	AND LEN(D2_COD) = 4 
	AND D2_TES IN ( SELECT F4_CODIGO  FROM SF4050  WHERE F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  D_E_L_E_T_ <> '*' )
	AND D2_CLIENTE+D2_LOJA NOT IN ( SELECT DISTINCT( D2_CLIENTE+D2_LOJA ) FROM SD2050 WHERE D2_EMISSAO BETWEEN '20191201' AND '20191231'
																AND D_E_L_E_T_ <> '*'
																AND D2_TES IN ( SELECT F4_CODIGO  FROM SF4050  WHERE F4_DUPLIC = 'S' AND F4_ESTOQUE = 'S' AND  D_E_L_E_T_ <> '*'  )
																)  -- 93  RECUPERADOS 
														
//* YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY*//



