
--///////////////////////////////////////////////////////////////
/* QUERY PARA ATENDER A FISCALIZACAO DO DP*/
--///////////////////////////////////////////////////////////////

SELECT RA_NOME AS 'NOME', RA_PIS AS 'PIS', RJ_DESC AS 'FUNCAO', FORMAT(CAST(RA_ADMISSA AS date),'dd/MM/yyyy') AS 'ADMISSAO' FROM SRA030 
INNER JOIN SRJ010 ON RA_CODFUNC = RJ_FUNCAO
WHERE RA_DEMISSA = ''
AND RA_CIC NOT IN ('61189871653','00456284672')
AND RJ_FUNCAO NOT IN ('410','5142','000000001')
ORDER BY RA_NOME



SELECT RA_NOME AS 'NOME', RA_PIS AS 'PIS', RJ_DESC AS 'FUNCAO', FORMAT(CAST(RA_ADMISSA AS date),'dd/MM/yyyy') AS 'ADMISSAO' FROM SRA010 
INNER JOIN SRJ010 ON RA_CODFUNC = RJ_FUNCAO
WHERE RA_DEMISSA = ''
AND RA_CIC NOT IN ('61189871653','00456284672')
AND RA_FILIAL = '06'
AND RJ_FUNCAO NOT IN ('410','5142','000000001')
ORDER BY RA_NOME
--///////////////////////////////////////////////////////////////
