/*TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT*/
/*AUTOR: ENRICO AUGUSTO 																														*/
/*DATA  : 13/02/2020 																																 */
/*QUERY : TRAZ TODOS OS FUNCIONARIOS DEMITIDOS EM UMA DATA DECLARADA 								   */
/*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*/

//INFORME A DATA INICIO E DATA FIM
DECLARE @DTINI VARCHAR(8)
DECLARE @DTFIM VARCHAR(8)
SET @DTINI = '20190101'
SET @DTFIM = '20191231'

//EXECUTA A QUERY 
SELECT '01 DISTRIBUIDORA' AS 'EMP' ,RA_FILIAL,RA_MAT, RA_NOME , FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS 'DEMISSAO' FROM SRA010 WHERE RA_DEMISSA BETWEEN @DTINI AND @DTFIM
UNION
SELECT '02 DERIVADOS' AS 'EMP' ,RA_FILIAL,RA_MAT, RA_NOME, FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS 'DEMISSAO' FROM SRA020 WHERE RA_DEMISSA BETWEEN @DTINI AND @DTFIM
UNION
SELECT '03 LOGISTICA' AS 'EMP' ,RA_FILIAL,RA_MAT, RA_NOME, FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS 'DEMISSAO' FROM SRA030 WHERE RA_DEMISSA BETWEEN @DTINI AND @DTFIM
UNION
SELECT '04 FUNDACAO' AS 'EMP' ,RA_FILIAL,RA_MAT, RA_NOME, FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS 'DEMISSAO' FROM SRA040 WHERE RA_DEMISSA BETWEEN @DTINI AND @DTFIM
UNION
SELECT '05 TRRGO' AS 'EMP' ,RA_FILIAL,RA_MAT, RA_NOME, FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS 'DEMISSAO' FROM SRA050 WHERE RA_DEMISSA BETWEEN @DTINI AND @DTFIM

