DECLARE @DATAIN DATE
SET @DATAIN = '20211026'
DECLARE @DATAFIM DATE
SET @DATAFIM = '20211026'
SELECT EMP,	MES,E1_PORTADO ,SUM(E1_VALOR) AS VALOR FROM
	( SELECT 'DIST' EMP,E1_FILIAL , MONTH(E1_EMISSAO) MES, E1_PORTADO, E1_VALOR FROM SE1010 WHERE E1_EMISSAO BETWEEN @DATAIN AND @DATAFIM and D_E_L_E_T_ <> '*' AND E1_PORTADO <> ''
		UNION ALL	
		SELECT 'DERV' EMP,E1_FILIAL , MONTH(E1_EMISSAO) MES, E1_PORTADO, E1_VALOR  FROM SE1020 WHERE E1_EMISSAO BETWEEN @DATAIN AND @DATAFIM and D_E_L_E_T_ <> '*' AND E1_PORTADO <> '' 
		UNION ALL
		SELECT 'TRRG' EMP,E1_FILIAL , MONTH(E1_EMISSAO) MES, E1_PORTADO, E1_VALOR  FROM SE1050 WHERE E1_EMISSAO BETWEEN @DATAIN AND @DATAFIM and D_E_L_E_T_ <> '*' AND E1_PORTADO <> '' 
	) TABELA1 
	GROUP BY EMP,MES,E1_PORTADO
	ORDER BY EMP DESC