-- #######################################################################
-- ## - RELAÇÃO DE NOTAS EMITIDAS POR MOTORISTA							##
-- ## - 09/05/2019 - ENRICO AUGUSTO                                     ##
-- #######################################################################

SELECT 'DISTRIBUIDORA' AS EMPRESA,F2_FILIAL,F2_DOC,A1_NOME AS 'CLIENTE' , A1_EST AS 'UF ENTREGA', A1_MUN AS 'MUNICIPIO ENTREGA', '' AS 'ORIGEM CARGA',FORMAT(CAST(F2_EMISSAO AS date),'dd/MM/yyyy') AS EMISSAO, 
		F2_HORA , F2_VOLUME1, F2_MOTORIS, F2_CHVNFE, F2_TPFRETE, F2_PLACA1, B1_DESC
--SELECT 	F2_DOC,	F2_SERIE  
FROM SF2010
INNER JOIN SD2010 ON D2_DOC = F2_DOC AND D2_SERIE = F2_SERIE AND F2_FILIAL = D2_FILIAL
INNER JOIN SC5010 ON C5_NOTA = F2_DOC AND C5_SERIE = F2_SERIE AND C5_FILIAL = F2_FILIAL
INNER JOIN SA1010 ON A1_COD = F2_CLIENTE AND A1_LOJA = F2_LOJA 
INNER JOIN SF4010 ON F4_CODIGO = D2_TES
INNER JOIN SB1010 ON B1_COD = D2_COD
WHERE F2_MOTORIS IN  ('00554832674')
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
--AND A1_COD NOT IN ('001773')
--AND F2_FILIAL = '01'
AND F2_PLACA1 NOT IN ('AAA000')

AND SF2010.D_E_L_E_T_ <> '*'
AND SF4010.D_E_L_E_T_ <> '*'
AND SA1010.D_E_L_E_T_ <> '*'
AND SD2010.D_E_L_E_T_ <> '*'
AND SC5010.D_E_L_E_T_ <> '*'
--//////////////////

--ORDER BY EMISSAO

UNION 

SELECT 'DERIVADOS' AS EMPRESA,F2_FILIAL,F2_DOC,A1_NOME AS 'CLIENTE', 
		A1_EST AS 'UF ENTREGA', A1_MUN AS 'MUNICIPIO ENTREGA',
										   CASE C5_C_ORIGE
												WHEN '1' THEN 'PATOS DE MINAS'   
												WHEN '2' THEN 'UBERABA'
												WHEN '3' THEN 'UBERLÂNDIA'	
												WHEN '4' THEN 'BETIM'
												WHEN '5' THEN 'RIBEIRÁO PRETO'																																																									
											END AS 'ORIGEM CARGA',
		FORMAT(CAST(F2_EMISSAO AS date),'dd/MM/yyyy') AS EMISSAO, 
		F2_HORA , F2_VOLUME1, F2_MOTORIS, F2_CHVNFE, F2_TPFRETE, 
		F2_PLACA1, B1_DESC

--SELECT 	F2_DOC,	F2_SERIE  		  
FROM SF2020
INNER JOIN SD2020 ON D2_DOC = F2_DOC AND D2_SERIE = F2_SERIE AND F2_FILIAL = D2_FILIAL
INNER JOIN SC5020 ON C5_NOTA = F2_DOC AND C5_SERIE = F2_SERIE AND C5_FILIAL = F2_FILIAL
INNER JOIN SA1010 ON A1_COD = F2_CLIENTE AND A1_LOJA = F2_LOJA 
INNER JOIN SF4020 ON F4_CODIGO = D2_TES
INNER JOIN SB1010 ON B1_COD = D2_COD
WHERE  F2_MOTORIS IN  ('00554832674')
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
--AND A1_COD NOT IN ('001773')
AND F2_PLACA1 NOT IN ('AAA000')
--AND F2_DOC NOT IN ('000068836','000068837'--
AND SF2020.D_E_L_E_T_ <> '*'
AND SF4020.D_E_L_E_T_ <> '*'
AND SA1010.D_E_L_E_T_ <> '*'
AND SD2020.D_E_L_E_T_ <> '*'
AND SC5020.D_E_L_E_T_ <> '*'
--//////////////////


--ORDER BY 1
UNION 

SELECT 'TRR GOIAS' AS EMPRESA,F2_FILIAL,F2_DOC,A1_NOME AS 'CLIENTE' , A1_EST AS 'UF ENTREGA', A1_MUN AS 'MUNICIPIO ENTREGA',C5_ORIGEM AS 'ORIGEM CARGA',FORMAT(CAST(F2_EMISSAO AS date),'dd/MM/yyyy') AS EMISSAO, 
		F2_HORA , F2_VOLUME1, F2_MOTORIS, F2_CHVNFE, F2_TPFRETE, F2_PLACA1, B1_DESC
--SELECT 	F2_DOC,	F2_SERIE  		  
FROM SF2050
INNER JOIN SD2050 ON D2_DOC = F2_DOC AND D2_SERIE = F2_SERIE AND F2_FILIAL = D2_FILIAL
INNER JOIN SC5050 ON C5_NOTA = F2_DOC AND C5_SERIE = F2_SERIE AND C5_FILIAL = F2_FILIAL
INNER JOIN SA1010 ON A1_COD = F2_CLIENTE AND A1_LOJA = F2_LOJA 
INNER JOIN SF4050 ON F4_CODIGO = D2_TES
INNER JOIN SB1010 ON B1_COD = D2_COD
WHERE F2_MOTORIS IN  ('00554832674')
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
--AND A1_COD NOT IN ('001773')
AND F2_PLACA1 NOT IN ('AAA000')
AND SF2050.D_E_L_E_T_ <> '*'
AND SF4050.D_E_L_E_T_ <> '*'
AND SA1010.D_E_L_E_T_ <> '*'
AND SD2050.D_E_L_E_T_ <> '*'
AND SC5050.D_E_L_E_T_ <> '*'

--//////////////////

--ORDER BY 1,2,11,8,9



SELECT 'DIST' AS 'EMP',RA_CIC, FORMAT(CAST(RA_ADMISSA AS date),'dd/MM/yyyy') AS ADMISSAO , FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS DEMISSAO  FROM SRA010 
WHERE RA_CIC IN ('00554832674')
UNION
SELECT 'TRR' AS 'EMP',RA_CIC, FORMAT(CAST(RA_ADMISSA AS date),'dd/MM/yyyy') AS ADMISSAO , FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS DEMISSAO  FROM SRA020 
WHERE RA_CIC IN ('00554832674')
UNION
SELECT 'LOG' AS 'EMP',RA_CIC, FORMAT(CAST(RA_ADMISSA AS date),'dd/MM/yyyy') AS ADMISSAO , FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS DEMISSAO  FROM SRA030 
WHERE RA_CIC IN ('00554832674')
UNION 
SELECT 'TRRGO' AS 'EMP',RA_CIC, FORMAT(CAST(RA_ADMISSA AS date),'dd/MM/yyyy') AS ADMISSAO , FORMAT(CAST(RA_DEMISSA AS date),'dd/MM/yyyy') AS DEMISSAO  FROM SRA050 
WHERE RA_CIC IN ('00554832674')

ORDER BY 2,3
 --CIC - 01417946660 - ADSON TEIXEIRA DOS SANTOS     */


 ---------------------------------------

 SELECT E1_NUM,E1_SERIE
  FROM SE1050 WHERE E1_CLIENTE = '007894'
 AND E1_BAIXA = '' 
 AND D_E_L_E_T_ <> '*'
 AND E1_TIPO = 'NF'
 AND E1_FILIAL = '01'
 ORDER BY E1_FILIAL

  