/* 
 * AUTOR   : ENRICO AUGUSTO
 * DATA    : 23/03/2022
 * QUERY   : RELATORIO DE ROTAS / QUANTIDADE PARA IBAMA (ANUAL)
 * FILTROS : DATA / TRANSPORTADORA / 
*/ 


--/////////////////////////////////////////////////////////////////////////////////
SELECT  ANO,NOME,SUM(QUANTIDADE)AS 'QUANTIDADE',[TIPO DE TRANSPORTE],[TIPO DE ARMAZENAMENTO],[PLANO DE EMERGENCIA],TIPO,ORIGEM,DESTINO
FROM (
		--//***************************//
		SELECT '2021' AS 'ANO', 
		 CASE 
		  	WHEN B1.B1_X_CT IN ('D10','DA0','DIA','DIE','OUT','BIO') THEN 'OLEO DIESEL'
		  	WHEN B1.B1_X_CT IN ('GAS') THEN 'GASOLINA'
			WHEN B1.B1_X_CT IN ('HID','ANI') THEN 'ALCOOL'
			ELSE B1.B1_X_CT
		 END AS 'NOME',
		 SUM(C5.C5_VOLUME1) AS 'QUANTIDADE' , 
		 'RODOVIÁRIO' AS 'TIPO DE TRANSPORTE',
		 'TANQUES' AS 'TIPO DE ARMAZENAMENTO',
		 'SIM' AS 'PLANO DE EMERGENCIA',
		 'F' AS TIPO,
		 (TRIM(C5.C5_XMUNORI)+' - '+C5.C5_XUFORIG) AS 'ORIGEM', 
		 (TRIM(C5.C5_XMUNENT) +' - ' + C5.C5_XUFENTR  ) AS 'DESTINO'
		FROM SC6020 C6
		INNER JOIN SC5020 C5 ON C5.C5_FILIAL <> '' AND C5.C5_FILIAL = C6.C6_FILIAL AND C5.C5_NUM = C6.C6_NUM 
							AND C5.C5_CLIENTE  = C6.C6_CLI AND C5.C5_LOJACLI = C6.C6_LOJA AND C5.D_E_L_E_T_ = ''
							AND C5.C5_EMISSAO  BETWEEN '20210101' AND  '20211231' AND C5.C5_NOTA <> ''
							AND C5.C5_TRANSP = '000325'
		INNER JOIN SB1010 B1 ON B1.B1_COD = C6.C6_PRODUTO AND B1.D_E_L_E_T_ = ''
		WHERE 
			    C6.C6_FILIAL <> ''
			AND C6.D_E_L_E_T_  = '' 
			AND C6.C6_PRODUTO  BETWEEN '0101' AND '0303'
		GROUP BY C5.C5_FILIAL,(TRIM(C5.C5_XMUNENT) +' - ' + C5.C5_XUFENTR  ),B1.B1_X_CT,(TRIM(C5.C5_XMUNORI)+' - '+C5.C5_XUFORIG)
		--//***************************//
		UNION
		--//***************************//
		SELECT 
			'2021' AS 'ANO', 
			 CASE 
			  	WHEN B1.B1_X_CT IN ('D10','DA0','DIA','DIE','OUT','BIO') THEN 'OLEO DIESEL'
			  	WHEN B1.B1_X_CT IN ('GAS') THEN 'GASOLINA'
				WHEN B1.B1_X_CT IN ('HID','ANI') THEN 'ALCOOL'
				ELSE B1.B1_X_CT
			 END AS 'NOME',
			SUM(D1_QUANT) AS 'QUANTIDADE', 	 
		    'RODOVIÁRIO' AS 'TIPO DE TRANSPORTE',
			'TANQUES' AS 'TIPO DE ARMAZENAMENTO',
			'SIM' AS 'PLANO DE EMERGENCIA',
			'C' AS TIPO,
			(TRIM(A2.A2_MUN) + ' - ' + A2.A2_EST) AS 'ORIGEM',
			/*CASE	 --//// DISTRIBUIDORA 
				WHEN D1.D1_FILIAL = '01' THEN 'UBERABA - MG'
				WHEN D1.D1_FILIAL = '02' THEN 'UBERLANDIA - MG'
				WHEN D1.D1_FILIAL = '03' THEN 'SENADOR CANEDO - GO'
				WHEN D1.D1_FILIAL = '04' THEN 'BETIM - MG'
				WHEN D1.D1_FILIAL = '05' THEN 'PAULINIA - SP'
				WHEN D1.D1_FILIAL = '06' THEN 'RIBEIRÃO PRETO - SP'
				WHEN D1.D1_FILIAL = '07' THEN 'CUIABA - MT'
			END AS 'DESTINO'
			*/
			CASE	-- //// DERIVADOS
				WHEN D1.D1_FILIAL = '01' THEN 'UBERABA - MG'
				WHEN D1.D1_FILIAL = '02' THEN 'PATOS DE MINAS - MG'
				WHEN D1.D1_FILIAL = '03' THEN 'RIBEIRÃO PRETO - SP'
				WHEN D1.D1_FILIAL = '04' THEN 'SENADOR CANEDO - GO'
				WHEN D1.D1_FILIAL = '05' THEN 'PARACATU - MG'
				WHEN D1.D1_FILIAL = '06' THEN 'MONTIVIDIU - GO'
			END AS 'DESTINO'			
		FROM ZF4020 F4
		JOIN SD1020 D1 ON D1.D1_FILIAL <> '' AND  D1_FILIAL = ZF4_FILIAL AND D1_SERIE = ZF4_SERIE AND D1_DOC = ZF4_NF 
					   AND D1.D1_EMISSAO = ZF4_EMISSA AND D1.D_E_L_E_T_ = ' '
		JOIN SA2010 A2 ON A2.A2_FILIAL = '' AND  A2.A2_COD = D1.D1_FORNECE AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_ = ''			
		JOIN SB1010 B1 ON B1.B1_FILIAL = '' AND B1.B1_COD = D1.D1_COD  AND B1.D_E_L_E_T_ = ''
		WHERE ZF4_FILIAL > ' ' AND ZF4_FATCOM = 'C' AND ZF4_TRANSP = '07123253000100' 
			  AND ZF4_EMISSA  BETWEEN '20210101' AND '20211231' AND F4.D_E_L_E_T_ = ' '
		GROUP BY B1.B1_X_CT,D1.D1_FILIAL,(TRIM(A2.A2_MUN) + ' - ' + A2.A2_EST)
		--//***************************//
) AS TABELA1 
GROUP BY ANO,NOME,[TIPO DE TRANSPORTE],[TIPO DE ARMAZENAMENTO],[PLANO DE EMERGENCIA],TIPO,ORIGEM,DESTINO
ORDER BY ORIGEM , DESTINO 
--/////////////////////////////////////////////////////////////////////////////////
