SELECT 'RIO BRANCO DISTRIBUIDORA ' AS 'EMPRESA', RA_FILIAL, RJ_DESC, RA_SALARIO , COUNT(RA_SALARIO) AS 'QUANTIDADE'
FROM SRA010
INNER JOIN SRJ010 ON RJ_FUNCAO = RA_CODFUNC
WHERE RA_DEMISSA = '' 
AND RA_SALARIO <> 0 
AND RA_CODFUNC <> '5142'
GROUP BY RA_FILIAL,RA_CODFUNC, RJ_DESC, RA_SALARIO 

UNION 

SELECT 'RIO BRANCO DERIVADOS' AS 'EMPRESA', RA_FILIAL, RJ_DESC, RA_SALARIO , COUNT(RA_SALARIO) AS 'QUANTIDADE'
FROM SRA020
INNER JOIN SRJ010 ON RJ_FUNCAO = RA_CODFUNC
WHERE RA_DEMISSA = '' 
AND RA_SALARIO <> 0 
AND RA_CODFUNC <> '5142'
GROUP BY RA_FILIAL,RA_CODFUNC, RJ_DESC, RA_SALARIO 

UNION 

SELECT 'RIO BRANCO TRR GOIAS ' AS 'EMPRESA', RA_FILIAL, RJ_DESC, RA_SALARIO , COUNT(RA_SALARIO) AS 'QUANTIDADE'
FROM SRA050
INNER JOIN SRJ010 ON RJ_FUNCAO = RA_CODFUNC
WHERE RA_DEMISSA = '' 
AND RA_SALARIO <> 0 
AND RA_CODFUNC <> '5142'
GROUP BY RA_FILIAL,RA_CODFUNC, RJ_DESC, RA_SALARIO 



