
--================================================ 
-- LUANA (CONTROLE DE HORAS)
--================================================ 

/*------------------------------------------------------------------------------------------------------------------------------------------------------------------------
AUTOR: ENRICO CARDOSO	
DATA : 09/07/2025
DESCRICAO: CONFERENCIA GPE - BANCO DE HORAS)	
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SP_GPE_HORAS '01/01/2025', '31/01/2025' 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP PROCEDURE SP_GPE_HORAS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
ALTER PROCEDURE [dbo].[SP_GPE_HORAS]
(	@MV_PAR01 VARCHAR(10),
	@MV_PAR02 VARCHAR(10))
AS

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT @MV_PAR01=SUBSTRING(@MV_PAR01,7,4)+SUBSTRING(@MV_PAR01,4,2)+SUBSTRING(@MV_PAR01,1,2)
SELECT @MV_PAR02=SUBSTRING(@MV_PAR02,7,4)+SUBSTRING(@MV_PAR02,4,2)+SUBSTRING(@MV_PAR02,1,2)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET NOCOUNT ON 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--DECLARE @MV_PAR01 VARCHAR(8)
--DECLARE @MV_PAR02 VARCHAR(8)
--SET @MV_PAR01='20250901'
--SET @MV_PAR02='20250931'
	SELECT 
		MAT, 
		NOME, 
		CARGO, 
		DESC_CARGO, 
		FORMAT(CONVERT(date, ADMISSAO), 'dd/MM/yyyy') AS ADMISSAO,
		DEPARTAMENTO,
		TURNO,
ISNULL(CAST(FLOOR([HORAS TRABALHADAS] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HORAS TRABALHADAS],
ISNULL(CAST(FLOOR([HORAS NAO TRABALHADA] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HORAS NAO TRABALHADA],
ISNULL(CAST(FLOOR([SAIDA ANTEC.  BH] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [SAIDA ANTEC.  BH],
ISNULL(CAST(FLOOR([SAIDA ANTECIPADA] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [SAIDA ANTECIPADA],
ISNULL(CAST(FLOOR([D.S.R.] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [D.S.R.],
ISNULL(CAST(FLOOR([HE BH 70%-DIA NORMAL] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HE BH 70%-DIA NORMAL],
ISNULL(CAST(FLOOR([HE 70% - DIA NORMAL] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HE 70% - DIA NORMAL],
ISNULL(CAST(FLOOR([HE 100% - DIA COMPEN] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HE 100% - DIA COMPEN],
ISNULL(CAST(FLOOR([FERIAS] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [FERIAS],
ISNULL(CAST(FLOOR([FALTA INTEGRAL] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [FALTA INTEGRAL],
ISNULL(CAST(FLOOR([FALTA  INTEGRAL-BH] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [FALTA  INTEGRAL-BH],
ISNULL(CAST(FLOOR([ADIC HE AUT NOTURNA] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [ADIC HE AUT NOTURNA],
ISNULL(CAST(FLOOR([HE 70% - DIA NOR NOT] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HE 70% - DIA NOR NOT],
ISNULL(CAST(FLOOR([HORA NOTURNA SUMPLEM] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HORA NOTURNA SUMPLEM],
ISNULL(CAST(FLOOR([HORA TRAB. NOTURNAS] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HORA TRAB. NOTURNAS],
ISNULL(CAST(FLOOR([ADICIONAL NOTURNO] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [ADICIONAL NOTURNO],
ISNULL(CAST(FLOOR([HE 100% -DIA FER NOT] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HE 100% -DIA FER NOT],
ISNULL(CAST(FLOOR([HE 100% - DIA FERIAD] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HE 100% - DIA FERIAD],
ISNULL(CAST(FLOOR([HE BH 70%-D NOR NOT] * 100) / 100.0 AS DECIMAL(10,2)), 0) AS [HE BH 70%-D NOR NOT] 	
--		ISNULL(FORMAT(CAST([HORAS TRABALHADAS]     AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HORAS TRABALHADAS],
--		ISNULL(FORMAT(CAST([HORAS NAO TRABALHADA]  AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HORAS NAO TRABALHADA],
--		ISNULL(FORMAT(CAST([SAIDA ANTEC.  BH]      AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [SAIDA ANTEC.  BH],
--		ISNULL(FORMAT(CAST([SAIDA ANTECIPADA]      AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [SAIDA ANTECIPADA],
--		ISNULL(FORMAT(CAST([D.S.R.]                AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [D.S.R.],
--		ISNULL(FORMAT(CAST([HE BH 70%-DIA NORMAL]  AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HE BH 70%-DIA NORMAL],
--		ISNULL(FORMAT(CAST([HE 70% - DIA NORMAL]   AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HE 70% - DIA NORMAL],
--		ISNULL(FORMAT(CAST([HE 100% - DIA COMPEN]  AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HE 100% - DIA COMPEN],
--		ISNULL(FORMAT(CAST([FERIAS]                AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [FERIAS],
--		ISNULL(FORMAT(CAST([FALTA INTEGRAL]        AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [FALTA INTEGRAL],
--		ISNULL(FORMAT(CAST([FALTA  INTEGRAL-BH]    AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [FALTA  INTEGRAL-BH],
--		ISNULL(FORMAT(CAST([ADIC HE AUT NOTURNA]   AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [ADIC HE AUT NOTURNA],
--		ISNULL(FORMAT(CAST([HE 70% - DIA NOR NOT]  AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HE 70% - DIA NOR NOT],
--		ISNULL(FORMAT(CAST([HORA NOTURNA SUMPLEM]  AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HORA NOTURNA SUMPLEM],
--		ISNULL(FORMAT(CAST([HORA TRAB. NOTURNAS]   AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HORA TRAB. NOTURNAS],
--		ISNULL(FORMAT(CAST([ADICIONAL NOTURNO]     AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [ADICIONAL NOTURNO],
--		ISNULL(FORMAT(CAST([HE 100% -DIA FER NOT]  AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HE 100% -DIA FER NOT],
--		ISNULL(FORMAT(CAST([HE 100% - DIA FERIAD]  AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HE 100% - DIA FERIAD],
--		ISNULL(FORMAT(CAST([HE BH 70%-D NOR NOT]   AS DECIMAL(10,2)), 'N2', 'pt-BR') , 0) AS [HE BH 70%-D NOR NOT]
	FROM (
		SELECT 
			MAT, 
			NOME, 
			CARGO, 
			DESC_CARGO, 
			ADMISSAO,
			DEPARTAMENTO,
			TURNO,
			DESCR,
			HORAS
		FROM (
			SELECT PC_MAT AS MAT , RA.RA_NOME  AS NOME , RA.RA_CODFUNC AS CARGO, RJ.RJ_DESC AS DESC_CARGO , QB.QB_DESCRIC AS DEPARTAMENTO, TRIM(R6.R6_TURNO)+' - '+TRIM(R6.R6_DESC) AS TURNO ,RA.RA_ADMISSA  AS ADMISSAO , 
				'SPC' AS TABELA, PC_DATA AS 'DATA',  PC_QUANTC  AS HORAS, PC_PD AS PD, P9_CLASEV AS CLASSE  , P9.P9_DESC AS DESCR 
			FROM SPC010 PC 
			INNER JOIN SRA010 RA ON RA.RA_MAT = PC.PC_MAT  
			INNER JOIN SP9010 P9 ON P9.P9_CODIGO = PC.PC_PD  
			INNER JOIN SRJ010 RJ ON RJ.RJ_FUNCAO = RA_CODFUNC  
			LEFT JOIN SR6010 R6 ON R6.R6_TURNO = RA.RA_TNOTRAB AND R6.D_E_L_E_T_ = '' 
			INNER JOIN SQB010 QB  ON QB.QB_DEPTO = RA.RA_DEPTO        
			WHERE PC_DATA BETWEEN @MV_PAR01 AND @MV_PAR02  
				AND PC.D_E_L_E_T_ = ''  
			UNION  
			SELECT PI.PI_MAT AS MAT, RA.RA_NOME  AS NOME , RA.RA_CODFUNC AS CARGO, RJ.RJ_DESC AS DESC_CARGO ,QB.QB_DESCRIC AS DEPARTAMENTO,  TRIM(R6.R6_TURNO)+' - '+TRIM(R6.R6_DESC) AS TURNO , RA.RA_ADMISSA  AS ADMISSAO , 
				'SPI' AS TABELA, PI.PI_DATA AS 'DATA',  PI.PI_QUANT AS HORAS, PI.PI_PD AS PD, P9_CLASEV AS CLASSE  , P9.P9_DESC AS DESCR 
			FROM SPI010 PI 
			INNER JOIN SRA010 RA ON RA.RA_MAT = PI.PI_MAT 
			INNER JOIN SP9010 P9 ON P9.P9_CODIGO = PI.PI_PD 
			INNER JOIN SRJ010 RJ ON RJ.RJ_FUNCAO = RA_CODFUNC 
			LEFT JOIN SR6010 R6 ON R6.R6_TURNO = RA.RA_TNOTRAB AND R6.D_E_L_E_T_ = ''
			INNER JOIN SQB010 QB  ON QB.QB_DEPTO = RA.RA_DEPTO        
			WHERE PI.PI_DATA BETWEEN @MV_PAR01 AND @MV_PAR02
				AND PI.D_E_L_E_T_ = ''  
			UNION
			SELECT PH_MAT AS MAT , RA.RA_NOME  AS NOME , RA.RA_CODFUNC AS CARGO, RJ.RJ_DESC AS DESC_CARGO , QB.QB_DESCRIC AS DEPARTAMENTO, TRIM(R6.R6_TURNO)+' - '+TRIM(R6.R6_DESC) AS TURNO ,RA.RA_ADMISSA  AS ADMISSAO , 
				'SPH' AS TABELA, PH_DATA AS 'DATA',  PH_QUANTC  AS HORAS, PH_PD AS PD, P9_CLASEV AS CLASSE  , P9.P9_DESC AS DESCR 
			FROM SPH010 PH 
			INNER JOIN SRA010 RA ON RA.RA_MAT = PH.PH_MAT  
			INNER JOIN SP9010 P9 ON P9.P9_CODIGO = PH.PH_PD  
			INNER JOIN SRJ010 RJ ON RJ.RJ_FUNCAO = RA_CODFUNC  
			LEFT JOIN SR6010 R6 ON R6.R6_TURNO = RA.RA_TNOTRAB AND R6.D_E_L_E_T_ = '' 
			INNER JOIN SQB010 QB  ON QB.QB_DEPTO = RA.RA_DEPTO        
			WHERE PH_DATA BETWEEN @MV_PAR01 AND @MV_PAR02  
				AND PH.D_E_L_E_T_ = ''		
--			UNION  
--			SELECT RD.RD_MAT AS MAT , RA.RA_NOME  AS NOME , RA.RA_CODFUNC AS CARGO, RJ.RJ_DESC AS DESC_CARGO ,QB.QB_DESCRIC AS DEPARTAMENTO , TRIM(R6.R6_TURNO)+' - '+TRIM(R6.R6_DESC) AS TURNO ,RA.RA_ADMISSA  AS ADMISSAO , 
--				'SRD' AS TABELA,  RD.RD_DTREF AS 'DATA',  RD.RD_HORAS AS HORAS, RD.RD_PD AS PD, 'RD' AS CLASSE  , RV.RV_DESC AS DESCR 
--			FROM SRD010 RD 
--			INNER JOIN SRA010 RA ON RA.RA_MAT = RD.RD_MAT 
--			INNER JOIN SRV010 RV ON RV.RV_COD = RD.RD_PD AND RD_PD IN ('130','60') 
--			INNER JOIN SRJ010 RJ ON RJ.RJ_FUNCAO = RA_CODFUNC
--			LEFT JOIN SR6010 R6 ON R6.R6_TURNO = RA.RA_TNOTRAB AND R6.D_E_L_E_T_ = ''
--			INNER JOIN SQB010 QB  ON QB.QB_DEPTO = RA.RA_DEPTO
--			WHERE RD.RD_DATARQ BETWEEN SUBSTRING(@MV_PAR01,1,4) AND SUBSTRING(@MV_PAR02,1,4) 
--				AND RD.D_E_L_E_T_ = '' 
		) AS TAB01
	) AS SRC
	PIVOT (
		SUM(HORAS)
		FOR DESCR IN (
			[HORAS NAO TRABALHADA],
			[SAIDA ANTEC.  BH],
			[HORAS TRABALHADAS],
			[D.S.R.],
			[HE BH 70%-DIA NORMAL],
			[HE 70% - DIA NORMAL],
			[HE 100% - DIA COMPEN],
			[SAIDA ANTECIPADA],
			[FERIAS],
			[FALTA INTEGRAL],
			[FALTA  INTEGRAL-BH],
			[ADIC HE AUT NOTURNA],
			[HE 70% - DIA NOR NOT],
			[HORA NOTURNA SUMPLEM],
			[HORA TRAB. NOTURNAS],
			[ADICIONAL NOTURNO],
			[HE 100% -DIA FER NOT],
			[HE 100% - DIA FERIAD],
			[HE BH 70%-D NOR NOT]
		)
	) AS PVT

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET NOCOUNT OFF
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
