/*
OBJETIVO: Validar PRECO_ATUAL e ULTIMO_PRECO da SP_HDS3418_RCOM04.
BANCO ESPERADO: CCW2SA_171703_PR_PD
OBJETO VALIDADO: SC7200
ULTIMA VALIDACAO: 28/08/2026
RESULTADO ESPERADO:
  1. A aplicacao do pedido anterior nao altera a quantidade de itens atuais.
  2. PRECO_ATUAL corresponde ao C7_PRECO do item atual.
  3. ULTIMO_PRECO corresponde ao C7_PRECO do pedido anterior do produto.
*/

DECLARE @MV_PAR01 VARCHAR(8) = '20260101';
DECLARE @MV_PAR02 VARCHAR(8) = '20261231';

;WITH PEDIDOS_ATUAIS AS
(
    SELECT
        C7.C7_FILIAL,
        C7.C7_NUM,
        C7.C7_ITEM,
        C7.C7_PRODUTO,
        C7.C7_EMISSAO,
        C7.C7_PRECO AS PRECO_ATUAL,
        C7.R_E_C_N_O_ AS RECNO
    FROM SC7200 C7
    WHERE C7.D_E_L_E_T_ = ''
      AND C7.C7_EMISSAO BETWEEN @MV_PAR01 AND @MV_PAR02
),
PRECOS AS
(
    SELECT
        ATUAL.C7_FILIAL,
        ATUAL.C7_NUM,
        ATUAL.C7_ITEM,
        ATUAL.C7_PRODUTO,
        ATUAL.PRECO_ATUAL,
        COALESCE(ULTIMO_PC.ULTIMO_PRECO, ATUAL.PRECO_ATUAL) AS ULTIMO_PRECO
    FROM PEDIDOS_ATUAIS ATUAL
    OUTER APPLY
    (
        SELECT TOP (1)
            ANTERIOR.C7_PRECO AS ULTIMO_PRECO
        FROM SC7200 ANTERIOR
        WHERE ANTERIOR.D_E_L_E_T_ = ''
          AND ANTERIOR.C7_FILIAL = ATUAL.C7_FILIAL
          AND ANTERIOR.C7_PRODUTO = ATUAL.C7_PRODUTO
          AND ANTERIOR.C7_NUM <> ATUAL.C7_NUM
          AND
              (
                  ANTERIOR.C7_EMISSAO < ATUAL.C7_EMISSAO
                  OR
                  (
                      ANTERIOR.C7_EMISSAO = ATUAL.C7_EMISSAO
                      AND ANTERIOR.R_E_C_N_O_ < ATUAL.RECNO
                  )
              )
        ORDER BY
            ANTERIOR.C7_EMISSAO DESC,
            ANTERIOR.R_E_C_N_O_ DESC
    ) ULTIMO_PC
)
SELECT TOP (100)
    (SELECT COUNT(*) FROM PEDIDOS_ATUAIS) AS ITENS_ATUAIS,
    (SELECT COUNT(*) FROM PRECOS) AS ITENS_APOS_APLICACAO,
    (SELECT COUNT(DISTINCT C7_FILIAL + '|' + C7_NUM + '|' + C7_ITEM) FROM PRECOS) AS ITENS_DISTINTOS,
    (SELECT COUNT(*) FROM PRECOS WHERE ULTIMO_PRECO IS NULL) AS ULTIMOS_PRECOS_NULOS,
    P.C7_FILIAL,
    P.C7_NUM,
    P.C7_ITEM,
    P.C7_PRODUTO,
    P.ULTIMO_PRECO,
    P.PRECO_ATUAL
FROM PRECOS P
ORDER BY P.C7_NUM DESC, P.C7_ITEM;
