/*------------------------------------------------------------------------------------------------------------------------------------------------------------------------
AUTOR: ROBERTO RECIFE
DATA : 17/07/2023
DESCRICAO: CONFERENCIA FERTMINAS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SP_CONFERENCIA_FERTMINAS '20240601','20240630',2
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP PROCEDURE SP_CONFERENCIA_FERTMINAS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
CREATE PROCEDURE SP_CONFERENCIA_FERTMINAS
(	@MV_PAR01		VARCHAR(08),	--Periodo de?
	@MV_PAR02		VARCHAR(08),	--Periodo Ate?
	@MV_PAR03		FLOAT)			--1-Entradas  2-Saidas
AS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET NOCOUNT ON 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IF @MV_PAR03=1 BEGIN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	FT_FILIAL FILIAL,
		F1_TIPO TIPONF,
		F1_DOC DOCUMENTO,
		F1_SERIE SERIE,
		FT_NFORI NF_ORIGEM,
		FT_CHVNFE 'CHAVE ELETRONICA',
		FT_CLIEFOR FORNECEDOR,
		FT_LOJA LOJA,
		'RAZAO SOCIAL'=CASE WHEN F1_TIPO IN ('B','D') THEN (SELECT TOP 1 A1_NOME FROM SA1010 WHERE A1_FILIAL='' AND A1_COD=FT_CLIEFOR AND A1_LOJA=FT_LOJA) ELSE (SELECT TOP 1 A2_NOME FROM SA2010 WHERE A2_FILIAL='' AND A2_COD=FT_CLIEFOR AND A2_LOJA=FT_LOJA) END,
		'CNPJ'=CASE WHEN F1_TIPO IN ('B','D') THEN (SELECT TOP 1 A1_CGC FROM SA1010 WHERE A1_FILIAL='' AND A1_COD=FT_CLIEFOR AND A1_LOJA=FT_LOJA) ELSE (SELECT TOP 1 A2_CGC FROM SA2010 WHERE A2_FILIAL='' AND A2_COD=FT_CLIEFOR AND A2_LOJA=FT_LOJA) END,
		'INSCRICAO ESTADUAL'=CASE WHEN F1_TIPO IN ('B','D') THEN (SELECT TOP 1 A1_INSCR FROM SA1010 WHERE A1_FILIAL='' AND A1_COD=FT_CLIEFOR AND A1_LOJA=FT_LOJA) ELSE (SELECT TOP 1 A2_INSCR FROM SA2010 WHERE A2_FILIAL='' AND A2_COD=FT_CLIEFOR AND A2_LOJA=FT_LOJA) END,
		'INSCRICAO MUNICIPAL'=CASE WHEN F1_TIPO IN ('B','D') THEN (SELECT TOP 1 A1_INSCRM FROM SA1010 WHERE A1_FILIAL='' AND A1_COD=FT_CLIEFOR AND A1_LOJA=FT_LOJA) ELSE (SELECT TOP 1 A2_INSCMU FROM SA2010 WHERE A2_FILIAL='' AND A2_COD=FT_CLIEFOR AND A2_LOJA=FT_LOJA) END,
		'ESTADO'=CASE WHEN F1_TIPO IN ('B','D') THEN (SELECT TOP 1 A1_EST FROM SA1010 WHERE A1_FILIAL='' AND A1_COD=FT_CLIEFOR AND A1_LOJA=FT_LOJA) ELSE (SELECT TOP 1 A2_EST FROM SA2010 WHERE A2_FILIAL='' AND A2_COD=FT_CLIEFOR AND A2_LOJA=FT_LOJA) END,
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF1.F1_EMISSAO),103) 'DATA EMISSAO',
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF1.F1_DTDIGIT),103) 'DATA DIGITACAO',
		SFT.FT_ITEM 'ITEM',
		SFT.FT_PRODUTO 'PRODUTO',
		SB1.B1_DESC 'DESCRICAO',
		SB1.B1_POSIPI 'NCM',
		SB1.B1_TIPO 'TIPO',
		'SITTRIB'=(SELECT F4_SITTRIB FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		SB1.B1_LOCPAD AS 'ALMOX',
		SFT.FT_TES 'TES',
		SFT.FT_CFOP 'CFOP',
		'FINALIDADE'=(SELECT F4_TEXTO FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		B1_UM 'UM',
		FT_QUANT AS 'QUANTIDADE',
		FT_PRCUNIT AS 'VL UNIT',
		FT_QUANT*FT_PRCUNIT AS 'VL TOTAL',
		FT_VALCONT AS 'VL CONTABIL',
		FT_BASEICM AS 'BASE ICMS/ISS',
		FT_ALIQICM AS 'ALIQ.ICMS/ISS',
		FT_VALICM AS 'VL ICMS/ISS',
		FT_ISENICM AS 'VL ISENTO ICMS',
		FT_OUTRICM AS 'VL OUTROS ICMS',
		FT_BASEIPI AS 'BASE IPI',
		FT_ALIQIPI AS 'ALIQ.IPI',
		FT_VALIPI AS 'VL IPI',
		FT_ISENIPI AS 'VL ISENTO IPI',
		FT_OUTRIPI AS 'VL OUTROS IPI',
		FT_CTIPI AS 'COD TRIB.IPI',
		FT_BASERET AS 'BASE ICMS ST',
		FT_ICMSRET AS 'AL ICMS ST',
		FT_ALIQSOL AS 'ALIQ.ICMS ST',
		FT_OBSERV AS 'OBSERVACAO',
		FT_TIPO AS 'FT TIPO',
		F1_ESPECIE AS 'ESPECIE',
		FT_ICMSCOM AS 'ICMS COM',
		FT_ICMSDIF AS 'ICMS DIF',
		FT_IPIOBS AS 'IPI OBS',
		FT_OBSICM AS 'OBS ICMS',
		FT_OBSSOL AS 'OBS ST',
		D1_ITEMPC AS 'ITEM PC',
		'NUM SC'=ISNULL((SELECT TOP 1 C7_NUMSC FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND D1_ITEMPC=C7_ITEM AND D_E_L_E_T_<>'*'),''),
		'ITEM SC'=ISNULL((SELECT TOP 1 C7_ITEMSC FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND D1_ITEMPC=C7_ITEM AND D_E_L_E_T_<>'*'),''),
		D1_PEDIDO AS 'PEDIDO COMPRA',
		'VENCIMENTO'='',
		'OBSERVACAO PEDIDO'=ISNULL((SELECT C7_OBS FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND C7_ITEM=D1_ITEMPC AND D_E_L_E_T_<>'*'),''),
		'OBSERVACAO PEDIDO2'=ISNULL((SELECT C7_OBSM FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND C7_ITEM=D1_ITEMPC AND D_E_L_E_T_<>'*'),''),
		D1_CONTA AS 'C.ORCAMENTARIA',
		'DESCRICAO C.ORCAMENTARIA'=ISNULL((SELECT CT1_DESC01 FROM CT1010 WHERE CT1_FILIAL='' AND CT1_CONTA=D1_CONTA AND D_E_L_E_T_<>'*'),''),
		D1_CC AS 'CC',
		'DESCRICAO CC'=ISNULL((SELECT CTT_DESC01 FROM CTT010 WHERE CTT_FILIAL='' AND CTT_CUSTO=D1_CC AND D_E_L_E_T_<>'*'),''),
		'TIPO MOV'=CASE WHEN F1_TIPO<>'D' THEN 'ENTRADA' ELSE 'SAIDA' END,
		FT_FRETE AS 'VALOR FRETE',
		FT_SEGURO AS 'VALOR SEGURO',
		FT_DESPESA AS 'VALOR DESPESA',
		FT_DESCONT AS 'VALOR DESCONTO',
		FT_BASEPIS AS 'BASE PIS',
		FT_ALIQPIS AS 'ALIQ.PIS',
		FT_VALPIS AS 'VLR PIS',
		FT_BASECOF AS 'BASE COF',
		FT_ALIQCOF AS 'ALIQ.COF',
		FT_VALCOF AS 'VLR COF',
		FT_CSTPIS AS 'CST PIS',
		FT_CSTCOF AS 'CST COF',
		'MOV.ESTOQUE'=(SELECT F4_ESTOQUE FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'GERA FINANCEIRO'=(SELECT F4_DUPLIC FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'AT.ATIVO'=(SELECT F4_ATUATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'LIVRO CIAP'=(SELECT F4_CIAP FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		F1_TPFRETE AS 'TIPO FRETE',
		FT_BASEIRR as 'BASE IRRF',
		FT_ALIQIRR AS 'ALIQ IRRF',
		FT_VALIRR AS 'VLR IRRF', 
		FT_VALCONT AS 'BASE PIS/COF',
		FT_ARETPIS AS 'ALIQ RET PIS',             
		FT_VRETPIS AS 'VLR RET PIS',    
		FT_ARETCOF AS 'ALQ RET COF',
		FT_VRETCOF AS 'VLR RET COF',
		FT_ALIQINS AS 'ALQ INSS',            
		FT_VALINS AS 'VLR INSS',
		FT_VRETCSL AS 'VLR RET CSLL',
		'HISTORICO'=ISNULL((SELECT TOP 1 E2_HIST FROM SE2010 WHERE E2_FILIAL=FT_FILIAL AND E2_EMISSAO=FT_EMISSAO AND E2_NUM=FT_NFISCAL AND E2_PREFIXO=FT_SERIE AND E2_FORNECE=FT_CLIEFOR AND D_E_L_E_T_<>'*'),''),
		'MANIFESTADO'=ISNULL((SELECT TOP 1 CASE WHEN C00_CODEVE='3' THEN 'SIM' ELSE '' END FROM C00010 WHERE C00_FILIAL=FT_FILIAL AND C00_NUMNFE=FT_NFISCAL AND C00_SERNFE=FT_SERIE AND SUBSTRING(C00_DTEMI,1,6)=SUBSTRING(FT_EMISSAO,1,6) AND D_E_L_E_T_<>'*'),''),
		'NF FRETE'=ISNULL((SELECT TOP 1 RTRIM(LTRIM(F8_NFDIFRE))+'/'+F8_SERORIG FROM SF8010 WHERE F8_FILIAL=FT_FILIAL AND F8_NFORIG=FT_NFISCAL AND F8_SERORIG=FT_SERIE AND F1_TIPO='N' AND D_E_L_E_T_<>'*'),''),
		'VLR FRETE'=ISNULL((SELECT TOP 1 F1_VALBRUT FROM SF1010 WHERE F1_FILIAL+F1_DOC+F1_SERIE IN (SELECT TOP 1 F8_FILIAL+F8_NFDIFRE+F8_SERORIG FROM SF8010 WHERE F8_FILIAL=F1_FILIAL AND F8_NFORIG=FT_NFISCAL AND F8_SERORIG=FT_SERIE AND D_E_L_E_T_<>'*') AND F1_TIPO='C' AND D_E_L_E_T_<>'*'),0),
		'ICMS NA NF'=F1_VALICM,
		'DESMEM.IT.ATF'=CASE WHEN (SELECT F4_BENSATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*')='1' THEN 'SIM' ELSE 'NAO' END,
		'' 'ESPECIE NA NF',
		0 'QTD.VOLUME'
		INTO #PRINCIPAL
		
FROM	SFT010 SFT,
		SF1010 SF1,
		SB1010 SB1,
		SD1010 SD1

WHERE	FT_TIPOMOV='E' 
		AND SF1.F1_DOC=SFT.FT_NFISCAL
		AND SF1.F1_DTDIGIT BETWEEN @MV_PAR01 AND @MV_PAR02
		AND SF1.F1_FILIAL=SFT.FT_FILIAL
		AND SF1.F1_FORNECE=SFT.FT_CLIEFOR
		AND SF1.F1_EMISSAO=SFT.FT_EMISSAO
		AND SFT.FT_PRODUTO=SB1.B1_COD
		AND SFT.FT_PRODUTO=SD1.D1_COD
		AND SF1.F1_FILIAL=SD1.D1_FILIAL
		AND SFT.FT_NFISCAL=SD1.D1_DOC
		AND SFT.FT_SERIE=SD1.D1_SERIE
		AND SFT.FT_ITEM=SD1.D1_ITEM
		AND SD1.D1_FORNECE=SF1.F1_FORNECE
		AND SB1.B1_FILIAL=''
		AND SD1.D_E_L_E_T_<>'*'
		AND SFT.D_E_L_E_T_<>'*' 
		AND SB1.D_E_L_E_T_<>'*'
		AND SF1.D_E_L_E_T_<>'*' 

ORDER BY F1_DTDIGIT,F1_DOC,F1_SERIE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- DOCUMENTOS SEM MOVIMENTO FISCAL
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO #PRINCIPAL
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	F1_FILIAL FILIAL,
		F1_TIPO TIPONF,
		F1_DOC DOCUMENTO,
		F1_SERIE SERIE,
		D1_NFORI NF_ORIGEM,
		F1_CHVNFE 'CHAVE ELETRONICA',
		F1_FORNECE FORNECEDOR,
		F1_LOJA LOJA,
		A2_NOME 'RAZAO SOCIAL',
		SA2.A2_CGC 'CNPJ',
		SA2.A2_INSCR 'INSCRICAO ESTADUAL',
		SA2.A2_INSCMU 'INSCRICAO MUNICIPAL',
		SA2.A2_EST 'ESTADO',
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF1.F1_EMISSAO),103) 'DATA EMISSAO',
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF1.F1_DTDIGIT),103) 'DATA DIGITACAO',
		SD1.D1_ITEM 'ITEM',
		SD1.D1_COD 'PRODUTO',
		SB1.B1_DESC 'DESCRICAO',
		SB1.B1_POSIPI 'NCM',
		SB1.B1_TIPO 'TIPO',
		'SITTRIB'=(SELECT F4_SITTRIB FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=D1_TES AND D_E_L_E_T_<>'*'),
		SB1.B1_LOCPAD AS 'ALMOX',
		SD1.D1_TES 'TES',
		SD1.D1_CF 'CFOP',
		'FINALIDADE'=(SELECT F4_TEXTO FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=D1_TES AND D_E_L_E_T_<>'*'),
		B1_UM 'UM',
		D1_QUANT AS 'QUANTIDADE',
		D1_VUNIT AS 'VL UNIT',
		D1_QUANT*D1_VUNIT AS 'VL TOTAL',
		0 AS 'VL CONTABIL',
		0 AS 'BASE ICMS',
		0 AS 'ALIQ.ICMS',
		0 AS 'VL ICMS',
		0 AS 'VL ISENTO ICMS',
		0 AS 'VL OUTROS ICMS',
		0 AS 'BASE IPI',
		0 AS 'ALIQ.IPI',
		0 AS 'VL IPI',
		0 AS 'VL ISENTO IPI',
		0 AS 'VL OUTROS IPI',
		0 AS 'COD TRIB.IPI',
		0 AS 'BASE ICMS ST',
		0 AS 'AL ICMS ST',
		0 AS 'ALIQ.ICMS ST',
		0 AS 'OBSERVACAO',
		0 AS 'FT TIPO',
		F1_ESPECIE AS 'ESPECIE',
		0 AS 'ICMS COM',
		0 AS 'ICMS DIF',
		0 AS 'IPI OBS',
		0 AS 'OBS ICMS',
		0 AS 'OBS ST',
		D1_ITEMPC AS 'ITEM PC',
		'NUM SC'=ISNULL((SELECT TOP 1 C7_NUMSC FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND D1_ITEMPC=C7_ITEM AND D_E_L_E_T_<>'*'),''),
		'ITEM SC'=ISNULL((SELECT TOP 1 C7_ITEMSC FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND D1_ITEMPC=C7_ITEM AND D_E_L_E_T_<>'*'),''),
		D1_PEDIDO AS 'PEDIDO COMPRA',
		'VENCIMENTO'='',
		'OBSERVACAO PEDIDO'=ISNULL((SELECT C7_OBS FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND C7_ITEM=D1_ITEMPC AND D_E_L_E_T_<>'*'),''),
		'OBSERVACAO PEDIDO2'=ISNULL((SELECT C7_OBSM FROM SC7010 WHERE C7_FILIAL=D1_FILIAL AND C7_NUM=D1_PEDIDO AND C7_ITEM=D1_ITEMPC AND D_E_L_E_T_<>'*'),''),
		D1_CONTA AS 'C.ORCAMENTARIA',
		'DESCRICAO C.ORCAMENTARIA'=ISNULL((SELECT CT1_DESC01 FROM CT1010 WHERE CT1_FILIAL='' AND CT1_CONTA=D1_CONTA AND D_E_L_E_T_<>'*'),''),
		D1_CC AS 'CC',
		'DESCRICAO CC'=ISNULL((SELECT CTT_DESC01 FROM CTT010 WHERE CTT_FILIAL='' AND CTT_CUSTO=D1_CC AND D_E_L_E_T_<>'*'),''),
		'TIPO MOV'=CASE WHEN F1_TIPO<>'D' THEN 'ENTRADA' ELSE 'SAIDA' END,
		0 AS 'VALOR FRETE',
		0 AS 'VALOR SEGURO',
		0 AS 'VALOR DESPESA',
		0 AS 'VALOR DESCONTO',
		0 AS 'BASE PIS',
		0 AS 'ALIQ.PIS',
		0 AS 'VLR PIS',
		0 AS 'BASE COF',
		0 AS 'ALIQ.COF',
		0 AS 'VLR COF',
		0 AS 'CST PIS',
		0 AS 'CST COF',
		'MOV.ESTOQUE'=(SELECT F4_ESTOQUE FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=D1_TES AND D_E_L_E_T_<>'*'),
		'GERA FINANCEIRO'=(SELECT F4_DUPLIC FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=D1_TES AND D_E_L_E_T_<>'*'),
		'AT.ATIVO'=(SELECT F4_ATUATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=D1_TES AND D_E_L_E_T_<>'*'),
		'LIVRO CIAP'=(SELECT F4_CIAP FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=D1_TES AND D_E_L_E_T_<>'*'),
		F1_TPFRETE AS 'TIPO FRETE',
		0 as 'BASE IRRF',
		0 AS 'ALIQ IRRF',
		0 AS 'VLR IRRF', 
		0 AS 'BASE PIS/COF',
		0 AS 'ALIQ RET PIS',             
		0 AS 'VLR RET PIS',    
		0 AS 'ALQ RET COF',
		0 AS 'VLR RET COF',
		0 AS 'ALQ INSS',            
		0 AS 'VLR INSS',
		0 AS 'VLR RET CSLL',
		'HISTORICO'='',
		'MANIFESTADO'=ISNULL((SELECT TOP 1 CASE WHEN C00_CODEVE='3' THEN 'SIM' ELSE '' END FROM C00010 WHERE C00_FILIAL=F1_FILIAL AND C00_NUMNFE=F1_DOC AND C00_SERNFE=F1_SERIE AND SUBSTRING(C00_DTEMI,1,6)=SUBSTRING(F1_EMISSAO,1,6) AND D_E_L_E_T_<>'*'),''),
		'' AS 'NF FRETE',
		0 AS 'VLR FRETE',
		0 AS 'ICMS NA NF',
		'DESMEM.IT.ATF'=CASE WHEN (SELECT F4_BENSATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=D1_TES AND D_E_L_E_T_<>'*')='1' THEN 'SIM' ELSE 'NAO' END,
		'' 'ESPECIE NA NF',
		0 'QTD.VOLUME'
		
FROM	SF1010 SF1,
		SA2010 SA2,
		SB1010 SB1,
		SD1010 SD1

WHERE	SF1.F1_DTDIGIT BETWEEN @MV_PAR01 AND @MV_PAR02
		AND SF1.F1_FILIAL=SD1.D1_FILIAL
		AND SF1.F1_DOC=SD1.D1_DOC
		AND SF1.F1_SERIE=SD1.D1_SERIE
		AND SF1.F1_FORNECE=SD1.D1_FORNECE
		AND SF1.F1_LOJA=SD1.D1_LOJA
		AND SD1.D1_TES='271'
		AND SD1.D1_COD=SB1.B1_COD
		AND SB1.B1_FILIAL=''
		AND SF1.F1_FORNECE=SA2.A2_COD
		AND SF1.F1_LOJA=SA2.A2_LOJA
		AND SA2.A2_FILIAL=''
		AND SD1.D_E_L_E_T_<>'*'
		AND SB1.D_E_L_E_T_<>'*'
		AND SA2.D_E_L_E_T_<>'*' 
		AND SF1.D_E_L_E_T_<>'*' 

ORDER BY F1_DTDIGIT,F1_DOC,F1_SERIE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM #PRINCIPAL ORDER BY 'DATA DIGITACAO',DOCUMENTO,SERIE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
END
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IF @MV_PAR03=2 BEGIN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	FT_FILIAL FILIAL,
		F2_TIPO TIPO,
		F2_DOC DOCUMENTO,
		F2_SERIE SERIE,
		FT_NFORI NF_ORIGEM,
		FT_CHVNFE 'CHAVE ELETRONICA',
		FT_CLIEFOR FORNECEDOR,
		FT_LOJA LOJA,
		A1_NOME 'RAZAO SOCIAL',
		SA1.A1_CGC 'CNPJ',
		SA1.A1_INSCR 'INSCRICAO ESTADUAL',
		SA1.A1_INSCRM 'INSCRICAO MUNICIPAL',
		SA1.A1_EST 'ESTADO',
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF2.F2_EMISSAO),103) 'DATA EMISSAO',
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF2.F2_EMISSAO),103) 'DATA DIGITACAO',
		SFT.FT_ITEM 'ITEM',
		SFT.FT_PRODUTO 'PRODUTO',
		SB1.B1_DESC 'DESCRICAO',
		SB1.B1_POSIPI 'NCM',
		SB1.B1_TIPO 'TIPO PROD',
		'SITTRIB'=(SELECT F4_SITTRIB FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		SB1.B1_LOCPAD AS 'ALMOX',
		SFT.FT_TES 'TES',
		SFT.FT_CFOP 'CFOP',
		'FINALIDADE'=(SELECT F4_TEXTO FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		B1_UM 'UM',
		FT_QUANT AS 'QUANTIDADE',
		FT_PRCUNIT AS 'VL UNIT',
		FT_QUANT*FT_PRCUNIT AS 'VL TOTAL',
		FT_VALCONT AS 'VL CONTABIL',
		FT_BASEICM AS 'BASE ICMS/ISS',
		FT_ALIQICM AS 'ALIQ.ICMS/ISS',
		FT_VALICM AS 'VL ICMS/ISS',
		FT_ISENICM AS 'VL ISENTO ICMS',
		FT_OUTRICM AS 'VL OUTROS ICMS',
		FT_BASEIPI AS 'BASE IPI',
		FT_ALIQIPI AS 'ALIQ.IPI',
		FT_VALIPI AS 'VL IPI',
		FT_ISENIPI AS 'VL ISENTO IPI',
		FT_OUTRIPI AS 'VL OUTROS IPI',
		FT_CTIPI AS 'COD TRIB.IPI',
		FT_BASERET AS 'BASE ICMS ST',
		FT_ICMSRET AS 'AL ICMS ST',
		FT_ALIQSOL AS 'ALIQ.ICMS ST',
		FT_OBSERV AS 'OBSERVACAO',
		FT_TIPO AS 'FT TIPO',
		F2_ESPECIE AS 'ESPECIE',
		FT_ICMSCOM AS 'ICMS COM',
		FT_ICMSDIF AS 'ICMS DIF',
		FT_IPIOBS AS 'IPI OBS',
		FT_OBSICM AS 'OBS ICMS',
		FT_OBSSOL AS 'OBS ST',
		'' AS 'ITEM PC',
		'NUM SC'='',
		'ITEM SC'='',
		D2_PEDIDO AS 'PEDIDO COMPRA',
		'VENCIMENTO'='',
		'' AS 'OBSERVACAO PEDIDO',
		'' AS 'OBSERVACAO PEDIDO2',
		D2_CONTA AS 'C.ORCAMENTARIA',
		'DESCRICAO C.ORCAMENTARIA'=ISNULL((SELECT CT1_DESC01 FROM CT1010 WHERE CT1_FILIAL='' AND CT1_CONTA=D2_CONTA AND D_E_L_E_T_<>'*'),''),
		'' AS 'CC',
		'' AS 'DESCRICAO CC',
		'TIPO MOV'='SAIDA',
		FT_FRETE AS 'VALOR FRETE',
		FT_SEGURO AS 'VALOR SEGURO',
		FT_DESPESA AS 'VALOR DESPESA',
		FT_DESCONT AS 'VALOR DESCONTO',
		FT_BASEPIS AS 'BASE PIS',
		FT_ALIQPIS AS 'ALIQ.PIS',
		FT_VALPIS AS 'VLR PIS',
		FT_BASECOF AS 'BASE COF',
		FT_ALIQCOF AS 'ALIQ.COF',
		FT_VALCOF AS 'VLR COF',
		FT_CSTPIS AS 'CST PIS',
		FT_CSTCOF AS 'CST COF',
		'MOV.ESTOQUE'=(SELECT F4_ESTOQUE FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'GERA FINANCEIRO'=(SELECT F4_DUPLIC FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'AT.ATIVO'=(SELECT F4_ATUATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'LIVRO CIAP'=(SELECT F4_CIAP FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		F2_TPFRETE AS 'TIPO FRETE',
		0 as 'BASE IRRF',
		0 AS 'ALIQ IRRF',
		0 AS 'VLR IRRF', 
		0 AS 'BASE PIS/COF',
		0 AS 'ALIQ RET PIS',             
		0 AS 'VLR RET PIS',    
		0 AS 'ALQ RET COF',
		0 AS 'VLR RET COF',
		0 AS 'ALQ INSS',            
		0 AS 'VLR INSS',
		0 AS 'VLR RET CSLL',
		'HISTORICO'='',
		'' AS 'MANIFESTADO',
		'' AS 'NF FRETE',
		0 AS 'VLR FRETE',
		0 AS 'ICMS NA NF',
		'DESMEM.IT.ATF'=CASE WHEN (SELECT F4_BENSATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*')='1' THEN 'SIM' ELSE 'NAO' END,
		F2_ESPECI1 'ESPECIE NA NF',
		F2_VOLUME1 'QTD.VOLUME'
		INTO #PRINCIPAL2

FROM	SFT010 SFT,
		SF2010 SF2,
		SA1010 SA1,
		SB1010 SB1,
		SD2010 SD2

WHERE	FT_TIPOMOV='S' 
		AND SF2.F2_TIPO NOT IN ('B','D')
		AND SF2.F2_DOC=SFT.FT_NFISCAL
		AND SF2.F2_EMISSAO BETWEEN @MV_PAR01 AND @MV_PAR02
		AND SF2.F2_FILIAL=SFT.FT_FILIAL
		AND SF2.F2_CLIENTE=SFT.FT_CLIEFOR
		AND SF2.F2_EMISSAO=SFT.FT_EMISSAO
		AND SFT.FT_PRODUTO=SB1.B1_COD
		AND SFT.FT_PRODUTO=SD2.D2_COD
		AND SF2.F2_FILIAL=SD2.D2_FILIAL
		AND SFT.FT_NFISCAL=SD2.D2_DOC
		AND SF2.F2_CLIENTE=SD2.D2_CLIENTE
		AND SFT.FT_SERIE=SD2.D2_SERIE
		AND SFT.FT_ITEM=SD2.D2_ITEM
		AND SB1.B1_FILIAL=''
		AND SFT.FT_CLIEFOR=SA1.A1_COD
		AND SFT.FT_LOJA=SA1.A1_LOJA
		AND SA1.A1_FILIAL=''
		AND SD2.D_E_L_E_T_<>'*'
		AND SFT.D_E_L_E_T_<>'*' 
		AND SB1.D_E_L_E_T_<>'*'
		AND SA1.D_E_L_E_T_<>'*' 
		AND SF2.D_E_L_E_T_<>'*' 

ORDER BY F2_EMISSAO,F2_DOC,F2_SERIE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO #PRINCIPAL2
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	FT_FILIAL FILIAL,
		F2_TIPO TIPO,
		F2_DOC DOCUMENTO,
		F2_SERIE SERIE,
		FT_NFORI NF_ORIGEM,
		FT_CHVNFE 'CHAVE ELETRONICA',
		FT_CLIEFOR FORNECEDOR,
		FT_LOJA LOJA,
		A2_NOME 'RAZAO SOCIAL',
		SA2.A2_CGC 'CNPJ',
		SA2.A2_INSCR 'INSCRICAO ESTADUAL',
		SA2.A2_INSCRM 'INSCRICAO MUNICIPAL',
		SA2.A2_EST 'ESTADO',
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF2.F2_EMISSAO),103) 'DATA EMISSAO',
		CONVERT(VARCHAR(10),CONVERT(DATETIME,SF2.F2_EMISSAO),103) 'DATA DIGITACAO',
		SFT.FT_ITEM 'ITEM',
		SFT.FT_PRODUTO 'PRODUTO',
		SB1.B1_DESC 'DESCRICAO',
		SB1.B1_POSIPI 'NCM',
		SB1.B1_TIPO 'TIPO PROD',
		'SITTRIB'=(SELECT F4_SITTRIB FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		SB1.B1_LOCPAD AS 'ALMOX',
		SFT.FT_TES 'TES',
		SFT.FT_CFOP 'CFOP',
		'FINALIDADE'=(SELECT F4_TEXTO FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		B1_UM 'UM',
		FT_QUANT AS 'QUANTIDADE',
		FT_PRCUNIT AS 'VL UNIT',
		FT_QUANT*FT_PRCUNIT AS 'VL TOTAL',
		FT_VALCONT AS 'VL CONTABIL',
		FT_BASEICM AS 'BASE ICMS/ISS',
		FT_ALIQICM AS 'ALIQ.ICMS/ISS',
		FT_VALICM AS 'VL ICMS/ISS',
		FT_ISENICM AS 'VL ISENTO ICMS',
		FT_OUTRICM AS 'VL OUTROS ICMS',
		FT_BASEIPI AS 'BASE IPI',
		FT_ALIQIPI AS 'ALIQ.IPI',
		FT_VALIPI AS 'VL IPI',
		FT_ISENIPI AS 'VL ISENTO IPI',
		FT_OUTRIPI AS 'VL OUTROS IPI',
		FT_CTIPI AS 'COD TRIB.IPI',
		FT_BASERET AS 'BASE ICMS ST',
		FT_ICMSRET AS 'AL ICMS ST',
		FT_ALIQSOL AS 'ALIQ.ICMS ST',
		FT_OBSERV AS 'OBSERVACAO',
		FT_TIPO AS 'FT TIPO',
		F2_ESPECIE AS 'ESPECIE',
		FT_ICMSCOM AS 'ICMS COM',
		FT_ICMSDIF AS 'ICMS DIF',
		FT_IPIOBS AS 'IPI OBS',
		FT_OBSICM AS 'OBS ICMS',
		FT_OBSSOL AS 'OBS ST',
		'' AS 'ITEM PC',
		'NUM SC'='',
		'ITEM SC'='',
		D2_PEDIDO AS 'PEDIDO COMPRA',
		'VENCIMENTO'='',
		'' AS 'OBSERVACAO PEDIDO',
		'' AS 'OBSERVACAO PEDIDO2',
		D2_CONTA AS 'C.ORCAMENTARIA',
		'DESCRICAO C.ORCAMENTARIA'=ISNULL((SELECT CT1_DESC01 FROM CT1010 WHERE CT1_FILIAL='' AND CT1_CONTA=D2_CONTA AND D_E_L_E_T_<>'*'),''),
		'' AS 'CC',
		'' AS 'DESCRICAO CC',
		'TIPO MOV'='SAIDA',
		FT_FRETE AS 'VALOR FRETE',
		FT_SEGURO AS 'VALOR SEGURO',
		FT_DESPESA AS 'VALOR DESPESA',
		FT_DESCONT AS 'VALOR DESCONTO',
		FT_BASEPIS AS 'BASE PIS',
		FT_ALIQPIS AS 'ALIQ.PIS',
		FT_VALPIS AS 'VLR PIS',
		FT_BASECOF AS 'BASE COF',
		FT_ALIQCOF AS 'ALIQ.COF',
		FT_VALCOF AS 'VLR COF',
		FT_CSTPIS AS 'CST PIS',
		FT_CSTCOF AS 'CST COF',
		'MOV.ESTOQUE'=(SELECT F4_ESTOQUE FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'GERA FINANCEIRO'=(SELECT F4_DUPLIC FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'AT.ATIVO'=(SELECT F4_ATUATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		'LIVRO CIAP'=(SELECT F4_CIAP FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*'),
		F2_TPFRETE AS 'TIPO FRETE',
		0 as 'BASE IRRF',
		0 AS 'ALIQ IRRF',
		0 AS 'VLR IRRF', 
		0 AS 'BASE PIS/COF',
		0 AS 'ALIQ RET PIS',             
		0 AS 'VLR RET PIS',    
		0 AS 'ALQ RET COF',
		0 AS 'VLR RET COF',
		0 AS 'ALQ INSS',            
		0 AS 'VLR INSS',
		0 AS 'VLR RET CSLL',
		'HISTORICO'='',
		'' AS 'MANIFESTADO',
		'' AS 'NF FRETE',
		0  AS 'VLR FRETE',
		0  AS 'ICMS NA NF',
		'DESMEM.IT.ATF'=CASE WHEN (SELECT F4_BENSATF FROM SF4010 WHERE F4_FILIAL='' AND F4_CODIGO=FT_TES AND D_E_L_E_T_<>'*')='1' THEN 'SIM' ELSE 'NAO' END,
		F2_ESPECI1 'ESPECIE NA NF',
		F2_VOLUME1 'QTD.VOLUME'


FROM	SFT010 SFT,
		SF2010 SF2,
		SA2010 SA2,
		SB1010 SB1,
		SD2010 SD2

WHERE	FT_TIPOMOV='S' 
		AND SF2.F2_TIPO IN ('B','D')
		AND SF2.F2_DOC=SFT.FT_NFISCAL
		AND SF2.F2_EMISSAO BETWEEN @MV_PAR01 AND @MV_PAR02
		AND SF2.F2_FILIAL=SFT.FT_FILIAL
		AND SF2.F2_CLIENTE=SFT.FT_CLIEFOR
		AND SF2.F2_EMISSAO=SFT.FT_EMISSAO
		AND SFT.FT_PRODUTO=SB1.B1_COD
		AND SF2.F2_CLIENTE=SD2.D2_CLIENTE
		AND SFT.FT_PRODUTO=SD2.D2_COD
		AND SF2.F2_FILIAL=SD2.D2_FILIAL
		AND SFT.FT_NFISCAL=SD2.D2_DOC
		AND SFT.FT_SERIE=SD2.D2_SERIE
		AND SFT.FT_ITEM=SD2.D2_ITEM
		AND SB1.B1_FILIAL=''
		AND SFT.FT_CLIEFOR=SA2.A2_COD
		AND SFT.FT_LOJA=SA2.A2_LOJA
		AND SA2.A2_FILIAL=''
		AND SD2.D_E_L_E_T_<>'*'
		AND SFT.D_E_L_E_T_<>'*' 
		AND SB1.D_E_L_E_T_<>'*'
		AND SA2.D_E_L_E_T_<>'*' 
		AND SF2.D_E_L_E_T_<>'*' 

ORDER BY F2_EMISSAO,F2_DOC,F2_SERIE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM #PRINCIPAL2 ORDER BY 'DATA DIGITACAO',DOCUMENTO,SERIE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
END
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET NOCOUNT OFF
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------