-------------------------------------------------------------------------------------
-- ARRUMA ROBO DE REMESSA COM NUMERAÇÃO DESCONTROLADA 
-------------------------------------------------------------------------------------

--// DISTRIBUIDORA
SELECT 'DIST' AS EMP ,EA_FILIAL,EA_NUM,EA_PARCELA, E1_EMISSAO, E1_VENCREA,  EA.D_E_L_E_T_ , A3_NOME AS VEND, EA_NUMBOR
FROM SEA010 EA 
INNER JOIN SE1010 E1 ON E1_NUM = EA_NUM AND E1_FILIAL = EA_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1_PARCELA = EA_PARCELA AND E1_NUMBCO = EA_NOSSONU AND E1.D_E_L_E_T_ = '' AND E1.E1_BAIXA =''
INNER JOIN SA3010 A3 ON E1_VEND1 = A3_COD
WHERE EA.D_E_L_E_T_ = '*'
AND EA_DATABOR > '20210900'
UNION
--// DERIVADOS
SELECT 'DERI' AS EMP ,EA_FILIAL,EA_NUM,EA_PARCELA, E1_EMISSAO, E1_VENCREA,  EA.D_E_L_E_T_ , A3_NOME AS VEND , EA_NUMBOR
FROM SEA020 EA 
INNER JOIN SE1020 E1 ON E1_NUM = EA_NUM AND E1_FILIAL = EA_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1_PARCELA = EA_PARCELA AND E1_NUMBCO = EA_NOSSONU AND E1.D_E_L_E_T_ = '' AND E1.E1_BAIXA =''
INNER JOIN SA3010 A3 ON E1_VEND1 = A3_COD
WHERE EA.D_E_L_E_T_ = '*'
AND EA_DATABOR > '20210900'
ORDER BY EMP,EA_FILIAL,E1_EMISSAO

// ///////////////////////////////////////////////////