


DECLARE @INIEMP VARCHAR(2) 
SET @INIEMP  = '01'
DECLARE @FIMEMP VARCHAR(2)
SET @FIMEMP  = '01'
DECLARE @INIFIL VARCHAR(2) 
SET @INIFIL  = '04'
DECLARE @FIMFIL VARCHAR(2)
SET @FIMFIL  = '04'
DECLARE @INIDTE DATE
SET @INIDTE  = '20210122'
DECLARE @FIMDTE DATE
SET @FIMDTE  = '20210122'
SELECT * FROM (    
	SELECT '01' AS EMPRESA , FILIAL  , PRODUTO, SUM(VALOR) AS VALOR, SUM(FATURADO) AS FATURADO, SUM(ABERTO) AS ABERTO, SUM(CONSFINAL) AS 'CONSFINAL', SUM(BANDBRANCA) AS 'BANDBRANCA' , SUM(BANDEIRADO) AS 'BANDEIRADO', SUM(PRODRURAL) AS PRODRURAL, SUM(REVENDEDOR) AS REVENDEDOR , SUM(AVISTA) AS AVISTA, SUM(UMDIA) AS UMDIA , SUM(LONGOPRAZO) AS LONGOPRAZO     
	FROM (	
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , SUM(C6_VALOR) AS 'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR', 0 AS  'AVISTA' , 0 AS  'UMDIA', 0 AS  'LONGOPRAZO' FROM SC5010   
		INNER JOIN SC6010 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6010.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5010.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL , C6_PRODUTO 		
		UNION ALL  -- ##################################################################################
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO',    
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'F2' OR A1_TIPO+A1_BANDEIR = 'F ' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'CONSFINAL',
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'S2'  OR  A1_TIPO+A1_BANDEIR = 'S ' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'BANDBRANCA',
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'S1' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'BANDEIRADO',		
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'L2' OR A1_TIPO+A1_BANDEIR = 'L ' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'PRODRURAL',		
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'R2' OR A1_TIPO+A1_BANDEIR = 'R ' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'REVENDEDOR',	0 AS  'AVISTA' , 0 AS  'UMDIA',0 AS  'LONGOPRAZO'
		FROM SC5010   
		INNER JOIN SC6010 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6010.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		INNER JOIN SA1010 ON C5_CLIENTE = A1_COD AND C5_LOJACLI = A1_LOJA AND SA1010.D_E_L_E_T_ <> '*'
		WHERE SC5010.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL, C6_PRODUTO , A1_TIPO+A1_BANDEIR				
		UNION ALL -- ######################################################################################		
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', SUM(C6_VALOR) AS 'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , 0 AS  'AVISTA' , 0 AS  'UMDIA', 0 AS  'LONGOPRAZO' FROM SC5010   
		INNER JOIN SC6010 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND  C6_NOTA <>'' AND SC6010.D_E_L_E_T_ <> '*'  AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5010.D_E_L_E_T_ <> '*'
		AND C5_NOTA <> ''
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL , C6_PRODUTO 	 		
		UNION ALL -- ########################################################################################
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', SUM(C6_VALOR) AS 'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , 0 AS  'AVISTA' , 0 AS  'UMDIA', 0 AS  'LONGOPRAZO' FROM SC5010   
		INNER JOIN SC6010 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND  C6_NOTA = '' AND SC6010.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5010.D_E_L_E_T_ <> '*'
		AND C5_NOTA = ''
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL , C6_PRODUTO 		
		UNION ALL --&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , SUM(C6_VALOR) AS 'AVISTA', 0 AS  'UMDIA', 0 AS  'LONGOPRAZO'  FROM SC5010  
		INNER JOIN SC6010 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6010.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5010.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		AND C5_CONDPAG = '000'
		GROUP BY C5_FILIAL , C6_PRODUTO 		
		UNION ALL --&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , 0 AS  'AVISTA', SUM(C6_VALOR) AS 'UMDIA', 0 AS  'LONGOPRAZO'  FROM SC5010  
		INNER JOIN SC6010 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6010.D_E_L_E_T_ <> '*' 		AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667')
		WHERE SC5010.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL  
		AND C5_CONDPAG = '001'
		GROUP BY C5_FILIAL , C6_PRODUTO 			
		UNION ALL --&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , 0 AS  'AVISTA', 0 AS  'UMDIA', SUM(C6_VALOR) AS 'LONGOPRAZO'  FROM SC5010  
		INNER JOIN SC6010 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6010.D_E_L_E_T_ <> '*' 		AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5010.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		AND C5_CONDPAG NOT IN  ('000','001')
		GROUP BY C5_FILIAL , C6_PRODUTO 					
	) AS POSICAOA
	GROUP BY FILIAL, PRODUTO	 	 
UNION ALL -- ииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииии
	SELECT '02' AS EMPRESA , FILIAL  , PRODUTO, SUM(VALOR) AS VALOR, SUM(FATURADO) AS FATURADO, SUM(ABERTO) AS ABERTO, SUM(CONSFINAL) AS 'CONSFINAL', SUM(BANDBRANCA) AS 'BANDBRANCA' , SUM(BANDEIRADO) AS BANDEIRADO, SUM(PRODRURAL) AS PRODRURAL, SUM(REVENDEDOR) AS REVENDEDOR  ,  SUM(AVISTA) AS AVISTA, SUM(UMDIA) AS UMDIA , SUM(LONGOPRAZO) AS LONGOPRAZO 
	FROM (	
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , SUM(C6_VALOR) AS 'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR', 0 AS  'AVISTA' , 0 AS  'UMDIA', 0 AS  'LONGOPRAZO' FROM SC5020  
		INNER JOIN SC6020 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6020.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5020.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL , C6_PRODUTO 
		UNION ALL  -- ##################################################################################
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO', 
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'F2' OR A1_TIPO+A1_BANDEIR = 'F ' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'CONSFINAL',
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'S2'  OR  A1_TIPO+A1_BANDEIR = 'S ' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'BANDBRANCA',
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'S1' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'BANDEIRADO',		
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'L2' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'PRODRURAL',		
		CASE 
				WHEN A1_TIPO+A1_BANDEIR = 'R2' THEN SUM(C6_VALOR)  
				ELSE 0 
				END
				AS 'REVENDEDOR'	,  0 AS  'AVISTA' , 0 AS  'UMDIA', 0 AS  'LONGOPRAZO'
		FROM SC5020   
		INNER JOIN SC6020 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6020.D_E_L_E_T_ <> '*' 		AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		INNER JOIN SA1010 ON C5_CLIENTE = A1_COD AND C5_LOJACLI = A1_LOJA AND SA1010.D_E_L_E_T_ <> '*'
		WHERE SC5020.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL, C6_PRODUTO , A1_TIPO+A1_BANDEIR
		UNION ALL -- ######################################################################################
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', SUM(C6_VALOR) AS 'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR',  0 AS  'AVISTA' , 0 AS  'UMDIA', 0 AS  'LONGOPRAZO' FROM SC5020  
		INNER JOIN SC6020 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND  C6_NOTA <>'' AND SC6020.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5020.D_E_L_E_T_ <> '*'
		AND C5_NOTA <> ''
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL , C6_PRODUTO 
		UNION ALL -- ########################################################################################
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', SUM(C6_VALOR) AS 'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' ,  0 AS  'AVISTA' , 0 AS  'UMDIA', 0 AS  'LONGOPRAZO'FROM SC5020  
		INNER JOIN SC6020 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND  C6_NOTA = '' AND SC6020.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5020.D_E_L_E_T_ <> '*'
		AND C5_NOTA = ''
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		GROUP BY C5_FILIAL , C6_PRODUTO 		
		UNION ALL --&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , SUM(C6_VALOR) AS 'AVISTA', 0 AS  'UMDIA', 0 AS  'LONGOPRAZO'  FROM SC5020  
		INNER JOIN SC6020 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6020.D_E_L_E_T_ <> '*'AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5020.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		AND C5_CONDPAG = '000'
		GROUP BY C5_FILIAL , C6_PRODUTO 		
		UNION ALL 
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , 0 AS  'AVISTA', SUM(C6_VALOR) AS 'UMDIA', 0 AS  'LONGOPRAZO'  FROM SC5020  
		INNER JOIN SC6020 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6020.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5020.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		AND C5_CONDPAG = '001'
		GROUP BY C5_FILIAL , C6_PRODUTO 			
		UNION ALL 
		SELECT C5_FILIAL AS FILIAL, C6_PRODUTO AS 'PRODUTO' , 0 AS  'VALOR', 0 AS  'FATURADO', 0 AS  'ABERTO' , 0 AS   'CONSFINAL',  0 AS   'BANDBRANCA', 0 AS   'BANDEIRADO', 0 AS   'PRODRURAL', 0 AS   'REVENDEDOR' , 0 AS  'AVISTA', 0 AS  'UMDIA', SUM(C6_VALOR) AS 'LONGOPRAZO'  FROM SC5020  
		INNER JOIN SC6020 ON C6_NUM = C5_NUM AND C6_FILIAL = C5_FILIAL AND C6_SERIE = C5_SERIE AND SC6020.D_E_L_E_T_ <> '*' AND C6_ENTREG BETWEEN @INIDTE AND @FIMDTE AND C6_CF IN ('5656','5655','6656','6655','5659','6659','5667','6667') 
		WHERE SC5020.D_E_L_E_T_ <> '*'
		AND C5_FILIAL BETWEEN @INIFIL AND @FIMFIL 
		AND C5_CONDPAG NOT IN  ('000','001')
		GROUP BY C5_FILIAL , C6_PRODUTO 		
	) AS POSICAOB
	GROUP BY FILIAL, PRODUTO	
) AS POSICAO2	
WHERE EMPRESA BETWEEN @INIEMP AND @FIMEMP
ORDER BY EMPRESA, FILIAL, PRODUTO


SELECT RA_NASC, * FROM SRA010 WHERE RA_NOME LIKE '%ERNESTA%'
