-- GERA SENHA PARA RHONLINE 

SELECT RA.RA_MAT, RA.RA_NOME ,
		(SUBSTRING(RA.RA_NASC , 3, 2)+ 
		 SUBSTRING(RA.RA_ADMISSA , 7, 2)+ 
		 SUBSTRING(RA.RA_CIC , 10, 2)  ) AS SENHA
FROM SRA010 RA 
WHERE  RA.RA_DEMISSA ='' 
ORDER BY RA.RA_NOME

-- CONSULTA SENHA USUARIOS

SELECT   RA.RA_MAT, RA.RA_NOME,RA.RA_CIC,	
		(SUBSTRING(RA.RA_NASC , 3, 2)+ 
		 SUBSTRING(RA.RA_ADMISSA , 7, 2)+ 
		 SUBSTRING(RA.RA_CIC , 10, 2)  ) AS SENHA FROM SRA010 RA WHERE RA.RA_NOME LIKE '%TANIS%' 
UNION
SELECT RA.RA_MAT, RA.RA_NOME,		
		(SUBSTRING(RA.RA_NASC , 3, 2)+ 
		 SUBSTRING(RA.RA_ADMISSA , 7, 2)+ 
		 SUBSTRING(RA.RA_CIC , 10, 2)  ) AS SENHA FROM SRA020 RA WHERE RA.RA_NOME LIKE '%GIVA%' 
UNION 
SELECT RA.RA_MAT, RA.RA_NOME,		
		(SUBSTRING(RA.RA_NASC , 3, 2)+ 
		 SUBSTRING(RA.RA_ADMISSA , 7, 2)+ 
		 SUBSTRING(RA.RA_CIC , 10, 2)  ) AS SENHA FROM SRA030 RA WHERE RA.RA_NOME LIKE '%GIVA%'
UNION
SELECT RA.RA_MAT, RA.RA_NOME,		
		(SUBSTRING(RA.RA_NASC , 3, 2)+ 
		 SUBSTRING(RA.RA_ADMISSA , 7, 2)+ 
		 SUBSTRING(RA.RA_CIC , 10, 2)  ) AS SENHA FROM SRA040 RA WHERE RA.RA_NOME LIKE '%GIVA%'
UNION 
SELECT RA.RA_MAT, RA.RA_NOME,		
		(SUBSTRING(RA.RA_NASC , 3, 2)+ 
		 SUBSTRING(RA.RA_ADMISSA , 7, 2)+ 
		 SUBSTRING(RA.RA_CIC , 10, 2)  ) AS SENHA FROM SRA050 RA WHERE RA.RA_NOME LIKE '%GIVA%'