--// DISTRIBUIDORA
SELECT '01' AS EMP, EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME 
FROM SEA010 EA 
INNER JOIN SE1010 E1 ON E1_BAIXA = '' AND  E1_NUM = EA_NUM AND E1_FILIAL = EA_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1_PARCELA = EA_PARCELA AND E1_NUMBCO = EA_NOSSONU AND E1.D_E_L_E_T_ <> '' AND E1_BAIXA = ''
INNER JOIN SA3010 A3 ON E1_VEND1 = A3_COD
WHERE EA.D_E_L_E_T_ <> '*'
AND EA_DATABOR > '20210800'
AND EA_CART  = 'R'
AND EA_PREFIXO  = '1'
UNION
--// DERIVADOS
SELECT 'DERI' AS EMP ,EA_FILIAL,EA_NUM,EA_PARCELA, E1_EMISSAO, E1_VENCREA,  EA.D_E_L_E_T_ , A3_NOME AS VEND , EA_NUMBOR
FROM SEA020 EA 
INNER JOIN SE1020 E1 ON E1_BAIXA = '' AND E1_NUM = EA_NUM AND E1_FILIAL = EA_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1_PARCELA = EA_PARCELA AND E1_NUMBCO = EA_NOSSONU AND E1.D_E_L_E_T_ = '' AND E1_BAIXA = ''
INNER JOIN SA3010 A3 ON E1_VEND1 = A3_COD
WHERE EA.D_E_L_E_T_ <> '*'
AND EA_DATABOR > '20210800'
AND EA_CART  = 'R'
AND EA_PREFIXO  = '1'
ORDER BY EMP,EA_FILIAL,E1_VENCREA
--// EMPREENDIMENTOS
SELECT 'EMPR' AS EMP ,EA_FILIAL,EA_NUM,EA_PARCELA, E1_EMISSAO, E1_VENCREA,  EA.D_E_L_E_T_ , A3_NOME AS VEND , EA_NUMBOR
FROM SEA070 EA 
INNER JOIN SE1070 E1 ON E1_BAIXA = '' AND E1_NUM = EA_NUM AND E1_FILIAL = EA_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1_PARCELA = EA_PARCELA AND E1_NUMBCO = EA_NOSSONU AND E1.D_E_L_E_T_ = '' AND E1_BAIXA = ''
INNER JOIN SA3010 A3 ON E1_VEND1 = A3_COD
WHERE EA.D_E_L_E_T_ <> '*'
AND EA_CART  = 'R'
AND EA_DATABOR > '20210800'
AND EA_PREFIXO  = '1'
ORDER BY EMP,EA_FILIAL,E1_VENCREA


SELECT '01' AS EMP, EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME 
FROM SE1010 E1 
	INNER JOIN SEA010 EA ON E1_NUM = EA_NUM AND EA_FILIAL = E1_FILIAL AND E1_PREFIXO = EA_PREFIXO AND EA.D_E_L_E_T_ ='' AND E1_PARCELA = EA_PARCELA AND E1_PREFIXO = '1' AND EA.EA_DATABOR > '20201101'
	INNER JOIN SA3010 A3 ON A3_COD = E1_VEND1 AND A3.D_E_L_E_T_ <> '*'
WHERE E1.D_E_L_E_T_ <> '*' 
AND E1_NUMBCO <> ''
AND E1_BAIXA = ''
GROUP BY EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME
HAVING COUNT(E1_NUMBCO) > 1
UNION
SELECT '02' AS EMP, EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME 
FROM SE1020 E1 
	INNER JOIN SEA020 EA ON E1_NUM = EA_NUM AND EA_FILIAL = E1_FILIAL AND E1_PREFIXO = EA_PREFIXO AND EA.D_E_L_E_T_ ='' AND E1_PARCELA = EA_PARCELA AND E1_PREFIXO = '1' AND EA.EA_DATABOR > '20211101'
	INNER JOIN SA3010 A3 ON A3_COD = E1_VEND1 AND A3.D_E_L_E_T_ <> '*'
WHERE E1.D_E_L_E_T_ <> '*' 
AND E1_NUMBCO <> ''
AND E1_BAIXA = ''
GROUP BY EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME
HAVING COUNT(E1_NUMBCO) > 1
UNION 
SELECT '07' AS EMP, EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME 
FROM SE1070 E1 
	INNER JOIN SEA070 EA ON E1_NUM = EA_NUM AND EA_FILIAL = E1_FILIAL AND E1_PREFIXO = EA_PREFIXO AND EA.D_E_L_E_T_ ='' AND E1_PARCELA = EA_PARCELA AND E1_PREFIXO = '1' AND EA.EA_DATABOR > '20211101'
	INNER JOIN SA3010 A3 ON A3_COD = E1_VEND1 AND A3.D_E_L_E_T_ <> '*'
WHERE E1.D_E_L_E_T_ <> '*' 
AND E1_NUMBCO <> ''
AND E1_BAIXA = ''
GROUP BY EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME
HAVING COUNT(E1_NUMBCO) > 1


SELECT '01' AS EMP, EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME 
FROM SEA010 EA
INNER JOIN SE1010 E1 ON E1_NUM = EA_NUM AND EA_FILIAL = E1_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1.D_E_L_E_T_ ='' AND E1_PARCELA = EA_PARCELA 
INNER JOIN SA3010 A3 ON A3_COD = E1_VEND1 AND A3.D_E_L_E_T_ <> '*'
WHERE EA_FILIAL+EA_NOSSONU IN (
	SELECT E1_FILIAL+E1_NUMBCO 
	FROM SE1010
	WHERE E1_DATABOR >= '20211110'
	AND EA.D_E_L_E_T_ <> '*'
	GROUP BY E1_FILIAL,E1_NUMBCO, E1_PREFIXO  
	HAVING COUNT(E1_NUMBCO) > 1)
UNION 
SELECT '02' AS EMP, EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME 
FROM SEA020 
INNER JOIN SE1020 E1 ON E1_NUM = EA_NUM AND EA_FILIAL = E1_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1.D_E_L_E_T_ ='' AND E1_PARCELA = EA_PARCELA 
INNER JOIN SA3010 A3 ON A3_COD = E1_VEND1 AND A3.D_E_L_E_T_ <> '*'
WHERE EA_FILIAL+EA_NOSSONU IN (
	SELECT E1_FILIAL+E1_NUMBCO 
	FROM SE1020
	WHERE E1_DATABOR >= '20211110'
	AND D_E_L_E_T_ <> '*'
	GROUP BY E1_FILIAL,E1_NUMBCO, E1_PREFIXO  
	HAVING COUNT(E1_NUMBCO) > 1)
UNION 
SELECT '07' AS EMP, EA_FILIAL,EA_NUMBOR,EA_PREFIXO,EA_NUM,EA_PARCELA,EA_TIPO,EA_FORNECE,EA_LOJA,E1_NOMCLI,E1_EMISSAO, E1_VENCREA,A3_NOME 
FROM SEA070 
INNER JOIN SE1070 E1 ON E1_NUM = EA_NUM AND EA_FILIAL = E1_FILIAL AND E1_PREFIXO = EA_PREFIXO AND E1.D_E_L_E_T_ ='' AND E1_PARCELA = EA_PARCELA 
INNER JOIN SA3010 A3 ON A3_COD = E1_VEND1 AND A3.D_E_L_E_T_ <> '*'
WHERE EA_FILIAL+EA_NOSSONU IN (
	SELECT E1_FILIAL+E1_NUMBCO 
	FROM SE1070
	WHERE E1_DATABOR >= '20211110'
	AND D_E_L_E_T_ <> '*'
	GROUP BY E1_FILIAL,E1_NUMBCO, E1_PREFIXO  
	HAVING COUNT(E1_NUMBCO) > 1)

SELECT * FROM SEA010 WHERE EA_NUMBOR = 'TSTB72'	
	
	
