/*
////////////////////////////////////////////////////////////////
// - QUERY USADO PARA PREENCHER OS CAMPOS FALTANTES NA 
//   ROTINA 53 PARA O PORTAL RH ONLINE
//
// - ENRICO AUGUSTO - 24/09/2018 
////////////////////////////////////////////////////////////////

*/



UPDATE RD0010 SET RD0_PORTAL = '000001', RD0_MAT = ( SELECT RA_MAT FROM SRA010 WHERE RA_NOME LIKE RD0_NOME) WHERE 
RD0_MAT = '' AND D_E_L_E_T_ <> '*';

UPDATE RD0020 SET RD0_PORTAL = '000001', RD0_MAT = ( SELECT RA_MAT FROM SRA020 WHERE RA_NOME LIKE LTRIM(RD0_NOME)) WHERE 
RD0_MAT = '' AND D_E_L_E_T_ <> '*';

UPDATE RD0030 SET RD0_PORTAL = '000001', RD0_MAT = ( SELECT RA_MAT FROM SRA030 WHERE RA_NOME LIKE RD0_NOME) WHERE 
RD0_MAT = ''  AND D_E_L_E_T_ <> '*';

--UPDATE RD0040 SET RD0_PORTAL = '000001', RD0_MAT = ( SELECT RA_MAT FROM SRA040 WHERE RA_NOME LIKE RD0_NOME) WHERE 
--RD0_MAT = '' AND D_E_L_E_T_ <> '*';

UPDATE RD0050 SET RD0_PORTAL = '000001', RD0_MAT = ( SELECT RA_MAT FROM SRA050 WHERE RA_NOME LIKE RD0_NOME) WHERE 
RD0_MAT = '' AND D_E_L_E_T_ <> '*';

